import type { DiagnosticFollowUpQuestion, MovementTestDefinition } from '@/lib/diagnostics/types'

export const DIAGNOSTIC_INSTRUCTION_VERSION = 'diagnostic-v1-one-angle-2026-04-23'

export const COMMON_DIAGNOSTIC_PROMPTS = [
  'My knees hurt in squats',
  'I feel unstable',
  'I feel slow',
  'My shoulder feels tight',
  'I get tired too quickly',
  'I feel weak on one side',
  'I cannot jump well',
  'My back feels uncomfortable when I lift',
] as const

export const DIAGNOSTIC_DISCLAIMER =
  'This is movement and performance guidance, not a medical diagnosis. Stop if symptoms feel sharp, worsening, swollen, numb, locked, or unsafe.'

export const MOVEMENT_TESTS: MovementTestDefinition[] = [
  {
    id: 'bodyweight_squat',
    displayName: 'Bodyweight squat',
    bodyRegion: 'lower_body',
    requiredView: 'front',
    instructions: [
      'Stand tall with feet around shoulder width.',
      'Perform 5 slow bodyweight squats.',
      'Keep the full body visible from head to feet.',
      'Move only within a comfortable range.',
    ],
    cameraSetup: [
      'Use the back camera.',
      'Place the phone 2 to 3 meters in front of you.',
      'Keep feet, knees, hips, trunk, and head in frame.',
    ],
    repCount: 5,
    contraindicationHints: ['Do not continue if squat pain is sharp, worsening, or changes how you bear weight.'],
    compatibleComplaintBuckets: [
      'lower_body_mobility',
      'lower_body_stability',
      'lower_body_pain_with_movement',
      'asymmetry',
      'technique_breakdown',
      'unknown_general',
    ],
    expectedAnalysisMetrics: ['depthScore', 'kneeTrackingScore', 'hipControlScore', 'ankleMobilityIndicator', 'trunkControlScore'],
    scoringLogicReferences: ['knee_valgus', 'shallow_squat', 'rounded_spine', 'trunk_collapse'],
    passFailLogic: 'Front-view squat is used for knee tracking, symmetry, stance, and basic control in V1.',
  },
  {
    id: 'split_squat',
    displayName: 'Split squat',
    bodyRegion: 'lower_body',
    requiredView: 'front',
    instructions: [
      'Set one foot forward and one foot back.',
      'Perform 3 controlled reps on the side that feels worse first.',
      'Use a chair or wall nearby if balance feels uncertain.',
    ],
    cameraSetup: ['Use the back camera.', 'Place the phone in front so both legs are visible.', 'Record only one side in V1.'],
    repCount: 3,
    contraindicationHints: ['Skip this test if you cannot comfortably control the bottom position.'],
    compatibleComplaintBuckets: ['lower_body_stability', 'asymmetry', 'lower_body_pain_with_movement', 'technique_breakdown'],
    expectedAnalysisMetrics: ['kneeTrackingScore', 'hipControlScore', 'stabilityScore', 'asymmetryIndicator'],
    scoringLogicReferences: ['knee_valgus', 'hip_drop', 'trunk_collapse'],
  },
  {
    id: 'forward_lunge',
    displayName: 'Forward lunge',
    bodyRegion: 'lower_body',
    requiredView: 'front',
    instructions: ['Step forward into a controlled lunge.', 'Perform 3 reps on the side that feels more limited.', 'Return to standing between reps.'],
    cameraSetup: ['Use the back camera.', 'Face the phone so knee tracking and balance are visible.', 'Keep the whole body in frame.'],
    repCount: 3,
    contraindicationHints: ['Avoid this test if stepping forward creates sharp pain or a giving-way feeling.'],
    compatibleComplaintBuckets: ['lower_body_stability', 'balance_and_control', 'asymmetry', 'technique_breakdown'],
    expectedAnalysisMetrics: ['kneeTrackingScore', 'hipControlScore', 'balanceScore', 'stabilityScore'],
    scoringLogicReferences: ['knee_valgus', 'hip_drop', 'narrow_base'],
  },
  {
    id: 'single_leg_balance_hold',
    displayName: 'Single-leg balance hold',
    bodyRegion: 'lower_body',
    requiredView: 'front',
    instructions: ['Stand on the side that feels less stable.', 'Hold for 20 seconds.', 'Keep arms relaxed and eyes forward.'],
    cameraSetup: ['Use the back camera.', 'Place the phone in front.', 'Keep head, hips, knees, and feet visible.'],
    durationSeconds: 20,
    contraindicationHints: ['Use support nearby. Stop if balance feels unsafe.'],
    compatibleComplaintBuckets: ['balance_and_control', 'lower_body_stability', 'asymmetry'],
    expectedAnalysisMetrics: ['balanceScore', 'stabilityScore', 'hipControlScore', 'asymmetryIndicator'],
    scoringLogicReferences: ['hip_drop', 'head_falling_over', 'narrow_base'],
  },
  {
    id: 'step_down',
    displayName: 'Step-down',
    bodyRegion: 'lower_body',
    requiredView: 'front',
    instructions: ['Stand on a low step.', 'Tap the opposite heel lightly to the floor.', 'Perform 3 slow reps on the side that feels worse.'],
    cameraSetup: ['Use the back camera.', 'Face the phone.', 'Use a low, stable step only.'],
    repCount: 3,
    contraindicationHints: ['Do not use a high step. Stop if knee pain is sharp or unstable.'],
    compatibleComplaintBuckets: ['lower_body_stability', 'lower_body_pain_with_movement', 'balance_and_control', 'asymmetry'],
    expectedAnalysisMetrics: ['kneeTrackingScore', 'hipControlScore', 'balanceScore', 'asymmetryIndicator'],
    scoringLogicReferences: ['knee_valgus', 'hip_drop', 'trunk_collapse'],
  },
  {
    id: 'overhead_reach',
    displayName: 'Overhead reach',
    bodyRegion: 'upper_body',
    requiredView: 'side',
    instructions: ['Stand tall with ribs relaxed.', 'Reach both arms overhead slowly 3 times.', 'Do not force through pain.'],
    cameraSetup: ['Use the back camera.', 'Place the phone side-on.', 'Keep hips, ribs, shoulders, and hands visible.'],
    repCount: 3,
    contraindicationHints: ['Stop if shoulder symptoms are sharp, radiating, or worsening.'],
    compatibleComplaintBuckets: ['upper_body_mobility', 'upper_body_pain_with_movement', 'technique_breakdown'],
    expectedAnalysisMetrics: ['shoulderMobilityScore', 'trunkControlScore', 'asymmetryIndicator'],
    scoringLogicReferences: ['low_contact_point', 'shoulder_tilt', 'forward_head'],
  },
  {
    id: 'wall_slide',
    displayName: 'Wall slide',
    bodyRegion: 'upper_body',
    requiredView: 'front',
    instructions: ['Stand with back near a wall if available.', 'Slide arms upward and downward 3 times.', 'Keep the range comfortable.'],
    cameraSetup: ['Use the back camera.', 'Place the phone in front.', 'Keep the full upper body visible.'],
    repCount: 3,
    contraindicationHints: ['Stop if symptoms travel down the arm or include numbness.'],
    compatibleComplaintBuckets: ['upper_body_mobility', 'upper_body_pain_with_movement', 'asymmetry'],
    expectedAnalysisMetrics: ['shoulderMobilityScore', 'trunkControlScore', 'asymmetryIndicator'],
    scoringLogicReferences: ['shoulder_tilt', 'forward_head', 'low_contact_point'],
  },
  {
    id: 'push_up_pattern_check',
    displayName: 'Push-up pattern check',
    bodyRegion: 'upper_body',
    requiredView: 'side',
    instructions: ['Use an incline, knees, or floor version that feels easy.', 'Perform 3 controlled reps.', 'Keep ribs and hips moving together.'],
    cameraSetup: ['Use the back camera.', 'Place the phone side-on.', 'Make sure head, shoulders, hips, knees, and hands are visible.'],
    repCount: 3,
    contraindicationHints: ['Skip this test if wrist, shoulder, or back pain is sharp.'],
    compatibleComplaintBuckets: ['upper_body_pain_with_movement', 'technique_breakdown', 'asymmetry'],
    expectedAnalysisMetrics: ['trunkControlScore', 'shoulderMobilityScore', 'stabilityScore'],
    scoringLogicReferences: ['trunk_collapse', 'forward_head', 'shoulder_tilt'],
  },
  {
    id: 'vertical_jump',
    displayName: 'Vertical jump',
    bodyRegion: 'lower_body',
    requiredView: 'side',
    instructions: ['Perform 3 comfortable vertical jumps.', 'Land quietly and reset between reps.', 'Do not chase maximum height in V1.'],
    cameraSetup: ['Use the back camera.', 'Place the phone side-on.', 'Keep full body and landing in frame.'],
    repCount: 3,
    contraindicationHints: ['Do not jump if pain is present or landing feels unsafe.'],
    compatibleComplaintBuckets: ['speed_and_explosiveness', 'technique_breakdown', 'fatigue_and_recovery'],
    expectedAnalysisMetrics: ['landingControlScore', 'explosivenessIndicator', 'trunkControlScore', 'kneeTrackingScore'],
    scoringLogicReferences: ['stiff_landing', 'knee_valgus', 'trunk_collapse'],
  },
  {
    id: 'pogo_hops',
    displayName: 'Pogo hops',
    bodyRegion: 'lower_body',
    requiredView: 'front',
    instructions: ['Perform 10 small, low pogo hops.', 'Keep hops quiet and springy.', 'Stop if pain appears.'],
    cameraSetup: ['Use the back camera.', 'Face the phone.', 'Keep feet, knees, hips, and trunk visible.'],
    repCount: 10,
    contraindicationHints: ['Skip if calf, Achilles, knee, or foot pain is present.'],
    compatibleComplaintBuckets: ['speed_and_explosiveness', 'fatigue_and_recovery', 'balance_and_control'],
    expectedAnalysisMetrics: ['landingControlScore', 'stabilityScore', 'explosivenessIndicator', 'tempoControlScore'],
    scoringLogicReferences: ['stiff_landing', 'stiff_knees', 'narrow_base'],
  },
  {
    id: 'basic_hip_hinge',
    displayName: 'Basic hip hinge',
    bodyRegion: 'lower_back',
    requiredView: 'side',
    instructions: ['Stand tall and push hips back like closing a car door.', 'Perform 5 slow hinge reps.', 'Keep the movement pain-free and light.'],
    cameraSetup: ['Use the back camera.', 'Place the phone side-on.', 'Keep head, trunk, hips, knees, and feet visible.'],
    repCount: 5,
    contraindicationHints: ['Stop if back discomfort is sharp, radiating, or worsening.'],
    compatibleComplaintBuckets: ['lower_body_mobility', 'lower_body_pain_with_movement', 'technique_breakdown'],
    expectedAnalysisMetrics: ['hingePatternScore', 'trunkControlScore', 'hipControlScore'],
    scoringLogicReferences: ['rounded_spine', 'trunk_collapse', 'stiff_knees'],
  },
  {
    id: 'toe_touch_hamstring_hinge',
    displayName: 'Toe touch / hamstring hinge screen',
    bodyRegion: 'hamstring',
    requiredView: 'side',
    instructions: ['Stand tall and slowly reach toward the toes.', 'Return to standing and repeat 3 times.', 'Only use a comfortable range.'],
    cameraSetup: ['Use the back camera.', 'Place the phone side-on.', 'Keep the full body visible.'],
    repCount: 3,
    contraindicationHints: ['Stop if symptoms radiate, tingle, or feel sharp.'],
    compatibleComplaintBuckets: ['lower_body_mobility', 'lower_body_pain_with_movement', 'unknown_general'],
    expectedAnalysisMetrics: ['hingePatternScore', 'trunkControlScore', 'ankleMobilityIndicator'],
    scoringLogicReferences: ['rounded_spine', 'trunk_collapse', 'stiff_knees'],
  },
]

export const FOLLOW_UP_QUESTIONS: Record<string, DiagnosticFollowUpQuestion> = {
  movement_story: {
    key: 'movement_story',
    prompt: 'Tell me a little more about what you notice.',
    type: 'open_text',
    required: true,
    helperText: 'Mention where you feel it, what it feels like, and whether one side feels different.',
  },
  context_story: {
    key: 'context_story',
    prompt: 'When does it show up most?',
    type: 'open_text',
    required: true,
    helperText: 'You can include the movement, sport or gym context, load, speed, fatigue, and how long it has been happening.',
  },
  safety_story: {
    key: 'safety_story',
    prompt: 'Before I choose the screen, any swelling, locking, numbness, sharp or worsening pain, or trouble bearing weight?',
    type: 'open_text',
    required: true,
    helperText: 'Say “none” if none of those are present. CREEDA will stop the test if the answer suggests a serious symptom.',
  },
}

export function getMovementTestDefinition(testId: string) {
  return MOVEMENT_TESTS.find((test) => test.id === testId) || null
}
