import type { Environment, SupportedSport } from '@/lib/product/types'
import { makeSeries, warmupBase } from '@/lib/product/exercises/shared'

const allSports: SupportedSport[] = ['general_fitness', 'cricket', 'football', 'badminton', 'athletics']

export const mobilityRecoveryRehabCatalog = [
  ...makeSeries(
    {
      ...warmupBase({
        family: 'hip-opener',
        subcategory: 'movement_prep',
        movementPattern: 'hip_mobility',
        primaryMuscles: ['glutes', 'hip_flexors'],
        secondaryMuscles: ['adductors', 'obliques'],
        jointsInvolved: ['hips', 'spine'],
        sportTags: allSports,
        movementQualityTags: ['hip_rotation', 'front_leg_access'],
        description: 'Dynamic hip-opening prep to unlock squat depth, stride length, and rotational access.',
      }),
    },
    [
      { slug: 'worlds-greatest-stretch', name: "World's Greatest Stretch" },
      { slug: 'spiderman-lunge-rotation', name: 'Spiderman Lunge Rotation' },
      { slug: 'shinbox-switch', name: 'Shinbox Switch', category: 'mobility', suitableBlocks: ['warmup', 'recovery'] },
      { slug: 'hip-airplane-supported', name: 'Supported Hip Airplane', category: 'mobility', suitableBlocks: ['warmup', 'rehab'], trainingIntent: ['mobility', 'stability', 'movement_prep'] },
      { slug: 'adductor-rockback', name: 'Adductor Rockback', category: 'mobility', suitableBlocks: ['warmup', 'cooldown', 'rehab'] },
      { slug: 'lateral-lunge-pry', name: 'Lateral Lunge Pry', category: 'mobility', suitableBlocks: ['warmup', 'accessory'] },
    ]
  ),
  ...makeSeries(
    {
      ...warmupBase({
        family: 'ankle-prep',
        subcategory: 'ankle_mobility',
        movementPattern: 'ankle_mobility',
        primaryMuscles: ['calves', 'tibialis'],
        secondaryMuscles: ['foot_intrinsics'],
        jointsInvolved: ['ankles', 'toes'],
        sportTags: allSports,
        movementQualityTags: ['ankle_dorsiflexion', 'foot_control'],
        description: 'Ankle prep and foot control for cleaner deceleration, squatting, and court contacts.',
      }),
    },
    [
      { slug: 'ankle-rocker', name: 'Ankle Rocker' },
      { slug: 'knee-to-wall-ankle-mobility', name: 'Knee-to-Wall Ankle Mobility', category: 'mobility', suitableBlocks: ['warmup', 'rehab', 'recovery'] },
      { slug: 'toe-yoga', name: 'Toe Yoga', category: 'warmup', subcategory: 'foot_activation', trainingIntent: ['warmup', 'movement_prep', 'stability'] },
      { slug: 'heel-toe-walk', name: 'Heel-Toe Walk', category: 'warmup', subcategory: 'foot_activation', trainingIntent: ['warmup', 'movement_prep', 'stability'], suitableBlocks: ['warmup'] },
      { slug: 'ankle-cars', name: 'Ankle CARs', category: 'mobility', suitableBlocks: ['warmup', 'recovery', 'rehab'] },
      { slug: 'banded-ankle-mobility', name: 'Banded Ankle Mobility', category: 'mobility', equipmentRequired: ['band'], suitableBlocks: ['warmup', 'rehab'] },
    ]
  ),
  ...makeSeries(
    {
      ...warmupBase({
        family: 'thoracic-opener',
        subcategory: 'thoracic_mobility',
        movementPattern: 'thoracic_rotation',
        primaryMuscles: ['upper_back'],
        secondaryMuscles: ['obliques', 'serratus'],
        jointsInvolved: ['thoracic_spine', 'shoulders'],
        sportTags: allSports,
        movementQualityTags: ['thoracic_rotation', 'rib_motion'],
        description: 'Thoracic mobility work to improve overhead mechanics, rotation, and breathing position.',
      }),
    },
    [
      { slug: 'open-book', name: 'Open Book' },
      { slug: 'thread-the-needle', name: 'Thread the Needle' },
      { slug: 'quadruped-t-spine-rotation', name: 'Quadruped T-Spine Rotation', category: 'mobility', suitableBlocks: ['warmup', 'recovery', 'rehab'] },
      { slug: 'bench-t-spine-extension', name: 'Bench T-Spine Extension', category: 'mobility', equipmentRequired: ['bench'], environment: ['gym', 'home'], suitableBlocks: ['warmup', 'cooldown'] },
      { slug: 'wall-thoracic-rotation', name: 'Wall Thoracic Rotation', category: 'mobility', suitableBlocks: ['warmup', 'recovery'] },
    ]
  ),
  ...makeSeries(
    {
      family: 'shoulder-prep',
      description: 'Shoulder prep for scapular rhythm, cuff activation, and more repeatable overhead mechanics.',
      category: 'warmup',
      subcategory: 'shoulder_prep',
      movementPattern: 'scapular_control',
      trainingIntent: ['warmup', 'movement_prep', 'stability'],
      primaryMuscles: ['serratus', 'rotator_cuff'],
      secondaryMuscles: ['mid_back', 'triceps'],
      jointsInvolved: ['shoulders', 'thoracic_spine'],
      difficulty: 'beginner',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['bodyweight'],
      environment: ['gym', 'home', 'field', 'court'] as Environment[],
      unilateralOrBilateral: 'mixed',
      impactLevel: 'low',
      intensityProfile: 'low',
      estimatedDurationSeconds: 75,
      defaultPrescription: { sets: 1, reps: '8-10', restSeconds: 15, intensity: 'prep', rpe: 3 },
      coachingCues: ['Make the shoulder blade glide, not shrug.', 'Stop the drill before pinchy front-shoulder sensation appears.'],
      instructions: [
        'Start from a long spine with the ribs quiet.',
        'Move the arm and shoulder blade together through the planned range.',
        'Finish each rep smoothly and reset to quality.',
      ],
      commonMistakes: ['Turning the drill into a neck shrug.', 'Forcing range that the shoulder does not own.'],
      regressions: ['wall-slide'],
      progressions: ['band-no-money', 'prone-y-t-w'],
      substitutions: ['face-pull', 'scap-push-up'],
      contraindications: ['acute_shoulder_pain'],
      injuryConstraints: ['shoulder_irritability'],
      sorenessConstraints: ['shoulder_domsy'],
      fatigueConstraints: [],
      readinessSuitability: ['low', 'moderate', 'high'],
      goalTags: ['injury_reduction', 'athletic_performance', 'return_to_play'],
      sportTags: allSports,
      positionTags: ['fast bowler', 'wicketkeeper', 'goalkeeper', 'doubles', 'thrower'],
      fitStartTags: ['shoulder_resilience'],
      recoveryTags: ['joint_prep'],
      rehabTags: ['shoulder_resilience'],
      movementQualityTags: ['scapular_control', 'cuff_activation'],
      suitableBlocks: ['warmup', 'rehab'],
    },
    [
      { slug: 'wall-slide', name: 'Wall Slide' },
      { slug: 'scap-push-up', name: 'Scap Push-Up' },
      { slug: 'band-no-money', name: 'Band No-Money', equipmentRequired: ['band'], environment: ['gym', 'home'], category: 'warmup' },
      { slug: 'prone-y-t-w', name: 'Prone Y-T-W', category: 'mobility', suitableBlocks: ['warmup', 'rehab'] },
      { slug: 'standing-cable-external-rotation', name: 'Standing Cable External Rotation', equipmentRequired: ['cable'], environment: ['gym'], category: 'rehab', suitableBlocks: ['rehab', 'recovery'] },
    ]
  ),
  ...makeSeries(
    {
      family: 'hamstring-mobility',
      description: 'Posterior-chain mobility for stride mechanics and smoother hinge positions.',
      category: 'mobility',
      subcategory: 'hamstring_mobility',
      movementPattern: 'posterior_chain_length',
      trainingIntent: ['mobility', 'flexibility', 'recovery'],
      primaryMuscles: ['hamstrings'],
      secondaryMuscles: ['calves', 'glutes'],
      jointsInvolved: ['hips', 'knees', 'ankles'],
      difficulty: 'beginner',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['bodyweight'],
      environment: ['gym', 'home', 'field'] as Environment[],
      unilateralOrBilateral: 'mixed',
      impactLevel: 'low',
      intensityProfile: 'low',
      estimatedDurationSeconds: 90,
      defaultPrescription: { sets: 2, reps: '5-8/side', restSeconds: 20, intensity: 'gentle range', rpe: 3 },
      coachingCues: ['Move slowly enough that the nervous system trusts the range.', 'Aim for length with breath, not strain.'],
      instructions: [
        'Choose a variation that lets you feel a stretch without pain or nerve symptoms.',
        'Exhale into the range and own the position briefly.',
        'Return smoothly and repeat without forcing depth.',
      ],
      commonMistakes: ['Bouncing into the stretch.', 'Chasing toe touch by rounding aggressively.'],
      regressions: ['supine-band-hamstring-stretch'],
      progressions: ['hinge-flow-reach', 'single-leg-toe-reach'],
      substitutions: ['adductor-rockback', 'ankle-rocker'],
      contraindications: ['acute_hamstring_strain'],
      injuryConstraints: ['sciatic_irritability', 'acute_hamstring_strain'],
      sorenessConstraints: ['posterior_chain_domsy'],
      fatigueConstraints: [],
      readinessSuitability: ['low', 'moderate', 'high'],
      goalTags: ['mobility', 'flexibility', 'recovery', 'injury_reduction'],
      sportTags: allSports,
      positionTags: ['fast bowler', 'winger', 'sprinter'],
      fitStartTags: ['posterior_chain', 'mobility'],
      recoveryTags: ['post_training_reset'],
      rehabTags: ['hamstring_mobility'],
      movementQualityTags: ['posterior_chain_length'],
      suitableBlocks: ['warmup', 'cooldown', 'recovery', 'rehab'],
    },
    [
      { slug: 'supine-band-hamstring-stretch', name: 'Supine Band Hamstring Stretch', equipmentRequired: ['band'], environment: ['gym', 'home'] },
      { slug: 'hinge-flow-reach', name: 'Hinge Flow Reach', category: 'mobility', suitableBlocks: ['warmup', 'cooldown'] },
      { slug: 'single-leg-toe-reach', name: 'Single-Leg Toe Reach', category: 'mobility', unilateralOrBilateral: 'unilateral', suitableBlocks: ['warmup', 'recovery'] },
      { slug: 'doorway-hamstring-floss', name: 'Doorway Hamstring Floss', category: 'recovery', suitableBlocks: ['recovery', 'cooldown', 'rehab'] },
      { slug: 'standing-hamstring-sweep', name: 'Standing Hamstring Sweep', category: 'warmup', suitableBlocks: ['warmup'] },
    ]
  ),
  ...makeSeries(
    {
      family: 'breathing-reset',
      description: 'Breathing drills to improve downregulation, trunk position, and post-session recovery quality.',
      category: 'recovery',
      subcategory: 'breathing',
      movementPattern: 'breathing',
      trainingIntent: ['recovery', 'breathing', 'cooldown'],
      primaryMuscles: ['diaphragm'],
      secondaryMuscles: ['obliques', 'pelvic_floor'],
      jointsInvolved: ['rib_cage', 'spine'],
      difficulty: 'beginner',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['bodyweight'],
      environment: ['gym', 'home', 'field', 'court', 'track'] as Environment[],
      unilateralOrBilateral: 'mixed',
      impactLevel: 'low',
      intensityProfile: 'low',
      estimatedDurationSeconds: 180,
      defaultPrescription: { sets: 1, reps: '2-4 min', durationSeconds: 180, restSeconds: 0, intensity: 'downshift', rpe: 2 },
      coachingCues: ['Let the exhale be longer than the inhale.', 'Feel the ribs drop instead of lifting the chest.'],
      instructions: [
        'Set up in a supported position that allows the neck and jaw to relax.',
        'Breathe in quietly through the nose and exhale slowly through the mouth or nose.',
        'Continue until heart rate, posture, and perceived tension settle.',
      ],
      commonMistakes: ['Forcing giant inhalations.', 'Turning the drill into another effort task.'],
      regressions: ['seated-box-breathing'],
      progressions: ['90-90-breathing-reach', 'crocodile-breathing'],
      substitutions: ['easy-walk-downshift'],
      contraindications: [],
      injuryConstraints: [],
      sorenessConstraints: [],
      fatigueConstraints: [],
      readinessSuitability: ['low', 'moderate', 'high'],
      goalTags: ['recovery', 'match_readiness', 'stress_management'],
      sportTags: allSports,
      positionTags: [],
      fitStartTags: ['stress_management', 'recovery'],
      recoveryTags: ['parasympathetic_shift', 'sleep_support'],
      rehabTags: ['pain_downregulation'],
      movementQualityTags: ['stacked_breathing'],
      suitableBlocks: ['recovery', 'cooldown'],
    },
    [
      { slug: 'seated-box-breathing', name: 'Seated Box Breathing', category: 'recovery' },
      { slug: '90-90-breathing', name: '90/90 Breathing', category: 'recovery' },
      { slug: '90-90-breathing-reach', name: '90/90 Breathing Reach', category: 'recovery' },
      { slug: 'crocodile-breathing', name: 'Crocodile Breathing', category: 'cooldown', suitableBlocks: ['cooldown', 'recovery'] },
      { slug: 'paced-nasal-breathing', name: 'Paced Nasal Breathing', category: 'cooldown', suitableBlocks: ['cooldown', 'recovery'] },
      { slug: 'easy-walk-downshift', name: 'Easy Walk Downshift', category: 'recovery', subcategory: 'active_recovery', trainingIntent: ['recovery', 'cooldown', 'aerobic_base'], primaryMuscles: ['full_body'], secondaryMuscles: ['diaphragm'], jointsInvolved: ['ankles', 'hips', 'rib_cage'], defaultPrescription: { sets: 1, reps: '5-10 min', durationSeconds: 300, restSeconds: 0, intensity: 'easy', rpe: 2 }, equipmentRequired: ['bodyweight'], environment: ['field', 'court', 'track', 'home', 'gym'] },
    ]
  ),
  ...makeSeries(
    {
      family: 'soft-tissue-reset',
      description: 'Soft-tissue and low-intensity recovery work to reduce tone and restore next-session quality.',
      category: 'recovery',
      subcategory: 'soft_tissue',
      movementPattern: 'soft_tissue',
      trainingIntent: ['recovery', 'mobility'],
      primaryMuscles: ['full_body'],
      secondaryMuscles: ['diaphragm'],
      jointsInvolved: ['full_body'],
      difficulty: 'beginner',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['foam_roller'],
      environment: ['gym', 'home'] as Environment[],
      unilateralOrBilateral: 'mixed',
      impactLevel: 'low',
      intensityProfile: 'low',
      estimatedDurationSeconds: 120,
      defaultPrescription: { sets: 1, reps: '45-60s/area', durationSeconds: 60, restSeconds: 10, intensity: 'release', rpe: 2 },
      coachingCues: ['Melt onto the implement instead of fighting it.', 'Use slow breaths to turn the tone down.'],
      instructions: [
        'Set the target area on the implement or ball.',
        'Roll or hold slowly until the tissue tension reduces slightly.',
        'Move off before numbness or sharp discomfort develops.',
      ],
      commonMistakes: ['Grinding aggressively into sensitive spots.', 'Treating recovery work like a pain contest.'],
      regressions: ['calf-smash'],
      progressions: ['lat-smash-breathing'],
      substitutions: ['breathing-reset', 'mobility-flow-cooldown'],
      contraindications: ['acute_inflammation'],
      injuryConstraints: ['acute_bruising'],
      sorenessConstraints: [],
      fatigueConstraints: [],
      readinessSuitability: ['low', 'moderate', 'high'],
      goalTags: ['recovery', 'injury_reduction'],
      sportTags: allSports,
      positionTags: [],
      fitStartTags: ['recovery'],
      recoveryTags: ['tone_reduction', 'circulation'],
      rehabTags: [],
      movementQualityTags: ['tissue_quality'],
      suitableBlocks: ['recovery', 'cooldown'],
    },
    [
      { slug: 'calf-smash', name: 'Calf Smash', equipmentRequired: ['foam_roller'], environment: ['gym', 'home'] },
      { slug: 'quad-roll', name: 'Quad Roll', equipmentRequired: ['foam_roller'], environment: ['gym', 'home'] },
      { slug: 'glute-ball-release', name: 'Glute Ball Release', equipmentRequired: ['massage_ball'], environment: ['gym', 'home'] },
      { slug: 'lat-smash-breathing', name: 'Lat Smash Breathing', equipmentRequired: ['foam_roller'], environment: ['gym', 'home'] },
      { slug: 'plantar-ball-roll', name: 'Plantar Ball Roll', equipmentRequired: ['massage_ball'], environment: ['gym', 'home'] },
    ]
  ),
  ...makeSeries(
    {
      family: 'cooldown-flow',
      description: 'End-of-session cooldown flow to shift from work output toward recovery readiness.',
      category: 'cooldown',
      subcategory: 'mobility_flow',
      movementPattern: 'cooldown_flow',
      trainingIntent: ['cooldown', 'mobility', 'recovery'],
      primaryMuscles: ['full_body'],
      secondaryMuscles: ['diaphragm'],
      jointsInvolved: ['hips', 'spine', 'shoulders', 'ankles'],
      difficulty: 'beginner',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['bodyweight'],
      environment: ['gym', 'home', 'field', 'court', 'track'] as Environment[],
      unilateralOrBilateral: 'mixed',
      impactLevel: 'low',
      intensityProfile: 'low',
      estimatedDurationSeconds: 240,
      defaultPrescription: { sets: 1, reps: '3-5 min', durationSeconds: 240, restSeconds: 0, intensity: 'decompress', rpe: 2 },
      coachingCues: ['Move slower than you think you need to.', 'Treat the cooldown like a bridge to the next session, not extra work.'],
      instructions: [
        'Choose a calm pace and link each movement with your breathing.',
        'Visit the biggest tightness zones from the session without forcing range.',
        'Finish feeling more settled than when you started.',
      ],
      commonMistakes: ['Rushing through the flow while still amped up.', 'Adding intensity instead of removing it.'],
      regressions: ['seated-breathing-reset'],
      progressions: ['mobility-flow-cooldown'],
      substitutions: ['easy-walk-downshift', 'soft-tissue-reset'],
      contraindications: [],
      injuryConstraints: ['acute_pain_flare'],
      sorenessConstraints: [],
      fatigueConstraints: [],
      readinessSuitability: ['low', 'moderate', 'high'],
      goalTags: ['recovery', 'mobility', 'match_readiness'],
      sportTags: allSports,
      positionTags: [],
      fitStartTags: ['recovery'],
      recoveryTags: ['post_session_downshift'],
      rehabTags: [],
      movementQualityTags: ['downregulation'],
      suitableBlocks: ['cooldown', 'recovery'],
    },
    [
      { slug: 'mobility-flow-cooldown', name: 'Mobility Flow Cooldown' },
      { slug: 'hips-and-ribs-reset', name: 'Hips and Ribs Reset' },
      { slug: 'hamstrings-and-calf-reset', name: 'Hamstrings and Calf Reset' },
      { slug: 'shoulders-and-t-spine-reset', name: 'Shoulders and T-Spine Reset' },
      { slug: 'seated-breathing-reset', name: 'Seated Breathing Reset', category: 'cooldown', subcategory: 'breathing' },
    ]
  ),
  ...makeSeries(
    {
      family: 'shoulder-rehab',
      description: 'Shoulder rehab work emphasizing cuff loading, scapular control, and return-to-throw tolerance.',
      category: 'rehab',
      subcategory: 'shoulder_rehab',
      movementPattern: 'shoulder_rehab',
      trainingIntent: ['rehab', 'return_to_play', 'stability'],
      primaryMuscles: ['rotator_cuff', 'serratus'],
      secondaryMuscles: ['mid_back', 'triceps'],
      jointsInvolved: ['shoulders', 'thoracic_spine'],
      difficulty: 'beginner',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['band'],
      environment: ['gym', 'home'] as Environment[],
      unilateralOrBilateral: 'mixed',
      impactLevel: 'low',
      intensityProfile: 'low',
      estimatedDurationSeconds: 90,
      defaultPrescription: { sets: 3, reps: '8-12/side', restSeconds: 30, intensity: 'pain-free control', rpe: 4 },
      coachingCues: ['The rep only counts if the shoulder stays calm.', 'Control the blade and cuff together instead of chasing fatigue.'],
      instructions: [
        'Set the trunk and shoulder blade in a comfortable stacked position.',
        'Move through the planned range with zero pinchy front-shoulder sensation.',
        'Stop the set if technique or symptom quality changes.',
      ],
      commonMistakes: ['Using too much resistance too early.', 'Shrugging or arching to finish the rep.'],
      regressions: ['isometric-external-rotation'],
      progressions: ['wall-slide-lift-off', 'prone-trap-raise', 'return-to-throw-step-behind'],
      substitutions: ['face-pull', 'scap-push-up'],
      contraindications: ['acute_shoulder_pain'],
      injuryConstraints: ['shoulder_irritability', 'throwing_pain'],
      sorenessConstraints: ['shoulder_domsy'],
      fatigueConstraints: [],
      readinessSuitability: ['low', 'moderate', 'high'],
      goalTags: ['rehab', 'return_to_play', 'injury_reduction'],
      sportTags: ['cricket', 'badminton', 'football', 'athletics', 'general_fitness'],
      positionTags: ['fast bowler', 'wicketkeeper', 'goalkeeper', 'doubles', 'thrower'],
      fitStartTags: ['shoulder_resilience'],
      recoveryTags: ['joint_calm'],
      rehabTags: ['shoulder_resilience', 'rotator_cuff', 'scapular_control'],
      movementQualityTags: ['scapular_control', 'cuff_tolerance'],
      suitableBlocks: ['rehab', 'recovery'],
    },
    [
      { slug: 'isometric-external-rotation', name: 'Isometric External Rotation', equipmentRequired: ['band'], environment: ['gym', 'home'] },
      { slug: 'band-external-rotation', name: 'Band External Rotation', equipmentRequired: ['band'], environment: ['gym', 'home'] },
      { slug: 'sidelying-external-rotation', name: 'Sidelying External Rotation', equipmentRequired: ['dumbbell'], environment: ['gym', 'home'] },
      { slug: 'wall-slide-lift-off', name: 'Wall Slide Lift-Off', equipmentRequired: ['bodyweight'], environment: ['gym', 'home'] },
      { slug: 'prone-trap-raise', name: 'Prone Trap Raise', equipmentRequired: ['bench'], environment: ['gym', 'home'] },
      { slug: 'return-to-throw-step-behind', name: 'Return-to-Throw Step-Behind', category: 'rehab', subcategory: 'return_to_play', trainingIntent: ['rehab', 'return_to_play', 'sport_drill'], equipmentRequired: ['med_ball'], environment: ['field', 'gym'], readinessSuitability: ['moderate', 'high'], impactLevel: 'moderate' },
    ]
  ),
  ...makeSeries(
    {
      family: 'ankle-rehab',
      description: 'Ankle and foot rehab progressions for stiffness, proprioception, and court/field return.',
      category: 'rehab',
      subcategory: 'ankle_rehab',
      movementPattern: 'ankle_rehab',
      trainingIntent: ['rehab', 'return_to_play', 'stability'],
      primaryMuscles: ['calves', 'foot_intrinsics'],
      secondaryMuscles: ['tibialis', 'peroneals'],
      jointsInvolved: ['ankles', 'toes'],
      difficulty: 'beginner',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['bodyweight'],
      environment: ['gym', 'home', 'court', 'field'] as Environment[],
      unilateralOrBilateral: 'mixed',
      impactLevel: 'low',
      intensityProfile: 'low',
      estimatedDurationSeconds: 75,
      defaultPrescription: { sets: 3, reps: '8-12/side', restSeconds: 30, intensity: 'controlled reload', rpe: 4 },
      coachingCues: ['Let the foot do the work before the hip takes over.', 'Pain-free quality beats range or speed every time.'],
      instructions: [
        'Create a stable foot tripod before adding movement.',
        'Move through the pattern under control while keeping the ankle stacked.',
        'Advance speed or instability only when the contact feels calm.',
      ],
      commonMistakes: ['Letting the ankle roll while chasing reps.', 'Progressing to jumps before strength and balance are ready.'],
      regressions: ['single-leg-balance-support'],
      progressions: ['single-leg-balance-reach', 'line-hop-stick', 'return-to-shuffle'],
      substitutions: ['march-carry', 'double-leg-calf-raise'],
      contraindications: ['acute_ankle_pain'],
      injuryConstraints: ['ankle_irritability', 'achilles_irritability'],
      sorenessConstraints: ['calf_domsy'],
      fatigueConstraints: [],
      readinessSuitability: ['low', 'moderate', 'high'],
      goalTags: ['rehab', 'return_to_play', 'injury_reduction', 'agility'],
      sportTags: ['football', 'badminton', 'athletics', 'cricket', 'general_fitness'],
      positionTags: ['fullback', 'winger', 'singles', 'doubles', 'sprinter'],
      fitStartTags: ['ankle_stability'],
      recoveryTags: ['joint_calm'],
      rehabTags: ['ankle_stability', 'proprioception', 'return_to_cutting'],
      movementQualityTags: ['foot_control', 'frontal_plane_control'],
      suitableBlocks: ['rehab', 'recovery'],
    },
    [
      { slug: 'single-leg-balance-support', name: 'Single-Leg Balance (Support)' },
      { slug: 'single-leg-balance-reach', name: 'Single-Leg Balance Reach', unilateralOrBilateral: 'unilateral', difficulty: 'intermediate' },
      { slug: 'banded-eversion', name: 'Banded Eversion', equipmentRequired: ['band'], environment: ['gym', 'home'] },
      { slug: 'line-hop-stick', name: 'Line Hop Stick', impactLevel: 'moderate', readinessSuitability: ['moderate', 'high'], environment: ['court', 'field', 'home'] },
      { slug: 'ankle-pogo-progress', name: 'Ankle Pogo Progression', impactLevel: 'moderate', readinessSuitability: ['moderate', 'high'], environment: ['court', 'field', 'track'] },
      { slug: 'return-to-shuffle', name: 'Return to Shuffle', impactLevel: 'moderate', readinessSuitability: ['moderate', 'high'], environment: ['court', 'field'] },
    ]
  ),
  ...makeSeries(
    {
      family: 'knee-rehab',
      description: 'Knee rehab progressions to rebuild quadriceps strength, landing confidence, and return-to-change-of-direction.',
      category: 'rehab',
      subcategory: 'knee_rehab',
      movementPattern: 'knee_rehab',
      trainingIntent: ['rehab', 'return_to_play', 'strength'],
      primaryMuscles: ['quadriceps', 'glutes'],
      secondaryMuscles: ['hamstrings', 'calves'],
      jointsInvolved: ['knees', 'hips', 'ankles'],
      difficulty: 'beginner',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['bodyweight'],
      environment: ['gym', 'home', 'field', 'court'] as Environment[],
      unilateralOrBilateral: 'mixed',
      impactLevel: 'low',
      intensityProfile: 'low',
      estimatedDurationSeconds: 90,
      defaultPrescription: { sets: 3, reps: '6-10/side', restSeconds: 45, intensity: 'controlled knee load', rpe: 4 },
      coachingCues: ['Stack the knee over the foot instead of diving inward.', 'Earn speed with force control first.'],
      instructions: [
        'Pick the progression that keeps pain and swelling quiet.',
        'Control the down phase and own alignment through the foot and hip.',
        'Only add speed or depth if the knee still feels trustworthy.',
      ],
      commonMistakes: ['Adding hop volume before strength is ready.', 'Letting the knee collapse inward during fatigue.'],
      regressions: ['terminal-knee-extension'],
      progressions: ['step-down', 'split-squat-iso-hold', 'snap-down-stick'],
      substitutions: ['wall-sit', 'march-carry'],
      contraindications: ['acute_knee_pain'],
      injuryConstraints: ['knee_irritability', 'acl_return_phase_early'],
      sorenessConstraints: ['quad_dominant_day'],
      fatigueConstraints: [],
      readinessSuitability: ['low', 'moderate', 'high'],
      goalTags: ['rehab', 'return_to_play', 'injury_reduction'],
      sportTags: ['football', 'badminton', 'athletics', 'cricket', 'general_fitness'],
      positionTags: ['defender', 'midfielder', 'singles', 'jumper'],
      fitStartTags: ['knee_stability'],
      recoveryTags: ['joint_calm'],
      rehabTags: ['quad_reload', 'landing_control'],
      movementQualityTags: ['knee_control', 'landing_mechanics'],
      suitableBlocks: ['rehab', 'recovery'],
    },
    [
      { slug: 'terminal-knee-extension', name: 'Terminal Knee Extension', equipmentRequired: ['band'], environment: ['gym', 'home'] },
      { slug: 'spanish-squat-hold', name: 'Spanish Squat Hold', equipmentRequired: ['strap'], environment: ['gym', 'home'] },
      { slug: 'step-down', name: 'Step-Down', unilateralOrBilateral: 'unilateral', difficulty: 'intermediate' },
      { slug: 'wall-sit', name: 'Wall Sit', difficulty: 'beginner' },
      { slug: 'knee-snap-down-stick', name: 'Snap Down Stick', impactLevel: 'moderate', readinessSuitability: ['moderate', 'high'], environment: ['court', 'field'] },
      { slug: 'return-to-cut-45', name: 'Return to Cut 45', impactLevel: 'high', readinessSuitability: ['high'], environment: ['court', 'field'], subcategory: 'return_to_play', trainingIntent: ['rehab', 'return_to_play', 'agility'] },
    ]
  ),
  ...makeSeries(
    {
      family: 'groin-rehab',
      description: 'Adductor and groin rehab progressions for cutting, kicking, and skating-style lateral demand.',
      category: 'rehab',
      subcategory: 'groin_rehab',
      movementPattern: 'adductor_control',
      trainingIntent: ['rehab', 'return_to_play', 'stability'],
      primaryMuscles: ['adductors'],
      secondaryMuscles: ['obliques', 'glutes'],
      jointsInvolved: ['hips', 'spine'],
      difficulty: 'beginner',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['bodyweight'],
      environment: ['gym', 'home', 'field', 'court'] as Environment[],
      unilateralOrBilateral: 'mixed',
      impactLevel: 'low',
      intensityProfile: 'low',
      estimatedDurationSeconds: 75,
      defaultPrescription: { sets: 3, reps: '15-30s/side', durationSeconds: 30, restSeconds: 30, intensity: 'calm control', rpe: 4 },
      coachingCues: ['Feel the adductor load without pain or pelvic twist.', 'Control the trunk so the groin is not left alone.'],
      instructions: [
        'Start with a progression that feels strong but calm.',
        'Hold or move through the rep without pain climbing during or after the set.',
        'Advance by lever or speed only when the next-day response is quiet.',
      ],
      commonMistakes: ['Jumping to hard Copenhagen work too early.', 'Letting the trunk sag away from the adductor.'],
      regressions: ['short-lever-copenhagen'],
      progressions: ['long-lever-copenhagen', 'lateral-bound-stick'],
      substitutions: ['adductor-rockback', 'side-plank-knees'],
      contraindications: ['acute_adductor_strain'],
      injuryConstraints: ['adductor_strain', 'groin_irritability'],
      sorenessConstraints: ['adductor_domsy'],
      fatigueConstraints: [],
      readinessSuitability: ['low', 'moderate', 'high'],
      goalTags: ['rehab', 'return_to_play', 'injury_reduction'],
      sportTags: ['football', 'badminton', 'cricket', 'general_fitness', 'athletics'],
      positionTags: ['defender', 'midfielder', 'singles', 'spinner'],
      fitStartTags: ['groin_resilience'],
      recoveryTags: ['joint_calm'],
      rehabTags: ['groin_resilience'],
      movementQualityTags: ['frontal_plane_control', 'adductor_tolerance'],
      suitableBlocks: ['rehab', 'recovery'],
    },
    [
      { slug: 'short-lever-copenhagen', name: 'Short-Lever Copenhagen' },
      { slug: 'long-lever-copenhagen', name: 'Long-Lever Copenhagen', difficulty: 'advanced', readinessSuitability: ['moderate', 'high'] },
      { slug: 'adductor-squeeze', name: 'Adductor Squeeze', equipmentRequired: ['ball'], environment: ['gym', 'home'] },
      { slug: 'lateral-shift-hold', name: 'Lateral Shift Hold', unilateralOrBilateral: 'unilateral' },
      { slug: 'lateral-bound-stick', name: 'Lateral Bound Stick', impactLevel: 'moderate', readinessSuitability: ['moderate', 'high'], environment: ['court', 'field'] },
      { slug: 'return-to-shuffle-cut', name: 'Return to Shuffle Cut', impactLevel: 'high', readinessSuitability: ['high'], environment: ['court', 'field'], subcategory: 'return_to_play', trainingIntent: ['rehab', 'return_to_play', 'agility'] },
    ]
  ),
]
