import type {
  Environment,
  ExerciseCategory,
  ExerciseLibraryItem,
  ReadinessBand,
  SessionBlockType,
  SupportedSport,
} from '@/lib/product/types'
import { makeSeries } from '@/lib/product/exercises/shared'

type DrillFamilyConfig = {
  family: string
  description: string
  category?: ExerciseCategory
  subcategory: string
  movementPattern: string
  trainingIntent: string[]
  primaryMuscles: string[]
  secondaryMuscles: string[]
  jointsInvolved: string[]
  sportTags: SupportedSport[]
  positionTags?: string[]
  fitStartTags?: string[]
  movementQualityTags: string[]
  goalTags: string[]
  suitableBlocks: SessionBlockType[]
  equipmentRequired?: string[]
  environment?: Environment[]
  impactLevel?: 'low' | 'moderate' | 'high'
  readinessSuitability?: ReadinessBand[]
  variants: Array<
    {
      slug: string
      name: string
    } & Partial<
      Omit<
        ExerciseLibraryItem,
        'id' | 'slug' | 'name' | 'family' | 'description' | 'media'
      >
    >
  >
}

function drillFamily(config: DrillFamilyConfig) {
  return makeSeries(
    {
      family: config.family,
      description: config.description,
      category: config.category || 'conditioning',
      subcategory: config.subcategory,
      movementPattern: config.movementPattern,
      trainingIntent: config.trainingIntent,
      primaryMuscles: config.primaryMuscles,
      secondaryMuscles: config.secondaryMuscles,
      jointsInvolved: config.jointsInvolved,
      difficulty: 'intermediate' as const,
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: config.equipmentRequired || ['bodyweight'],
      environment: config.environment || (['field', 'court', 'track', 'gym'] as Environment[]),
      unilateralOrBilateral: 'mixed' as const,
      impactLevel: config.impactLevel || 'moderate',
      intensityProfile: 'high' as const,
      estimatedDurationSeconds: 75,
      defaultPrescription: {
        sets: 3,
        reps: '3-6',
        durationSeconds: 20,
        restSeconds: 45,
        intensity: 'quality speed',
        rpe: 7,
      },
      coachingCues: [
        'Every rep should look intentional before it looks fast.',
        'Stop the set before mechanics become noisy.',
      ],
      instructions: [
        'Set the start position and the first action before the rep begins.',
        'Execute the drill with the exact speed and rhythm the variation asks for.',
        'Walk back, reset, and only continue while quality remains high.',
      ],
      commonMistakes: [
        'Adding fatigue that blurs the movement objective.',
        'Treating a technical drill like conditioning when it needs precision.',
      ],
      regressions: [],
      progressions: [],
      substitutions: [],
      contraindications: [],
      injuryConstraints: ['acute_lower_limb_pain'],
      sorenessConstraints: ['high_leg_soreness'],
      fatigueConstraints: ['high_cns_fatigue'],
      readinessSuitability: config.readinessSuitability || ['moderate', 'high'],
      goalTags: config.goalTags,
      sportTags: config.sportTags,
      positionTags: config.positionTags || [],
      fitStartTags: config.fitStartTags || [],
      recoveryTags: [],
      rehabTags: [],
      movementQualityTags: config.movementQualityTags,
      suitableBlocks: config.suitableBlocks,
    },
    config.variants
  )
}

const genericSports: SupportedSport[] = ['general_fitness', 'football', 'cricket', 'badminton', 'athletics']

const genericFamilies: DrillFamilyConfig[] = [
  {
    family: 'sprint-mechanics',
    description: 'Low-dose sprint drills that teach posture, front-side mechanics, and crisp rhythm.',
    subcategory: 'speed_mechanics',
    movementPattern: 'sprint_mechanics',
    trainingIntent: ['speed', 'movement_prep', 'athletic_performance'],
    primaryMuscles: ['hip_flexors', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: genericSports,
    fitStartTags: ['acceleration', 'running_form'],
    movementQualityTags: ['posture', 'front_side_mechanics'],
    goalTags: ['speed', 'athletic_performance', 'match_readiness'],
    suitableBlocks: ['warmup', 'main'],
    impactLevel: 'moderate',
    variants: [
      { slug: 'march-a', name: 'A-March', category: 'warmup', subcategory: 'movement_prep', trainingIntent: ['warmup', 'speed', 'movement_prep'], suitableBlocks: ['warmup', 'main'] },
      { slug: 'skip-a', name: 'A-Skip', category: 'warmup', subcategory: 'movement_prep', trainingIntent: ['warmup', 'speed', 'movement_prep'] },
      { slug: 'wall-switch', name: 'Wall Switch Drill', equipmentRequired: ['wall'], environment: ['home', 'gym', 'field'] },
      { slug: 'wicket-march', name: 'Wicket March', equipmentRequired: ['mini_hurdles'], environment: ['track', 'field'] },
      { slug: 'ankling-drill', name: 'Ankling Drill', environment: ['track', 'field', 'court'] },
      { slug: 'straight-leg-bound-drill', name: 'Straight-Leg Bound Drill', impactLevel: 'high', readinessSuitability: ['high'], environment: ['track', 'field'] },
    ],
  },
  {
    family: 'acceleration-start',
    description: 'Acceleration starts for projection, shin angle control, and first-step power.',
    subcategory: 'acceleration',
    movementPattern: 'acceleration',
    trainingIntent: ['speed', 'power', 'athletic_performance'],
    primaryMuscles: ['glutes', 'quadriceps'],
    secondaryMuscles: ['hamstrings', 'calves'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: genericSports,
    fitStartTags: ['acceleration'],
    movementQualityTags: ['shin_angle', 'projection'],
    goalTags: ['speed', 'athletic_performance', 'match_readiness'],
    suitableBlocks: ['main'],
    impactLevel: 'high',
    variants: [
      { slug: 'split-start-5m', name: 'Split Start 5m', environment: ['field', 'court', 'track'] },
      { slug: 'falling-start-10m', name: 'Falling Start 10m', environment: ['field', 'court', 'track'] },
      { slug: 'push-up-start-10m', name: 'Push-Up Start 10m', environment: ['field', 'track'] },
      { slug: 'lateral-start-5m', name: 'Lateral Start 5m', environment: ['court', 'field'], movementQualityTags: ['reactive_projection', 'first_step'] },
      { slug: 'crossover-start-10m', name: 'Crossover Start 10m', environment: ['court', 'field'], movementQualityTags: ['hip_turn', 'first_step'] },
      { slug: 'three-point-start-10m', name: 'Three-Point Start 10m', environment: ['field', 'track'] },
    ],
  },
  {
    family: 'resisted-acceleration',
    description: 'Resisted acceleration drills that teach force projection and smoother first steps.',
    subcategory: 'resisted_speed',
    movementPattern: 'resisted_acceleration',
    trainingIntent: ['speed', 'power', 'athletic_performance'],
    primaryMuscles: ['glutes', 'quadriceps'],
    secondaryMuscles: ['hamstrings', 'calves'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: genericSports,
    fitStartTags: ['acceleration', 'power'],
    movementQualityTags: ['force_projection', 'triple_extension'],
    goalTags: ['speed', 'power', 'athletic_performance'],
    suitableBlocks: ['main', 'conditioning'],
    impactLevel: 'high',
    equipmentRequired: ['sled'],
    environment: ['field', 'track', 'gym'],
    variants: [
      { slug: 'light-sled-10m', name: 'Light Sled 10m' },
      { slug: 'moderate-sled-15m', name: 'Moderate Sled 15m', difficulty: 'advanced' },
      { slug: 'sled-march', name: 'Sled March', difficulty: 'beginner', impactLevel: 'moderate', suitableBlocks: ['warmup', 'main'] },
      { slug: 'band-resisted-run-start', name: 'Band-Resisted Run Start', equipmentRequired: ['band', 'partner'], environment: ['field', 'court'] },
      { slug: 'partner-tow-release', name: 'Partner Tow Release', equipmentRequired: ['band', 'partner'], environment: ['field', 'track'] },
      { slug: 'prowler-drive-step', name: 'Prowler Drive Step', equipmentRequired: ['prowler'], environment: ['gym', 'field'] },
    ],
  },
  {
    family: 'max-velocity',
    description: 'Max-velocity prep to improve stiffness, rhythm, and upright sprint organization.',
    subcategory: 'top_speed',
    movementPattern: 'max_velocity',
    trainingIntent: ['speed', 'athletic_performance'],
    primaryMuscles: ['hamstrings', 'calves'],
    secondaryMuscles: ['glutes', 'hip_flexors'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: ['football', 'athletics', 'cricket', 'general_fitness'],
    fitStartTags: ['top_speed'],
    movementQualityTags: ['stiffness', 'upright_mechanics'],
    goalTags: ['speed', 'athletic_performance'],
    suitableBlocks: ['main'],
    impactLevel: 'high',
    variants: [
      { slug: 'flying-10', name: 'Flying 10', environment: ['track', 'field'] },
      { slug: 'flying-20', name: 'Flying 20', environment: ['track', 'field'], difficulty: 'advanced' },
      { slug: 'wicket-run', name: 'Wicket Run', equipmentRequired: ['mini_hurdles'], environment: ['track', 'field'] },
      { slug: 'build-up-sprint', name: 'Build-Up Sprint', environment: ['track', 'field'] },
      { slug: 'straight-leg-bound', name: 'Straight-Leg Bound', environment: ['track', 'field'], impactLevel: 'high' },
      { slug: 'dribble-bleed-run', name: 'Dribble to Bleed Run', environment: ['track', 'field'], impactLevel: 'moderate' },
    ],
  },
  {
    family: 'curve-sprint',
    description: 'Curve and arc sprint drills for wing runs, outfield tracking, and bend mechanics.',
    subcategory: 'curve_speed',
    movementPattern: 'curve_sprint',
    trainingIntent: ['speed', 'agility', 'sport_drill'],
    primaryMuscles: ['glutes', 'adductors'],
    secondaryMuscles: ['hamstrings', 'calves'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: ['football', 'cricket', 'athletics', 'general_fitness'],
    positionTags: ['winger', 'striker', 'fullback', 'outfielder'],
    fitStartTags: ['change_of_direction', 'speed'],
    movementQualityTags: ['curved_projection', 'lean_control'],
    goalTags: ['speed', 'agility', 'match_readiness'],
    suitableBlocks: ['main', 'conditioning'],
    impactLevel: 'high',
    variants: [
      { slug: 'arc-sprint-short', name: 'Arc Sprint Short', environment: ['field', 'track', 'court'] },
      { slug: 'arc-sprint-long', name: 'Arc Sprint Long', environment: ['field', 'track'], difficulty: 'advanced' },
      { slug: 'curve-sprint-to-brake', name: 'Curve Sprint to Brake', environment: ['field', 'court'] },
      { slug: 'inside-shoulder-arc', name: 'Inside Shoulder Arc', environment: ['field', 'track'] },
      { slug: 'outside-shoulder-arc', name: 'Outside Shoulder Arc', environment: ['field', 'track'] },
      { slug: 'bend-and-go', name: 'Bend and Go', environment: ['field', 'court'] },
    ],
  },
  {
    family: 'deceleration',
    description: 'Braking drills to teach stopping power, shin control, and landing positions.',
    subcategory: 'deceleration',
    movementPattern: 'deceleration',
    trainingIntent: ['agility', 'injury_reduction', 'athletic_performance'],
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['calves', 'trunk'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: genericSports,
    fitStartTags: ['deceleration', 'knee_control'],
    movementQualityTags: ['braking_mechanics', 'landing_control'],
    goalTags: ['agility', 'injury_reduction', 'athletic_performance'],
    suitableBlocks: ['main', 'rehab'],
    impactLevel: 'moderate',
    variants: [
      { slug: 'snap-down-stick', name: 'Snap Down Stick', category: 'rehab', subcategory: 'return_to_play', trainingIntent: ['rehab', 'agility', 'injury_reduction'], suitableBlocks: ['rehab', 'main'], impactLevel: 'moderate', readinessSuitability: ['moderate', 'high'] },
      { slug: 'drop-stop-5m', name: 'Drop Stop 5m', environment: ['court', 'field'] },
      { slug: 'decel-step-back', name: 'Decel Step Back', environment: ['court', 'field'] },
      { slug: 'run-in-stick', name: 'Run-In Stick', environment: ['court', 'field'] },
      { slug: 'single-leg-stick', name: 'Single-Leg Stick', category: 'rehab', subcategory: 'landing_control', trainingIntent: ['rehab', 'stability', 'injury_reduction'], suitableBlocks: ['rehab', 'warmup'], impactLevel: 'moderate' },
      { slug: 'brake-and-cut-preview', name: 'Brake and Cut Preview', environment: ['court', 'field'], impactLevel: 'high', readinessSuitability: ['high'] },
    ],
  },
  {
    family: 'lateral-agility',
    description: 'Lateral movement drills for court coverage, closing speed, and hip-to-foot linkage.',
    subcategory: 'lateral_agility',
    movementPattern: 'lateral_movement',
    trainingIntent: ['agility', 'sport_drill', 'athletic_performance'],
    primaryMuscles: ['adductors', 'glutes'],
    secondaryMuscles: ['calves', 'trunk'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: ['football', 'badminton', 'cricket', 'general_fitness'],
    fitStartTags: ['lateral_speed', 'single_leg_control'],
    movementQualityTags: ['lateral_push', 'frontal_plane_control'],
    goalTags: ['agility', 'athletic_performance', 'match_readiness'],
    suitableBlocks: ['main', 'conditioning'],
    impactLevel: 'high',
    variants: [
      { slug: 'lateral-shuffle-5m', name: 'Lateral Shuffle 5m', environment: ['court', 'field'] },
      { slug: 'crossover-run-5m', name: 'Crossover Run 5m', environment: ['court', 'field'] },
      { slug: 'lateral-bound-stick-drill', name: 'Lateral Bound Stick Drill', environment: ['court', 'field'], impactLevel: 'high' },
      { slug: 'mirror-shuffle', name: 'Mirror Shuffle', equipmentRequired: ['partner'], environment: ['court', 'field'] },
      { slug: 'shuffle-to-sprint', name: 'Shuffle to Sprint', environment: ['court', 'field'] },
      { slug: 'hip-turn-chase', name: 'Hip Turn Chase', environment: ['court', 'field'] },
    ],
  },
  {
    family: 'reactive-agility',
    description: 'Reactive change-of-direction drills that combine perception with footwork and posture.',
    subcategory: 'reactive_agility',
    movementPattern: 'reactive_change',
    trainingIntent: ['agility', 'sport_drill', 'match_readiness'],
    primaryMuscles: ['glutes', 'quadriceps'],
    secondaryMuscles: ['calves', 'trunk'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: genericSports,
    fitStartTags: ['reaction', 'agility'],
    movementQualityTags: ['decision_speed', 'reactive_posture'],
    goalTags: ['agility', 'match_readiness', 'athletic_performance'],
    suitableBlocks: ['main', 'conditioning'],
    impactLevel: 'high',
    variants: [
      { slug: 'coach-call-shuffle', name: 'Coach Call Shuffle', equipmentRequired: ['partner'], environment: ['court', 'field'] },
      { slug: 'color-cone-react', name: 'Color Cone React', equipmentRequired: ['cones'], environment: ['court', 'field'] },
      { slug: 'tennis-ball-drop-react', name: 'Tennis Ball Drop React', equipmentRequired: ['tennis_ball', 'partner'], environment: ['court', 'field', 'home'] },
      { slug: 'mirror-reactive-tag', name: 'Mirror Reactive Tag', equipmentRequired: ['partner'], environment: ['court', 'field'] },
      { slug: 'audio-cue-cut', name: 'Audio Cue Cut', environment: ['court', 'field'] },
      { slug: 'reactive-gate-choice', name: 'Reactive Gate Choice', equipmentRequired: ['cones'], environment: ['court', 'field'] },
    ],
  },
  {
    family: 'pogo-stiffness',
    description: 'Foot-ankle pogo work to build contact stiffness and elastic rhythm.',
    subcategory: 'elasticity',
    movementPattern: 'pogo',
    trainingIntent: ['plyometrics', 'speed', 'athletic_performance'],
    primaryMuscles: ['calves', 'foot_intrinsics'],
    secondaryMuscles: ['glutes'],
    jointsInvolved: ['ankles', 'toes'],
    sportTags: ['football', 'badminton', 'athletics', 'general_fitness'],
    fitStartTags: ['ankle_stiffness', 'elasticity'],
    movementQualityTags: ['elastic_rebound', 'contact_stiffness'],
    goalTags: ['speed', 'agility', 'athletic_performance'],
    suitableBlocks: ['warmup', 'main'],
    impactLevel: 'moderate',
    variants: [
      { slug: 'pogos-in-place', name: 'Pogos In Place', category: 'warmup', suitableBlocks: ['warmup', 'main'] },
      { slug: 'pogos-forward', name: 'Pogos Forward', environment: ['track', 'field', 'court'] },
      { slug: 'pogos-lateral', name: 'Pogos Lateral', environment: ['court', 'field'] },
      { slug: 'single-leg-pogo', name: 'Single-Leg Pogo', unilateralOrBilateral: 'unilateral' as never, impactLevel: 'high', readinessSuitability: ['high'] },
      { slug: 'line-hops', name: 'Line Hops', environment: ['court', 'field', 'home'] },
      { slug: 'mini-hurdle-pogos', name: 'Mini-Hurdle Pogos', equipmentRequired: ['mini_hurdles'], environment: ['track', 'field'] },
    ],
  },
  {
    family: 'bounds',
    description: 'Bounding variations for elastic projection and force transfer through the ground.',
    subcategory: 'bounding',
    movementPattern: 'bounds',
    trainingIntent: ['plyometrics', 'power', 'speed'],
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['calves', 'trunk'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: ['football', 'athletics', 'general_fitness', 'cricket'],
    fitStartTags: ['power', 'elasticity'],
    movementQualityTags: ['projection', 'stiffness'],
    goalTags: ['power', 'speed', 'athletic_performance'],
    suitableBlocks: ['main'],
    impactLevel: 'high',
    variants: [
      { slug: 'double-leg-bound', name: 'Double-Leg Bound', environment: ['track', 'field'] },
      { slug: 'single-leg-bound', name: 'Single-Leg Bound', environment: ['track', 'field'], readinessSuitability: ['high'] },
      { slug: 'alternate-bound', name: 'Alternate Bound', environment: ['track', 'field'] },
      { slug: 'skater-bound', name: 'Skater Bound', environment: ['court', 'field'] },
      { slug: 'bound-to-stick', name: 'Bound to Stick', environment: ['track', 'field'], category: 'rehab', subcategory: 'landing_control', trainingIntent: ['rehab', 'power', 'landing_control'], suitableBlocks: ['rehab', 'main'], readinessSuitability: ['moderate', 'high'] },
      { slug: 'continuous-bound', name: 'Continuous Bound', environment: ['track', 'field'], readinessSuitability: ['high'] },
    ],
  },
  {
    family: 'vertical-jump',
    description: 'Vertical power drills for elastic output, landing quality, and reactivity.',
    subcategory: 'vertical_power',
    movementPattern: 'jump',
    trainingIntent: ['power', 'plyometrics', 'athletic_performance'],
    primaryMuscles: ['glutes', 'quadriceps'],
    secondaryMuscles: ['calves', 'trunk'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: ['football', 'badminton', 'athletics', 'general_fitness'],
    fitStartTags: ['jump_power'],
    movementQualityTags: ['vertical_force', 'landing_control'],
    goalTags: ['power', 'athletic_performance', 'match_readiness'],
    suitableBlocks: ['main'],
    impactLevel: 'high',
    variants: [
      { slug: 'squat-jump', name: 'Squat Jump', environment: ['court', 'field', 'gym'] },
      { slug: 'countermovement-jump', name: 'Countermovement Jump', environment: ['court', 'field', 'gym'] },
      { slug: 'box-jump', name: 'Box Jump', equipmentRequired: ['box'], environment: ['gym', 'field'] },
      { slug: 'depth-drop', name: 'Depth Drop', equipmentRequired: ['box'], environment: ['gym', 'field'], category: 'rehab', subcategory: 'landing_control', trainingIntent: ['rehab', 'landing_control', 'power'], suitableBlocks: ['rehab', 'main'], readinessSuitability: ['moderate', 'high'] },
      { slug: 'drop-jump', name: 'Drop Jump', equipmentRequired: ['box'], environment: ['gym', 'field'], readinessSuitability: ['high'] },
      { slug: 'tuck-jump', name: 'Tuck Jump', environment: ['court', 'field'], readinessSuitability: ['high'] },
    ],
  },
  {
    family: 'repeat-sprint',
    description: 'Repeat-sprint drills for hard-effort repeatability without losing mechanics.',
    subcategory: 'repeat_sprint',
    movementPattern: 'repeat_sprint',
    trainingIntent: ['conditioning', 'speed_endurance', 'match_readiness'],
    primaryMuscles: ['glutes', 'quadriceps'],
    secondaryMuscles: ['hamstrings', 'calves'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: ['football', 'cricket', 'badminton', 'general_fitness'],
    fitStartTags: ['conditioning', 'repeat_effort'],
    movementQualityTags: ['speed_endurance'],
    goalTags: ['endurance', 'match_readiness', 'athletic_performance'],
    suitableBlocks: ['conditioning'],
    impactLevel: 'high',
    variants: [
      { slug: '6x20m-sprint', name: '6 x 20m Sprint', environment: ['field', 'track'] },
      { slug: '8x15m-sprint', name: '8 x 15m Sprint', environment: ['court', 'field'] },
      { slug: 'shuttle-10-20-10', name: 'Shuttle 10-20-10', environment: ['court', 'field'] },
      { slug: 'curve-repeat-sprint', name: 'Curve Repeat Sprint', environment: ['field'] },
      { slug: 'court-corner-sprint', name: 'Court Corner Sprint', environment: ['court'] },
      { slug: 'build-cruise-surge', name: 'Build-Cruise-Surge', environment: ['field', 'track'], impactLevel: 'moderate' },
    ],
  },
  {
    family: 'shuttle-conditioning',
    description: 'Shuttle-based conditioning for directional volume and work-rate resilience.',
    subcategory: 'shuttle_conditioning',
    movementPattern: 'shuttle',
    trainingIntent: ['conditioning', 'agility', 'endurance'],
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['calves', 'trunk'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: genericSports,
    fitStartTags: ['conditioning', 'agility'],
    movementQualityTags: ['repeat_effort', 'deceleration_control'],
    goalTags: ['endurance', 'body_recomposition', 'match_readiness'],
    suitableBlocks: ['conditioning'],
    impactLevel: 'moderate',
    variants: [
      { slug: '5-10-5-shuttle', name: '5-10-5 Shuttle', environment: ['field', 'court'] },
      { slug: 'beep-shuttle-10m', name: 'Beep Shuttle 10m', environment: ['court', 'field'] },
      { slug: 'cone-touch-shuttle', name: 'Cone Touch Shuttle', equipmentRequired: ['cones'], environment: ['court', 'field'] },
      { slug: 'lateral-shuttle', name: 'Lateral Shuttle', environment: ['court', 'field'] },
      { slug: 'triangle-shuttle', name: 'Triangle Shuttle', equipmentRequired: ['cones'], environment: ['court', 'field'] },
      { slug: 'suicide-run-lite', name: 'Suicide Run Lite', environment: ['court', 'field'], impactLevel: 'high' },
    ],
  },
  {
    family: 'tempo-conditioning',
    description: 'Controlled aerobic tempo work for base building and recovery-friendly conditioning.',
    subcategory: 'tempo',
    movementPattern: 'tempo_run',
    trainingIntent: ['conditioning', 'endurance', 'aerobic_base'],
    primaryMuscles: ['full_body'],
    secondaryMuscles: ['diaphragm'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: genericSports,
    fitStartTags: ['endurance', 'recovery'],
    movementQualityTags: ['aerobic_rhythm'],
    goalTags: ['endurance', 'fat_loss', 'general_fitness', 'recovery'],
    suitableBlocks: ['conditioning', 'recovery'],
    impactLevel: 'moderate',
    variants: [
      { slug: 'tempo-run-100m', name: 'Tempo Run 100m', environment: ['track', 'field'], impactLevel: 'moderate' },
      { slug: 'tempo-run-150m', name: 'Tempo Run 150m', environment: ['track', 'field'], impactLevel: 'moderate' },
      { slug: 'grass-strides', name: 'Grass Strides', environment: ['field'] },
      { slug: 'aerobic-shuttle-float', name: 'Aerobic Shuttle Float', environment: ['field', 'court'] },
      { slug: 'nasal-breath-jog', name: 'Nasal-Breath Jog', category: 'recovery', subcategory: 'active_recovery', trainingIntent: ['recovery', 'aerobic_base'], suitableBlocks: ['recovery', 'conditioning'], impactLevel: 'low' },
      { slug: 'walk-run-interval', name: 'Walk-Run Interval', category: 'recovery', subcategory: 'active_recovery', trainingIntent: ['recovery', 'conditioning', 'aerobic_base'], suitableBlocks: ['recovery', 'conditioning'], impactLevel: 'low' },
    ],
  },
  {
    family: 'bike-conditioning',
    description: 'Low-impact bike work for recovery-friendly conditioning and readiness-protected volume.',
    subcategory: 'bike_conditioning',
    movementPattern: 'cycle',
    trainingIntent: ['conditioning', 'recovery', 'aerobic_base'],
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['calves'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: genericSports,
    fitStartTags: ['conditioning', 'low_impact'],
    movementQualityTags: ['aerobic_rhythm'],
    goalTags: ['endurance', 'fat_loss', 'recovery'],
    suitableBlocks: ['conditioning', 'recovery'],
    impactLevel: 'low',
    equipmentRequired: ['bike'],
    environment: ['gym', 'home'],
    variants: [
      { slug: 'bike-easy-spin', name: 'Bike Easy Spin', category: 'recovery', subcategory: 'active_recovery', suitableBlocks: ['recovery', 'cooldown'], impactLevel: 'low', trainingIntent: ['recovery', 'aerobic_base'] },
      { slug: 'bike-30-30', name: 'Bike 30:30', suitableBlocks: ['conditioning'] },
      { slug: 'bike-45-15', name: 'Bike 45:15', suitableBlocks: ['conditioning'] },
      { slug: 'bike-threshold-wave', name: 'Bike Threshold Wave', readinessSuitability: ['moderate', 'high'] },
      { slug: 'bike-high-cadence-flush', name: 'Bike High-Cadence Flush', category: 'recovery', subcategory: 'active_recovery', suitableBlocks: ['recovery'], impactLevel: 'low', trainingIntent: ['recovery', 'conditioning'] },
      { slug: 'bike-sprint-cluster', name: 'Bike Sprint Cluster', readinessSuitability: ['high'], impactLevel: 'moderate' },
    ],
  },
  {
    family: 'sled-conditioning',
    description: 'Sled pushes and drags for robust low-skill power conditioning.',
    subcategory: 'sled_work',
    movementPattern: 'sled',
    trainingIntent: ['conditioning', 'power', 'strength'],
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['trunk', 'calves'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: ['football', 'cricket', 'athletics', 'general_fitness'],
    fitStartTags: ['conditioning', 'force_production'],
    movementQualityTags: ['projection', 'posture'],
    goalTags: ['strength', 'conditioning', 'athletic_performance'],
    suitableBlocks: ['conditioning', 'accessory'],
    impactLevel: 'moderate',
    equipmentRequired: ['sled'],
    environment: ['field', 'gym'],
    variants: [
      { slug: 'sled-push-light', name: 'Sled Push Light' },
      { slug: 'sled-push-heavy', name: 'Sled Push Heavy', difficulty: 'advanced' },
      { slug: 'backward-sled-drag', name: 'Backward Sled Drag', category: 'rehab', subcategory: 'knee_reload', trainingIntent: ['rehab', 'strength', 'conditioning'], suitableBlocks: ['rehab', 'conditioning'], impactLevel: 'low' },
      { slug: 'lateral-sled-drag', name: 'Lateral Sled Drag', environment: ['field', 'gym'] },
      { slug: 'sprint-sled-combo', name: 'Sprint Sled Combo', readinessSuitability: ['high'], impactLevel: 'high' },
      { slug: 'sled-march-flush', name: 'Sled March Flush', category: 'recovery', subcategory: 'active_recovery', trainingIntent: ['recovery', 'conditioning'], suitableBlocks: ['recovery', 'conditioning'], impactLevel: 'low' },
    ],
  },
  {
    family: 'home-conditioning',
    description: 'Minimal-equipment conditioning for home users who still need structure and specificity.',
    subcategory: 'home_conditioning',
    movementPattern: 'mixed_modal',
    trainingIntent: ['conditioning', 'body_recomposition', 'general_fitness'],
    primaryMuscles: ['full_body'],
    secondaryMuscles: ['diaphragm'],
    jointsInvolved: ['full_body'],
    sportTags: ['general_fitness', 'football', 'cricket', 'badminton'],
    fitStartTags: ['home_training', 'conditioning'],
    movementQualityTags: ['repeat_effort'],
    goalTags: ['fat_loss', 'body_recomposition', 'general_fitness'],
    suitableBlocks: ['conditioning'],
    impactLevel: 'moderate',
    environment: ['home'],
    variants: [
      { slug: 'shadow-box-conditioning', name: 'Shadow Box Conditioning', environment: ['home'] },
      { slug: 'low-impact-emom', name: 'Low-Impact EMOM', category: 'recovery', subcategory: 'active_recovery', trainingIntent: ['conditioning', 'recovery'], suitableBlocks: ['conditioning', 'recovery'], impactLevel: 'low', environment: ['home'] },
      { slug: 'band-circuit-12', name: 'Band Circuit 12', equipmentRequired: ['band'], environment: ['home'] },
      { slug: 'bodyweight-ladder-15', name: 'Bodyweight Ladder 15', environment: ['home'] },
      { slug: 'march-squat-reach-flow', name: 'March Squat Reach Flow', category: 'warmup', subcategory: 'movement_prep', trainingIntent: ['warmup', 'conditioning'], suitableBlocks: ['warmup', 'conditioning'], impactLevel: 'low', environment: ['home'] },
      { slug: 'stairs-repeat-effort', name: 'Stairs Repeat Effort', equipmentRequired: ['stairs'], environment: ['home'] },
    ],
  },
]

const cricketFamilies: DrillFamilyConfig[] = [
  {
    family: 'cricket-fast-bowler-rhythm',
    description: 'Fast-bowler approach drills for rhythm, trunk timing, and repeatable delivery mechanics.',
    subcategory: 'cricket_fast_bowler',
    movementPattern: 'run_up_rhythm',
    trainingIntent: ['sport_drill', 'speed', 'power'],
    primaryMuscles: ['glutes', 'trunk'],
    secondaryMuscles: ['hamstrings', 'shoulders'],
    jointsInvolved: ['hips', 'knees', 'ankles', 'shoulders'],
    sportTags: ['cricket'],
    positionTags: ['fast bowler'],
    fitStartTags: ['run_up', 'rotational_power'],
    movementQualityTags: ['run_up_rhythm', 'hip_shoulder_separation'],
    goalTags: ['athletic_performance', 'match_readiness', 'speed'],
    suitableBlocks: ['main', 'conditioning'],
    impactLevel: 'high',
    variants: [
      { slug: 'cricket-run-up-march', name: 'Cricket Run-Up March', category: 'warmup', trainingIntent: ['warmup', 'sport_drill', 'movement_prep'], suitableBlocks: ['warmup', 'main'], impactLevel: 'moderate' },
      { slug: 'cricket-run-up-build', name: 'Cricket Run-Up Build' },
      { slug: 'cricket-bound-to-stick', name: 'Cricket Bound to Stick', impactLevel: 'high' },
      { slug: 'cricket-delivery-stride-pattern', name: 'Cricket Delivery Stride Pattern' },
      { slug: 'cricket-run-up-repeat', name: 'Cricket Run-Up Repeat' },
      { slug: 'cricket-release-rhythm-medball', name: 'Cricket Release Rhythm Med Ball', equipmentRequired: ['med_ball'], environment: ['field', 'gym'] },
    ],
  },
  {
    family: 'cricket-batter',
    description: 'Batting movement drills for hip-shoulder sync, base stability, and repeated acceleration between wickets.',
    subcategory: 'cricket_batter',
    movementPattern: 'batting_drill',
    trainingIntent: ['sport_drill', 'power', 'agility'],
    primaryMuscles: ['obliques', 'glutes'],
    secondaryMuscles: ['adductors', 'calves'],
    jointsInvolved: ['hips', 'spine', 'ankles'],
    sportTags: ['cricket'],
    positionTags: ['batter'],
    fitStartTags: ['rotational_power', 'speed'],
    movementQualityTags: ['batting_base', 'rotational_timing'],
    goalTags: ['athletic_performance', 'match_readiness', 'power'],
    suitableBlocks: ['main', 'conditioning'],
    variants: [
      { slug: 'cricket-shadow-bat-shift', name: 'Cricket Shadow Bat Shift', category: 'warmup', trainingIntent: ['warmup', 'sport_drill'], suitableBlocks: ['warmup', 'main'], impactLevel: 'moderate' },
      { slug: 'cricket-medball-shot', name: 'Cricket Med Ball Shot', equipmentRequired: ['med_ball'], environment: ['field', 'gym'] },
      { slug: 'cricket-drop-step-drive', name: 'Cricket Drop Step Drive' },
      { slug: 'cricket-between-wickets-2s', name: 'Cricket Between Wickets 2s' },
      { slug: 'cricket-batting-react-call', name: 'Cricket Batting React Call', equipmentRequired: ['partner'], environment: ['field'] },
      { slug: 'cricket-run-turn-return', name: 'Cricket Run Turn Return', environment: ['field'] },
    ],
  },
  {
    family: 'cricket-wicketkeeper',
    description: 'Wicketkeeper drills for low stance tolerance, lateral reactions, and shoulder endurance.',
    subcategory: 'cricket_wicketkeeper',
    movementPattern: 'keeper_footwork',
    trainingIntent: ['sport_drill', 'agility', 'stability'],
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['calves', 'shoulders'],
    jointsInvolved: ['hips', 'knees', 'ankles', 'shoulders'],
    sportTags: ['cricket'],
    positionTags: ['wicketkeeper'],
    fitStartTags: ['agility', 'single_leg_control'],
    movementQualityTags: ['low_stance', 'reaction'],
    goalTags: ['match_readiness', 'agility', 'injury_reduction'],
    suitableBlocks: ['main', 'conditioning'],
    variants: [
      { slug: 'keeper-stance-rocker', name: 'Keeper Stance Rocker', category: 'warmup', trainingIntent: ['warmup', 'sport_drill'], suitableBlocks: ['warmup', 'main'], impactLevel: 'low' },
      { slug: 'keeper-lateral-pop', name: 'Keeper Lateral Pop', environment: ['field', 'court'] },
      { slug: 'keeper-reactive-pick', name: 'Keeper Reactive Pick', equipmentRequired: ['partner', 'ball'], environment: ['field'] },
      { slug: 'keeper-low-block-repeat', name: 'Keeper Low Block Repeat', equipmentRequired: ['ball'], environment: ['field'] },
      { slug: 'keeper-recovery-shuffle', name: 'Keeper Recovery Shuffle', environment: ['field'] },
      { slug: 'keeper-overhead-endurance', name: 'Keeper Overhead Endurance', category: 'strength', subcategory: 'shoulder_endurance', trainingIntent: ['stability', 'sport_drill'], equipmentRequired: ['band'], environment: ['gym', 'field'], suitableBlocks: ['accessory', 'main'], impactLevel: 'low' },
    ],
  },
  {
    family: 'cricket-spinner',
    description: 'Spinner drills for hip-shoulder separation, rhythm, and lower-limb balance under repeated deliveries.',
    subcategory: 'cricket_spinner',
    movementPattern: 'spinner_drill',
    trainingIntent: ['sport_drill', 'power', 'balance'],
    primaryMuscles: ['obliques', 'glutes'],
    secondaryMuscles: ['calves', 'rotator_cuff'],
    jointsInvolved: ['hips', 'spine', 'shoulders', 'ankles'],
    sportTags: ['cricket'],
    positionTags: ['spinner'],
    fitStartTags: ['rotational_control'],
    movementQualityTags: ['hip_shoulder_separation', 'balance'],
    goalTags: ['athletic_performance', 'match_readiness'],
    suitableBlocks: ['main'],
    variants: [
      { slug: 'spinner-coil-hold', name: 'Spinner Coil Hold', category: 'warmup', trainingIntent: ['warmup', 'sport_drill', 'balance'], suitableBlocks: ['warmup', 'main'], impactLevel: 'low' },
      { slug: 'spinner-walk-in-release', name: 'Spinner Walk-In Release' },
      { slug: 'spinner-medball-twist', name: 'Spinner Med Ball Twist', equipmentRequired: ['med_ball'], environment: ['field', 'gym'] },
      { slug: 'spinner-single-leg-release', name: 'Spinner Single-Leg Release', environment: ['field'] },
      { slug: 'spinner-repeat-delivery', name: 'Spinner Repeat Delivery', environment: ['field'] },
      { slug: 'spinner-rebound-step', name: 'Spinner Rebound Step', environment: ['field'] },
    ],
  },
  {
    family: 'cricket-fielding',
    description: 'Fielding movement drills for pickup angles, throw prep, and rapid reacceleration.',
    subcategory: 'cricket_fielding',
    movementPattern: 'fielding_drill',
    trainingIntent: ['sport_drill', 'agility', 'power'],
    primaryMuscles: ['glutes', 'quadriceps'],
    secondaryMuscles: ['rotator_cuff', 'obliques'],
    jointsInvolved: ['hips', 'knees', 'ankles', 'shoulders'],
    sportTags: ['cricket'],
    positionTags: ['batter', 'fast bowler', 'wicketkeeper', 'spinner'],
    fitStartTags: ['agility', 'throwing_prep'],
    movementQualityTags: ['pickup_angle', 'reacceleration'],
    goalTags: ['match_readiness', 'agility', 'athletic_performance'],
    suitableBlocks: ['main', 'conditioning'],
    variants: [
      { slug: 'fielding-pickup-shuffle', name: 'Fielding Pickup Shuffle' },
      { slug: 'fielding-sprint-pickup-return', name: 'Fielding Sprint Pickup Return' },
      { slug: 'fielding-medball-pickup-throw', name: 'Fielding Med Ball Pickup Throw', equipmentRequired: ['med_ball'], environment: ['field', 'gym'] },
      { slug: 'fielding-react-call-turn', name: 'Fielding React Call Turn', equipmentRequired: ['partner'], environment: ['field'] },
      { slug: 'fielding-reload-crow-hop', name: 'Fielding Reload Crow Hop', environment: ['field'] },
      { slug: 'fielding-dive-preview', name: 'Fielding Dive Preview', category: 'rehab', subcategory: 'return_to_play', trainingIntent: ['rehab', 'sport_drill', 'landing_control'], suitableBlocks: ['rehab', 'main'], readinessSuitability: ['moderate', 'high'] },
    ],
  },
]

const footballFamilies: DrillFamilyConfig[] = [
  {
    family: 'football-goalkeeper',
    description: 'Goalkeeper footwork and set-position drills for explosive first movement and repeat reactions.',
    subcategory: 'football_goalkeeper',
    movementPattern: 'goalkeeper_footwork',
    trainingIntent: ['sport_drill', 'agility', 'power'],
    primaryMuscles: ['glutes', 'quadriceps'],
    secondaryMuscles: ['calves', 'shoulders'],
    jointsInvolved: ['hips', 'knees', 'ankles', 'shoulders'],
    sportTags: ['football'],
    positionTags: ['goalkeeper'],
    fitStartTags: ['agility', 'reaction'],
    movementQualityTags: ['set_position', 'push_step'],
    goalTags: ['match_readiness', 'agility', 'athletic_performance'],
    suitableBlocks: ['main', 'conditioning'],
    variants: [
      { slug: 'gk-set-hop', name: 'GK Set Hop' },
      { slug: 'gk-lateral-push', name: 'GK Lateral Push' },
      { slug: 'gk-reactive-dive-step', name: 'GK Reactive Dive Step', equipmentRequired: ['partner'], environment: ['field'] },
      { slug: 'gk-recovery-to-set', name: 'GK Recovery to Set', environment: ['field'] },
      { slug: 'gk-high-ball-footwork', name: 'GK High Ball Footwork', environment: ['field'] },
      { slug: 'gk-band-shoulder-endurance', name: 'GK Band Shoulder Endurance', category: 'strength', subcategory: 'shoulder_endurance', trainingIntent: ['stability', 'sport_drill'], equipmentRequired: ['band'], environment: ['gym', 'field'], suitableBlocks: ['accessory', 'main'], impactLevel: 'low' },
    ],
  },
  {
    family: 'football-defender',
    description: 'Defender movement drills for backpedal-to-turn speed and collision-ready posture.',
    subcategory: 'football_defender',
    movementPattern: 'defender_movement',
    trainingIntent: ['sport_drill', 'agility', 'speed'],
    primaryMuscles: ['glutes', 'adductors'],
    secondaryMuscles: ['calves', 'trunk'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: ['football'],
    positionTags: ['defender'],
    fitStartTags: ['change_of_direction', 'agility'],
    movementQualityTags: ['hip_turn', 'deceleration_control'],
    goalTags: ['match_readiness', 'agility', 'athletic_performance'],
    suitableBlocks: ['main', 'conditioning'],
    variants: [
      { slug: 'defender-backpedal-turn', name: 'Defender Backpedal Turn' },
      { slug: 'defender-closeout-stick', name: 'Defender Closeout Stick' },
      { slug: 'defender-drop-and-run', name: 'Defender Drop and Run' },
      { slug: 'defender-angle-recovery', name: 'Defender Angle Recovery' },
      { slug: 'defender-jockey-shuffle', name: 'Defender Jockey Shuffle' },
      { slug: 'defender-clearance-step', name: 'Defender Clearance Step', environment: ['field'] },
    ],
  },
  {
    family: 'football-fullback',
    description: 'Fullback drills for repeated overlap sprinting and recovery to defensive shape.',
    subcategory: 'football_fullback',
    movementPattern: 'fullback_repeat',
    trainingIntent: ['sport_drill', 'speed_endurance', 'agility'],
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['calves', 'trunk'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: ['football'],
    positionTags: ['fullback'],
    fitStartTags: ['repeat_effort', 'speed'],
    movementQualityTags: ['curve_run', 'repeat_sprint'],
    goalTags: ['match_readiness', 'endurance', 'athletic_performance'],
    suitableBlocks: ['main', 'conditioning'],
    variants: [
      { slug: 'fullback-overlap-run', name: 'Fullback Overlap Run' },
      { slug: 'fullback-recover-arc', name: 'Fullback Recover Arc' },
      { slug: 'fullback-overlap-return', name: 'Fullback Overlap Return' },
      { slug: 'fullback-wide-channel-repeat', name: 'Fullback Wide Channel Repeat' },
      { slug: 'fullback-cross-step-recovery', name: 'Fullback Cross-Step Recovery' },
      { slug: 'fullback-repeated-curve-sprint', name: 'Fullback Repeated Curve Sprint' },
    ],
  },
  {
    family: 'football-midfielder',
    description: 'Midfielder drills for scan-to-move rhythm, central shuttle volume, and repeat deceleration.',
    subcategory: 'football_midfielder',
    movementPattern: 'midfielder_pattern',
    trainingIntent: ['sport_drill', 'conditioning', 'agility'],
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['calves', 'trunk'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: ['football'],
    positionTags: ['midfielder'],
    fitStartTags: ['repeat_effort', 'agility'],
    movementQualityTags: ['scan_and_move', 'repeat_effort'],
    goalTags: ['match_readiness', 'endurance', 'athletic_performance'],
    suitableBlocks: ['main', 'conditioning'],
    variants: [
      { slug: 'midfielder-scan-shuttle', name: 'Midfielder Scan Shuttle' },
      { slug: 'midfielder-open-close-angle', name: 'Midfielder Open Close Angle' },
      { slug: 'midfielder-react-pass-burst', name: 'Midfielder React Pass Burst', equipmentRequired: ['partner'], environment: ['field'] },
      { slug: 'midfielder-box-to-box-repeat', name: 'Midfielder Box-to-Box Repeat' },
      { slug: 'midfielder-turn-check-burst', name: 'Midfielder Turn Check Burst' },
      { slug: 'midfielder-rondo-footwork', name: 'Midfielder Rondo Footwork', environment: ['field', 'court'] },
    ],
  },
  {
    family: 'football-winger',
    description: 'Winger drills for curve speed, wide cuts, and explosive end-product movement.',
    subcategory: 'football_winger',
    movementPattern: 'winger_movement',
    trainingIntent: ['sport_drill', 'speed', 'agility'],
    primaryMuscles: ['glutes', 'adductors'],
    secondaryMuscles: ['hamstrings', 'calves'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: ['football'],
    positionTags: ['winger'],
    fitStartTags: ['speed', 'change_of_direction'],
    movementQualityTags: ['curve_speed', 'one_v_one_cut'],
    goalTags: ['match_readiness', 'speed', 'athletic_performance'],
    suitableBlocks: ['main', 'conditioning'],
    variants: [
      { slug: 'winger-curve-run-finish', name: 'Winger Curve Run Finish' },
      { slug: 'winger-isolation-cut', name: 'Winger Isolation Cut' },
      { slug: 'winger-double-move-burst', name: 'Winger Double Move Burst' },
      { slug: 'winger-wide-recovery-run', name: 'Winger Wide Recovery Run' },
      { slug: 'winger-cut-cross-repeat', name: 'Winger Cut Cross Repeat' },
      { slug: 'winger-reactive-channel-race', name: 'Winger Reactive Channel Race', equipmentRequired: ['partner'], environment: ['field'] },
    ],
  },
  {
    family: 'football-striker',
    description: 'Striker drills for box bursts, curved separation, and repeat finishing movement.',
    subcategory: 'football_striker',
    movementPattern: 'striker_movement',
    trainingIntent: ['sport_drill', 'speed', 'power'],
    primaryMuscles: ['glutes', 'quadriceps'],
    secondaryMuscles: ['hamstrings', 'calves'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: ['football'],
    positionTags: ['striker'],
    fitStartTags: ['speed', 'power'],
    movementQualityTags: ['separation_run', 'box_burst'],
    goalTags: ['match_readiness', 'speed', 'power'],
    suitableBlocks: ['main', 'conditioning'],
    variants: [
      { slug: 'striker-near-post-burst', name: 'Striker Near-Post Burst' },
      { slug: 'striker-far-post-curve', name: 'Striker Far-Post Curve' },
      { slug: 'striker-check-and-spin', name: 'Striker Check and Spin' },
      { slug: 'striker-box-repeat-burst', name: 'Striker Box Repeat Burst' },
      { slug: 'striker-reactive-rebound-run', name: 'Striker Reactive Rebound Run', equipmentRequired: ['partner'], environment: ['field'] },
      { slug: 'striker-press-to-sprint', name: 'Striker Press to Sprint' },
    ],
  },
]

const badmintonFamilies: DrillFamilyConfig[] = [
  {
    family: 'badminton-split-step',
    description: 'Split-step and first-push drills for faster court reactions and cleaner recovery rhythm.',
    subcategory: 'badminton_split_step',
    movementPattern: 'split_step',
    trainingIntent: ['sport_drill', 'agility', 'match_readiness'],
    primaryMuscles: ['calves', 'glutes'],
    secondaryMuscles: ['quadriceps', 'trunk'],
    jointsInvolved: ['ankles', 'knees', 'hips'],
    sportTags: ['badminton'],
    positionTags: ['singles', 'doubles'],
    fitStartTags: ['reaction', 'agility'],
    movementQualityTags: ['split_step', 'court_reaction'],
    goalTags: ['match_readiness', 'agility', 'athletic_performance'],
    suitableBlocks: ['warmup', 'main'],
    variants: [
      { slug: 'badminton-split-step-basic', name: 'Badminton Split-Step Basic', category: 'warmup', trainingIntent: ['warmup', 'sport_drill'], suitableBlocks: ['warmup', 'main'], impactLevel: 'moderate' },
      { slug: 'badminton-split-step-react', name: 'Badminton Split-Step React' },
      { slug: 'badminton-split-step-lateral', name: 'Badminton Split-Step Lateral' },
      { slug: 'badminton-split-step-forward', name: 'Badminton Split-Step Forward' },
      { slug: 'badminton-split-step-recover', name: 'Badminton Split-Step Recover' },
      { slug: 'badminton-split-step-mirror', name: 'Badminton Split-Step Mirror', equipmentRequired: ['partner'], environment: ['court'] },
    ],
  },
  {
    family: 'badminton-singles',
    description: 'Singles court-coverage drills for deep-lunge tolerance, recovery hops, and repeat directional work.',
    subcategory: 'badminton_singles',
    movementPattern: 'singles_coverage',
    trainingIntent: ['sport_drill', 'agility', 'conditioning'],
    primaryMuscles: ['glutes', 'adductors'],
    secondaryMuscles: ['calves', 'quadriceps'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: ['badminton'],
    positionTags: ['singles'],
    fitStartTags: ['agility', 'single_leg_control'],
    movementQualityTags: ['court_recovery', 'lunge_control'],
    goalTags: ['match_readiness', 'agility', 'endurance'],
    suitableBlocks: ['main', 'conditioning'],
    variants: [
      { slug: 'badminton-shadow-six-point', name: 'Badminton Shadow Six Point' },
      { slug: 'badminton-recovery-hop', name: 'Badminton Recovery Hop' },
      { slug: 'badminton-deep-forecourt-lunge', name: 'Badminton Deep Forecourt Lunge' },
      { slug: 'badminton-rear-court-recover', name: 'Badminton Rear Court Recover' },
      { slug: 'badminton-multi-shuttle-feet', name: 'Badminton Multi-Shuttle Feet', equipmentRequired: ['partner', 'shuttles'], environment: ['court'] },
      { slug: 'badminton-singles-rally-repeat', name: 'Badminton Singles Rally Repeat', environment: ['court'] },
    ],
  },
  {
    family: 'badminton-doubles',
    description: 'Doubles patterns for front-back rotation, intercept speed, and shared-court reactions.',
    subcategory: 'badminton_doubles',
    movementPattern: 'doubles_rotation',
    trainingIntent: ['sport_drill', 'agility', 'match_readiness'],
    primaryMuscles: ['glutes', 'calves'],
    secondaryMuscles: ['adductors', 'trunk'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: ['badminton'],
    positionTags: ['doubles'],
    fitStartTags: ['agility', 'reaction'],
    movementQualityTags: ['front_back_rotation', 'intercept_speed'],
    goalTags: ['match_readiness', 'agility'],
    suitableBlocks: ['main', 'conditioning'],
    variants: [
      { slug: 'badminton-front-back-switch', name: 'Badminton Front-Back Switch' },
      { slug: 'badminton-intercept-recover', name: 'Badminton Intercept Recover' },
      { slug: 'badminton-midcourt-pop', name: 'Badminton Midcourt Pop' },
      { slug: 'badminton-side-side-push', name: 'Badminton Side-Side Push' },
      { slug: 'badminton-doubles-react-call', name: 'Badminton Doubles React Call', equipmentRequired: ['partner'], environment: ['court'] },
      { slug: 'badminton-net-kill-repeat', name: 'Badminton Net Kill Repeat', environment: ['court'] },
    ],
  },
  {
    family: 'badminton-shoulder-endurance',
    description: 'Shoulder endurance and cuff control work for repeated overhead rallies.',
    category: 'strength',
    subcategory: 'badminton_shoulder',
    movementPattern: 'shoulder_endurance',
    trainingIntent: ['stability', 'sport_drill', 'injury_reduction'],
    primaryMuscles: ['rotator_cuff', 'serratus'],
    secondaryMuscles: ['mid_back', 'forearm'],
    jointsInvolved: ['shoulders', 'elbows'],
    sportTags: ['badminton'],
    positionTags: ['singles', 'doubles'],
    fitStartTags: ['shoulder_resilience'],
    movementQualityTags: ['overhead_endurance'],
    goalTags: ['injury_reduction', 'athletic_performance', 'match_readiness'],
    suitableBlocks: ['accessory', 'rehab'],
    impactLevel: 'low',
    variants: [
      { slug: 'badminton-band-w', name: 'Badminton Band W', equipmentRequired: ['band'], environment: ['court', 'gym', 'home'] },
      { slug: 'badminton-scaption-pulse', name: 'Badminton Scaption Pulse', equipmentRequired: ['dumbbell'], environment: ['gym', 'home'] },
      { slug: 'badminton-racket-isometric', name: 'Badminton Racket Isometric', equipmentRequired: ['racket'], environment: ['court', 'home'] },
      { slug: 'badminton-wall-slide-reach', name: 'Badminton Wall Slide Reach', equipmentRequired: ['wall'], environment: ['court', 'home', 'gym'] },
      { slug: 'badminton-cuff-catch', name: 'Badminton Cuff Catch', equipmentRequired: ['partner', 'light_ball'], environment: ['court', 'gym'] },
      { slug: 'badminton-overhead-rhythm-band', name: 'Badminton Overhead Rhythm Band', equipmentRequired: ['band'], environment: ['court', 'home', 'gym'] },
    ],
  },
  {
    family: 'badminton-footwork-conditioning',
    description: 'Footwork conditioning sequences that preserve shape while building repeat effort.',
    subcategory: 'badminton_conditioning',
    movementPattern: 'court_conditioning',
    trainingIntent: ['conditioning', 'sport_drill', 'endurance'],
    primaryMuscles: ['calves', 'glutes'],
    secondaryMuscles: ['quadriceps', 'trunk'],
    jointsInvolved: ['ankles', 'knees', 'hips'],
    sportTags: ['badminton'],
    positionTags: ['singles', 'doubles'],
    fitStartTags: ['conditioning', 'agility'],
    movementQualityTags: ['court_repeat_effort'],
    goalTags: ['endurance', 'match_readiness', 'athletic_performance'],
    suitableBlocks: ['conditioning'],
    variants: [
      { slug: 'badminton-court-corners', name: 'Badminton Court Corners' },
      { slug: 'badminton-front-back-repeat', name: 'Badminton Front-Back Repeat' },
      { slug: 'badminton-lateral-repeat', name: 'Badminton Lateral Repeat' },
      { slug: 'badminton-shuttle-react-circuit', name: 'Badminton Shuttle React Circuit', equipmentRequired: ['partner', 'shuttles'], environment: ['court'] },
      { slug: 'badminton-shadow-emom', name: 'Badminton Shadow EMOM', environment: ['court'] },
      { slug: 'badminton-recovery-walk-shuffle', name: 'Badminton Recovery Walk Shuffle', category: 'recovery', subcategory: 'active_recovery', trainingIntent: ['recovery', 'sport_drill'], suitableBlocks: ['recovery', 'conditioning'], impactLevel: 'low', environment: ['court'] },
    ],
  },
]

const athleticsFamilies: DrillFamilyConfig[] = [
  {
    family: 'athletics-sprinter',
    description: 'Sprint event drills for acceleration, wickets, and upright rhythm.',
    subcategory: 'athletics_sprinter',
    movementPattern: 'sprinter_drill',
    trainingIntent: ['sport_drill', 'speed', 'power'],
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['calves', 'hip_flexors'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: ['athletics'],
    positionTags: ['sprinter'],
    fitStartTags: ['speed', 'running_form'],
    movementQualityTags: ['stiffness', 'upright_mechanics'],
    goalTags: ['speed', 'athletic_performance', 'match_readiness'],
    suitableBlocks: ['warmup', 'main'],
    impactLevel: 'high',
    variants: [
      { slug: 'sprinter-wicket-walk', name: 'Sprinter Wicket Walk', category: 'warmup', trainingIntent: ['warmup', 'sport_drill'], suitableBlocks: ['warmup', 'main'], impactLevel: 'moderate' },
      { slug: 'sprinter-wicket-run', name: 'Sprinter Wicket Run', environment: ['track', 'field'], equipmentRequired: ['mini_hurdles'] },
      { slug: 'sprinter-fly-build', name: 'Sprinter Fly Build', environment: ['track'] },
      { slug: 'sprinter-block-exit-preview', name: 'Sprinter Block Exit Preview', equipmentRequired: ['blocks'], environment: ['track'] },
      { slug: 'sprinter-dribble-run', name: 'Sprinter Dribble Run', environment: ['track'] },
      { slug: 'sprinter-accel-to-wicket', name: 'Sprinter Accel to Wicket', environment: ['track'], equipmentRequired: ['mini_hurdles'] },
    ],
  },
  {
    family: 'athletics-middle-distance',
    description: 'Middle-distance drills for rhythm, elastic economy, and pace-control conditioning.',
    subcategory: 'athletics_middle_distance',
    movementPattern: 'middle_distance_drill',
    trainingIntent: ['sport_drill', 'endurance', 'running_economy'],
    primaryMuscles: ['full_body'],
    secondaryMuscles: ['diaphragm'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: ['athletics'],
    positionTags: ['middle-distance'],
    fitStartTags: ['endurance', 'running_form'],
    movementQualityTags: ['cadence', 'economy'],
    goalTags: ['endurance', 'athletic_performance', 'match_readiness'],
    suitableBlocks: ['main', 'conditioning'],
    impactLevel: 'moderate',
    variants: [
      { slug: 'mid-distance-drill-combo', name: 'Middle-Distance Drill Combo', category: 'warmup', trainingIntent: ['warmup', 'sport_drill'], suitableBlocks: ['warmup', 'main'] },
      { slug: 'mid-distance-strides', name: 'Middle-Distance Strides', environment: ['track', 'field'] },
      { slug: 'mid-distance-cadence-float', name: 'Middle-Distance Cadence Float', environment: ['track'] },
      { slug: 'mid-distance-pace-ladder', name: 'Middle-Distance Pace Ladder', environment: ['track'] },
      { slug: 'mid-distance-rhythm-200s', name: 'Middle-Distance Rhythm 200s', environment: ['track'] },
      { slug: 'mid-distance-recovery-jog-reset', name: 'Middle-Distance Recovery Jog Reset', category: 'recovery', subcategory: 'active_recovery', trainingIntent: ['recovery', 'aerobic_base'], suitableBlocks: ['recovery', 'conditioning'], impactLevel: 'low', environment: ['track', 'field'] },
    ],
  },
  {
    family: 'athletics-jumper',
    description: 'Jump event drills for approach rhythm, penultimate mechanics, and landing precision.',
    subcategory: 'athletics_jumper',
    movementPattern: 'jumper_drill',
    trainingIntent: ['sport_drill', 'power', 'plyometrics'],
    primaryMuscles: ['glutes', 'quadriceps'],
    secondaryMuscles: ['hamstrings', 'calves'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: ['athletics'],
    positionTags: ['jumper'],
    fitStartTags: ['power', 'landing_control'],
    movementQualityTags: ['approach_rhythm', 'penultimate_control'],
    goalTags: ['power', 'athletic_performance', 'match_readiness'],
    suitableBlocks: ['main'],
    impactLevel: 'high',
    variants: [
      { slug: 'jumper-pop-up', name: 'Jumper Pop-Up', environment: ['track', 'field'] },
      { slug: 'jumper-penultimate-run', name: 'Jumper Penultimate Run', environment: ['track', 'field'] },
      { slug: 'jumper-bounding-approach', name: 'Jumper Bounding Approach', environment: ['track', 'field'] },
      { slug: 'jumper-takeoff-stick', name: 'Jumper Takeoff Stick', category: 'rehab', subcategory: 'landing_control', trainingIntent: ['rehab', 'power', 'landing_control'], suitableBlocks: ['rehab', 'main'], readinessSuitability: ['moderate', 'high'] },
      { slug: 'jumper-depth-pop', name: 'Jumper Depth Pop', environment: ['track', 'field'], readinessSuitability: ['high'] },
      { slug: 'jumper-approach-rhythm-repeats', name: 'Jumper Approach Rhythm Repeats', environment: ['track', 'field'] },
    ],
  },
  {
    family: 'athletics-thrower',
    description: 'Throw event drills for hip-block sequencing, rotational power, and overhead resilience.',
    subcategory: 'athletics_thrower',
    movementPattern: 'thrower_drill',
    trainingIntent: ['sport_drill', 'power', 'strength'],
    primaryMuscles: ['obliques', 'glutes'],
    secondaryMuscles: ['rotator_cuff', 'triceps'],
    jointsInvolved: ['hips', 'spine', 'shoulders'],
    sportTags: ['athletics'],
    positionTags: ['thrower'],
    fitStartTags: ['power', 'rotational_control'],
    movementQualityTags: ['hip_block', 'separation'],
    goalTags: ['power', 'athletic_performance', 'match_readiness'],
    suitableBlocks: ['main', 'accessory'],
    variants: [
      { slug: 'thrower-medball-step-and-throw', name: 'Thrower Med Ball Step and Throw', equipmentRequired: ['med_ball'], environment: ['field', 'gym'] },
      { slug: 'thrower-hip-block-drill', name: 'Thrower Hip Block Drill', environment: ['field', 'gym'] },
      { slug: 'thrower-separation-hold', name: 'Thrower Separation Hold', category: 'strength', subcategory: 'position_strength', trainingIntent: ['stability', 'power'], suitableBlocks: ['accessory', 'main'], impactLevel: 'low' },
      { slug: 'thrower-overhead-band-rhythm', name: 'Thrower Overhead Band Rhythm', category: 'strength', subcategory: 'shoulder_endurance', trainingIntent: ['stability', 'sport_drill'], equipmentRequired: ['band'], environment: ['gym', 'field'], suitableBlocks: ['accessory', 'main'], impactLevel: 'low' },
      { slug: 'thrower-rotational-release', name: 'Thrower Rotational Release', equipmentRequired: ['med_ball'], environment: ['field', 'gym'] },
      { slug: 'thrower-return-to-throw-preview', name: 'Thrower Return to Throw Preview', category: 'rehab', subcategory: 'return_to_play', trainingIntent: ['rehab', 'sport_drill', 'return_to_play'], equipmentRequired: ['light_ball'], environment: ['field', 'gym'], suitableBlocks: ['rehab', 'main'], readinessSuitability: ['moderate', 'high'] },
    ],
  },
  {
    family: 'athletics-general-prep',
    description: 'General track prep drills for posture, stiffness, and global coordination.',
    subcategory: 'athletics_general',
    movementPattern: 'track_prep',
    trainingIntent: ['warmup', 'sport_drill', 'movement_prep'],
    primaryMuscles: ['full_body'],
    secondaryMuscles: ['diaphragm'],
    jointsInvolved: ['hips', 'knees', 'ankles', 'shoulders'],
    sportTags: ['athletics'],
    positionTags: ['sprinter', 'middle-distance', 'jumper', 'thrower'],
    fitStartTags: ['movement_prep'],
    movementQualityTags: ['coordination', 'rhythm'],
    goalTags: ['athletic_performance', 'match_readiness'],
    suitableBlocks: ['warmup'],
    category: 'warmup',
    impactLevel: 'moderate',
    variants: [
      { slug: 'track-drill-series-1', name: 'Track Drill Series 1' },
      { slug: 'track-drill-series-2', name: 'Track Drill Series 2' },
      { slug: 'track-walk-skip-run', name: 'Track Walk Skip Run' },
      { slug: 'track-mobility-circuit', name: 'Track Mobility Circuit', category: 'warmup', subcategory: 'movement_prep', impactLevel: 'low' },
      { slug: 'track-pogo-combo', name: 'Track Pogo Combo' },
      { slug: 'track-posture-rehearsal', name: 'Track Posture Rehearsal', impactLevel: 'low' },
    ],
  },
]

const extraConditioningFamilies: DrillFamilyConfig[] = [
  {
    family: 'court-conditioning',
    description: 'Court-based conditioning that preserves sharp footwork instead of turning the day sloppy.',
    subcategory: 'court_conditioning',
    movementPattern: 'court_conditioning',
    trainingIntent: ['conditioning', 'agility', 'sport_drill'],
    primaryMuscles: ['quadriceps', 'calves'],
    secondaryMuscles: ['glutes', 'trunk'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: ['badminton', 'football', 'general_fitness'],
    fitStartTags: ['conditioning', 'agility'],
    movementQualityTags: ['repeat_effort', 'court_rhythm'],
    goalTags: ['endurance', 'match_readiness', 'athletic_performance'],
    suitableBlocks: ['conditioning'],
    variants: [
      { slug: 'court-corner-repeat', name: 'Court Corner Repeat', environment: ['court'] },
      { slug: 'court-zig-zag-repeat', name: 'Court Zig Zag Repeat', environment: ['court'] },
      { slug: 'court-box-shuffle', name: 'Court Box Shuffle', environment: ['court'] },
      { slug: 'court-closeout-series', name: 'Court Closeout Series', environment: ['court'] },
      { slug: 'court-reactive-circuit', name: 'Court Reactive Circuit', environment: ['court'], equipmentRequired: ['partner'] },
      { slug: 'court-recovery-lap', name: 'Court Recovery Lap', category: 'recovery', subcategory: 'active_recovery', trainingIntent: ['recovery', 'conditioning'], suitableBlocks: ['recovery', 'conditioning'], impactLevel: 'low', environment: ['court'] },
    ],
  },
  {
    family: 'field-conditioning',
    description: 'Field-conditioning patterns that blend stride quality with repeatable effort.',
    subcategory: 'field_conditioning',
    movementPattern: 'field_conditioning',
    trainingIntent: ['conditioning', 'speed_endurance'],
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['quadriceps', 'calves'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: ['football', 'cricket', 'general_fitness'],
    fitStartTags: ['conditioning', 'repeat_effort'],
    movementQualityTags: ['repeat_effort'],
    goalTags: ['endurance', 'match_readiness'],
    suitableBlocks: ['conditioning'],
    variants: [
      { slug: 'field-20-20-float', name: 'Field 20-20 Float', environment: ['field'] },
      { slug: 'field-arc-shuttle', name: 'Field Arc Shuttle', environment: ['field'] },
      { slug: 'field-curve-and-cruise', name: 'Field Curve and Cruise', environment: ['field'] },
      { slug: 'field-goalbox-repeat', name: 'Field Goalbox Repeat', environment: ['field'] },
      { slug: 'field-pressure-run', name: 'Field Pressure Run', environment: ['field'] },
      { slug: 'field-tempo-walkback', name: 'Field Tempo Walkback', category: 'recovery', subcategory: 'active_recovery', trainingIntent: ['recovery', 'aerobic_base'], suitableBlocks: ['recovery', 'conditioning'], impactLevel: 'low', environment: ['field'] },
    ],
  },
  {
    family: 'medball-power',
    description: 'Medicine-ball power series for low-skill explosive intent with clear explainable transfer.',
    subcategory: 'medball_power',
    movementPattern: 'medball_power',
    trainingIntent: ['power', 'athletic_performance'],
    primaryMuscles: ['obliques', 'glutes'],
    secondaryMuscles: ['lats', 'triceps'],
    jointsInvolved: ['hips', 'spine', 'shoulders'],
    sportTags: genericSports,
    fitStartTags: ['power'],
    movementQualityTags: ['force_transfer', 'rotational_timing'],
    goalTags: ['power', 'athletic_performance', 'match_readiness'],
    suitableBlocks: ['main', 'accessory'],
    variants: [
      { slug: 'medball-overhead-slam', name: 'Med Ball Overhead Slam', equipmentRequired: ['med_ball'], environment: ['gym', 'field'] },
      { slug: 'medball-chest-pass', name: 'Med Ball Chest Pass', equipmentRequired: ['med_ball'], environment: ['gym', 'field'] },
      { slug: 'medball-lateral-heave', name: 'Med Ball Lateral Heave', equipmentRequired: ['med_ball'], environment: ['gym', 'field'] },
      { slug: 'medball-shotput-step', name: 'Med Ball Shotput Step', equipmentRequired: ['med_ball'], environment: ['gym', 'field'] },
      { slug: 'medball-scoop-repeat', name: 'Med Ball Scoop Repeat', equipmentRequired: ['med_ball'], environment: ['gym', 'field'] },
      { slug: 'medball-pop-to-stick', name: 'Med Ball Pop to Stick', category: 'rehab', subcategory: 'return_to_play', trainingIntent: ['rehab', 'power', 'landing_control'], equipmentRequired: ['med_ball'], environment: ['gym', 'field'], suitableBlocks: ['rehab', 'main'], readinessSuitability: ['moderate', 'high'] },
    ],
  },
  {
    family: 'coordination-ladder',
    description: 'Coordination-ladder patterns that sharpen foot timing without pretending the ladder itself is the sport.',
    subcategory: 'coordination',
    movementPattern: 'coordination',
    trainingIntent: ['movement_prep', 'agility', 'warmup'],
    primaryMuscles: ['calves', 'hip_flexors'],
    secondaryMuscles: ['glutes', 'trunk'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    sportTags: genericSports,
    fitStartTags: ['coordination', 'confidence'],
    movementQualityTags: ['foot_timing'],
    goalTags: ['agility', 'confidence', 'athletic_performance'],
    suitableBlocks: ['warmup', 'main'],
    category: 'warmup',
    impactLevel: 'low',
    variants: [
      { slug: 'ladder-one-in', name: 'Ladder One In' },
      { slug: 'ladder-two-in', name: 'Ladder Two In' },
      { slug: 'ladder-ickey', name: 'Ladder Ickey' },
      { slug: 'ladder-lateral-run', name: 'Ladder Lateral Run' },
      { slug: 'ladder-in-out-react', name: 'Ladder In-Out React' },
      { slug: 'ladder-crossover-pattern', name: 'Ladder Crossover Pattern' },
    ],
  },
  {
    family: 'movement-prep-combo',
    description: 'Mixed movement-prep combos for low-friction session starts when time is tight.',
    category: 'warmup',
    subcategory: 'movement_prep_combo',
    movementPattern: 'movement_prep_combo',
    trainingIntent: ['warmup', 'movement_prep'],
    primaryMuscles: ['full_body'],
    secondaryMuscles: ['diaphragm'],
    jointsInvolved: ['hips', 'knees', 'ankles', 'shoulders', 'spine'],
    sportTags: genericSports,
    fitStartTags: ['movement_prep', 'confidence'],
    movementQualityTags: ['session_readiness'],
    goalTags: ['athletic_performance', 'general_fitness'],
    suitableBlocks: ['warmup'],
    impactLevel: 'low',
    variants: [
      { slug: 'prep-march-skip-open', name: 'Prep March Skip Open' },
      { slug: 'prep-squat-reach-shuffle', name: 'Prep Squat Reach Shuffle' },
      { slug: 'prep-lunge-rotate-march', name: 'Prep Lunge Rotate March' },
      { slug: 'prep-ankle-hip-rib', name: 'Prep Ankle Hip Rib' },
      { slug: 'prep-court-fast-feet', name: 'Prep Court Fast Feet' },
      { slug: 'prep-track-drill-mix', name: 'Prep Track Drill Mix' },
    ],
  },
]

export const sportConditioningCatalog = [
  ...genericFamilies.flatMap(drillFamily),
  ...cricketFamilies.flatMap(drillFamily),
  ...footballFamilies.flatMap(drillFamily),
  ...badmintonFamilies.flatMap(drillFamily),
  ...athleticsFamilies.flatMap(drillFamily),
  ...extraConditioningFamilies.flatMap(drillFamily),
]
