import type { Environment, SupportedSport } from '@/lib/product/types'
import { makeSeries } from '@/lib/product/exercises/shared'

const generalSportTags: SupportedSport[] = ['general_fitness', 'football', 'cricket', 'badminton', 'athletics']

export const strengthAndPowerCatalog = [
  ...makeSeries(
    {
      family: 'squat',
      description: 'A foundational squat pattern for lower-body force production, posture, and trunk stiffness.',
      category: 'strength',
      subcategory: 'compound_lower',
      movementPattern: 'squat',
      trainingIntent: ['strength', 'power', 'hypertrophy'],
      primaryMuscles: ['quadriceps', 'glutes'],
      secondaryMuscles: ['adductors', 'trunk'],
      jointsInvolved: ['hips', 'knees', 'ankles'],
      difficulty: 'intermediate',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['bodyweight'],
      environment: ['gym', 'home'] as Environment[],
      unilateralOrBilateral: 'bilateral',
      impactLevel: 'moderate',
      intensityProfile: 'moderate',
      estimatedDurationSeconds: 180,
      defaultPrescription: { sets: 4, reps: '5-8', restSeconds: 90, intensity: 'progressive load', rpe: 7, tempo: '21X1' },
      coachingCues: [
        'Own the tripod foot before descending.',
        'Let the ribs stay stacked over the pelvis as you drive up.',
      ],
      instructions: [
        'Set your stance so the feet feel stable and the hips can sit between them.',
        'Descend with control while keeping the torso braced and knees tracking over the mid-foot.',
        'Drive through the floor and finish tall without losing the stacked torso.',
      ],
      commonMistakes: ['Crashing into the bottom position.', 'Letting the heels peel up or the chest collapse.'],
      regressions: ['box-squat', 'counterbalance-squat', 'chair-squat'],
      progressions: ['front-squat', 'back-squat', 'paused-front-squat'],
      substitutions: ['trap-bar-deadlift', 'step-up', 'split-squat'],
      contraindications: ['acute_knee_pain', 'acute_low_back_spasm'],
      injuryConstraints: ['knee_irritability', 'lumbar_irritability'],
      sorenessConstraints: ['quad_dominant_day'],
      fatigueConstraints: ['high_cns_fatigue'],
      readinessSuitability: ['moderate', 'high'],
      goalTags: ['strength', 'muscle_gain', 'athletic_performance', 'body_recomposition'],
      sportTags: generalSportTags,
      positionTags: ['midfielder', 'defender', 'fast bowler', 'sprinter', 'jumper'],
      fitStartTags: ['lower_body_strength', 'force_production'],
      recoveryTags: [],
      rehabTags: ['return_to_strength'],
      movementQualityTags: ['triple_flexion', 'bracing', 'force_absorption'],
      suitableBlocks: ['main', 'accessory'],
    },
    [
      { slug: 'bw-counterbalance-squat', name: 'Counterbalance Squat', equipmentRequired: ['bodyweight'], difficulty: 'beginner', defaultPrescription: { sets: 3, reps: '8-10', restSeconds: 60, rpe: 6, tempo: '31X1' }, regressions: ['chair-squat'], progressions: ['db-goblet-squat'], suitableBlocks: ['warmup', 'accessory'] },
      { slug: 'db-goblet-squat', name: 'DB Goblet Squat', equipmentRequired: ['dumbbell'], environment: ['gym', 'home'], difficulty: 'beginner', coachingCues: ['Use the bell to keep the torso honest.'], progressions: ['db-tempo-goblet-squat', 'bb-front-squat'] },
      { slug: 'db-tempo-goblet-squat', name: 'DB Tempo Goblet Squat', equipmentRequired: ['dumbbell'], environment: ['gym', 'home'], difficulty: 'intermediate', defaultPrescription: { sets: 3, reps: '6-8', restSeconds: 75, rpe: 7, tempo: '41X1' }, trainingIntent: ['strength', 'hypertrophy', 'control'] },
      { slug: 'bb-front-squat', name: 'BB Front Squat', equipmentRequired: ['barbell', 'rack'], environment: ['gym'], difficulty: 'intermediate', progressions: ['bb-paused-front-squat', 'bb-back-squat'] },
      { slug: 'bb-paused-front-squat', name: 'BB Paused Front Squat', equipmentRequired: ['barbell', 'rack'], environment: ['gym'], difficulty: 'advanced', defaultPrescription: { sets: 4, reps: '3-5', restSeconds: 120, rpe: 8, tempo: '22X1' }, trainingIntent: ['strength', 'power', 'position_control'] },
      { slug: 'bb-back-squat', name: 'BB Back Squat', equipmentRequired: ['barbell', 'rack'], environment: ['gym'], difficulty: 'advanced', defaultPrescription: { sets: 5, reps: '3-5', restSeconds: 150, rpe: 8, tempo: '21X1' }, trainingIntent: ['strength', 'power'] },
    ]
  ),
  ...makeSeries(
    {
      family: 'hinge',
      description: 'Posterior-chain hinge work for force production, sprint support, and trunk stiffness.',
      category: 'strength',
      subcategory: 'hinge',
      movementPattern: 'hinge',
      trainingIntent: ['strength', 'power', 'posterior_chain'],
      primaryMuscles: ['glutes', 'hamstrings'],
      secondaryMuscles: ['spinal_erectors', 'grip'],
      jointsInvolved: ['hips', 'knees'],
      difficulty: 'intermediate',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['bodyweight'],
      environment: ['gym', 'home'] as Environment[],
      unilateralOrBilateral: 'mixed',
      impactLevel: 'low',
      intensityProfile: 'moderate',
      estimatedDurationSeconds: 150,
      defaultPrescription: { sets: 4, reps: '5-8', restSeconds: 90, intensity: 'posterior-chain load', rpe: 7, tempo: '31X1' },
      coachingCues: ['Push the hips back without losing rib position.', 'Let the hamstrings own the eccentric.'],
      instructions: [
        'Set the feet under the hips and grip the implement or load pattern.',
        'Drive the hips back while keeping the shins relatively quiet and the trunk braced.',
        'Return by pushing the floor away and squeezing the hips through.',
      ],
      commonMistakes: ['Turning the hinge into a squat.', 'Losing the lats and folding the trunk.'],
      regressions: ['hip-hinge-dowel', 'kb-deadlift'],
      progressions: ['bb-rdl', 'trap-bar-deadlift', 'single-leg-rdl'],
      substitutions: ['hip-thrust', 'hamstring-slide', 'cable-pull-through'],
      contraindications: ['acute_low_back_spasm'],
      injuryConstraints: ['lumbar_irritability', 'acute_hamstring_strain'],
      sorenessConstraints: ['posterior_chain_domsy'],
      fatigueConstraints: ['high_cns_fatigue'],
      readinessSuitability: ['moderate', 'high'],
      goalTags: ['strength', 'athletic_performance', 'injury_reduction', 'body_recomposition'],
      sportTags: generalSportTags,
      positionTags: ['fast bowler', 'midfielder', 'sprinter', 'jumper', 'striker'],
      fitStartTags: ['posterior_chain', 'acceleration'],
      recoveryTags: [],
      rehabTags: ['hamstring_return_to_strength'],
      movementQualityTags: ['hip_projection', 'posterior_chain_tension', 'bracing'],
      suitableBlocks: ['main', 'accessory'],
    },
    [
      { slug: 'hip-hinge-dowel', name: 'Hip Hinge Dowel Drill', equipmentRequired: ['dowel'], environment: ['gym', 'home'], difficulty: 'beginner', trainingIntent: ['movement_quality', 'strength'], suitableBlocks: ['warmup', 'accessory'], defaultPrescription: { sets: 2, reps: '8', restSeconds: 30, rpe: 4, tempo: '31X1' } },
      { slug: 'kb-deadlift', name: 'KB Deadlift', equipmentRequired: ['kettlebell'], environment: ['gym', 'home'], difficulty: 'beginner' },
      { slug: 'db-rdl', name: 'DB Romanian Deadlift', equipmentRequired: ['dumbbell'], environment: ['gym', 'home'], difficulty: 'intermediate' },
      { slug: 'bb-rdl', name: 'BB Romanian Deadlift', equipmentRequired: ['barbell'], environment: ['gym'], difficulty: 'intermediate', progressions: ['trap-bar-deadlift', 'bb-snatch-grip-rdl'] },
      { slug: 'trap-bar-deadlift', name: 'Trap Bar Deadlift', equipmentRequired: ['trap_bar'], environment: ['gym'], difficulty: 'advanced', defaultPrescription: { sets: 5, reps: '3-5', restSeconds: 150, rpe: 8, tempo: '21X1' }, trainingIntent: ['strength', 'power'] },
      { slug: 'single-leg-rdl', name: 'Single-Leg RDL', equipmentRequired: ['dumbbell'], environment: ['gym', 'home'], difficulty: 'advanced', unilateralOrBilateral: 'unilateral', suitableBlocks: ['accessory', 'rehab'] },
    ]
  ),
  ...makeSeries(
    {
      family: 'split-squat',
      description: 'Single-leg strength work that builds force, balance, and braking control.',
      category: 'strength',
      subcategory: 'single_leg',
      movementPattern: 'split_squat',
      trainingIntent: ['strength', 'hypertrophy', 'stability'],
      primaryMuscles: ['quadriceps', 'glutes'],
      secondaryMuscles: ['adductors', 'calves'],
      jointsInvolved: ['hips', 'knees', 'ankles'],
      difficulty: 'intermediate',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['bodyweight'],
      environment: ['gym', 'home', 'field', 'court'] as Environment[],
      unilateralOrBilateral: 'unilateral',
      impactLevel: 'moderate',
      intensityProfile: 'moderate',
      estimatedDurationSeconds: 160,
      defaultPrescription: { sets: 3, reps: '6-8/side', restSeconds: 75, intensity: 'control + load', rpe: 7, tempo: '31X1' },
      coachingCues: ['Let the front foot own the floor.', 'Stay tall enough to keep the pelvis level.'],
      instructions: [
        'Set up in a split stance with enough width for balance.',
        'Lower under control until both legs load without collapsing the front arch.',
        'Drive through the front foot and finish stacked over the hips.',
      ],
      commonMistakes: ['Standing too narrow and wobbling.', 'Dumping into the front knee without hip control.'],
      regressions: ['split-squat-iso-hold', 'assisted-split-squat'],
      progressions: ['db-rear-foot-elevated-split-squat', 'db-walking-lunge'],
      substitutions: ['step-up', 'reverse-lunge', 'single-leg-rdl'],
      contraindications: ['acute_knee_pain'],
      injuryConstraints: ['knee_irritability', 'adductor_strain'],
      sorenessConstraints: ['quad_dominant_day'],
      fatigueConstraints: ['high_cns_fatigue'],
      readinessSuitability: ['moderate', 'high'],
      goalTags: ['strength', 'muscle_gain', 'injury_reduction', 'athletic_performance'],
      sportTags: generalSportTags,
      positionTags: ['fast bowler', 'wicketkeeper', 'midfielder', 'singles', 'jumper'],
      fitStartTags: ['single_leg_strength', 'deceleration'],
      recoveryTags: [],
      rehabTags: ['return_to_run'],
      movementQualityTags: ['single_leg_control', 'frontal_plane_control', 'braking_mechanics'],
      suitableBlocks: ['main', 'accessory', 'rehab'],
    },
    [
      { slug: 'split-squat-iso-hold', name: 'Split Squat Iso Hold', difficulty: 'beginner', trainingIntent: ['strength', 'stability', 'rehab'], defaultPrescription: { sets: 3, reps: '20-30s/side', durationSeconds: 30, restSeconds: 45, intensity: 'isometric', rpe: 6 }, suitableBlocks: ['rehab', 'accessory'] },
      { slug: 'assisted-split-squat', name: 'Assisted Split Squat', equipmentRequired: ['bodyweight', 'support'], difficulty: 'beginner' },
      { slug: 'bw-reverse-lunge', name: 'Bodyweight Reverse Lunge', equipmentRequired: ['bodyweight'], environment: ['gym', 'home', 'field', 'court'], difficulty: 'beginner' },
      { slug: 'db-reverse-lunge', name: 'DB Reverse Lunge', equipmentRequired: ['dumbbell'], environment: ['gym', 'home'], difficulty: 'intermediate' },
      { slug: 'db-rear-foot-elevated-split-squat', name: 'DB Rear-Foot-Elevated Split Squat', equipmentRequired: ['dumbbell', 'bench'], environment: ['gym', 'home'], difficulty: 'advanced' },
      { slug: 'db-walking-lunge', name: 'DB Walking Lunge', equipmentRequired: ['dumbbell'], environment: ['gym', 'field'], difficulty: 'advanced', trainingIntent: ['strength', 'conditioning'], suitableBlocks: ['accessory', 'conditioning'] },
    ]
  ),
  ...makeSeries(
    {
      family: 'hip-thrust',
      description: 'Glute-dominant work for hip extension power and posterior-chain support.',
      category: 'strength',
      subcategory: 'glute_strength',
      movementPattern: 'hip_extension',
      trainingIntent: ['strength', 'hypertrophy', 'power'],
      primaryMuscles: ['glutes'],
      secondaryMuscles: ['hamstrings', 'trunk'],
      jointsInvolved: ['hips', 'knees'],
      difficulty: 'beginner',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['bodyweight'],
      environment: ['gym', 'home'] as Environment[],
      unilateralOrBilateral: 'mixed',
      impactLevel: 'low',
      intensityProfile: 'moderate',
      estimatedDurationSeconds: 150,
      defaultPrescription: { sets: 3, reps: '8-12', restSeconds: 60, intensity: 'glute drive', rpe: 6, tempo: '20X2' },
      coachingCues: ['Finish through the hips without arching the back.', 'Keep the chin slightly tucked and ribs quiet.'],
      instructions: [
        'Set the upper back against the support or floor depending on the variation.',
        'Drive through the feet and extend the hips until the trunk and thighs align.',
        'Pause at the top for glute tension before lowering with control.',
      ],
      commonMistakes: ['Overextending the lumbar spine.', 'Pushing through the toes instead of the full foot.'],
      regressions: ['glute-bridge', 'glute-bridge-march'],
      progressions: ['db-hip-thrust', 'bb-hip-thrust', 'single-leg-hip-thrust'],
      substitutions: ['kb-deadlift', 'hamstring-slide', 'step-up'],
      contraindications: ['acute_low_back_spasm'],
      injuryConstraints: ['lumbar_irritability'],
      sorenessConstraints: ['posterior_chain_domsy'],
      fatigueConstraints: [],
      readinessSuitability: ['low', 'moderate', 'high'],
      goalTags: ['strength', 'muscle_gain', 'athletic_performance', 'injury_reduction'],
      sportTags: generalSportTags,
      positionTags: ['fast bowler', 'sprinter', 'midfielder', 'striker'],
      fitStartTags: ['glute_strength'],
      recoveryTags: [],
      rehabTags: ['hip_extension_rebuild'],
      movementQualityTags: ['hip_extension', 'pelvic_control'],
      suitableBlocks: ['accessory', 'rehab'],
    },
    [
      { slug: 'glute-bridge', name: 'Glute Bridge', suitableBlocks: ['warmup', 'accessory', 'rehab'] },
      { slug: 'glute-bridge-march', name: 'Glute Bridge March', trainingIntent: ['stability', 'strength'], unilateralOrBilateral: 'mixed', suitableBlocks: ['warmup', 'rehab'] },
      { slug: 'db-hip-thrust', name: 'DB Hip Thrust', equipmentRequired: ['dumbbell', 'bench'], environment: ['gym', 'home'], difficulty: 'intermediate' },
      { slug: 'bb-hip-thrust', name: 'BB Hip Thrust', equipmentRequired: ['barbell', 'bench'], environment: ['gym'], difficulty: 'advanced', defaultPrescription: { sets: 4, reps: '5-8', restSeconds: 90, rpe: 8, tempo: '20X2' } },
      { slug: 'single-leg-hip-thrust', name: 'Single-Leg Hip Thrust', equipmentRequired: ['bodyweight', 'bench'], environment: ['gym', 'home'], unilateralOrBilateral: 'unilateral', difficulty: 'advanced' },
      { slug: 'band-hip-thrust-pulse', name: 'Band Hip Thrust Pulse', equipmentRequired: ['band', 'bench'], environment: ['gym', 'home'], difficulty: 'intermediate', trainingIntent: ['hypertrophy', 'glute_endurance'] },
    ]
  ),
  ...makeSeries(
    {
      family: 'horizontal-push',
      description: 'Horizontal pressing for upper-body strength, trunk control, and contact resilience.',
      category: 'strength',
      subcategory: 'upper_push',
      movementPattern: 'horizontal_push',
      trainingIntent: ['strength', 'hypertrophy'],
      primaryMuscles: ['chest', 'triceps'],
      secondaryMuscles: ['anterior_shoulder', 'trunk'],
      jointsInvolved: ['shoulders', 'elbows', 'wrists'],
      difficulty: 'intermediate',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['bodyweight'],
      environment: ['gym', 'home'] as Environment[],
      unilateralOrBilateral: 'mixed',
      impactLevel: 'low',
      intensityProfile: 'moderate',
      estimatedDurationSeconds: 150,
      defaultPrescription: { sets: 4, reps: '6-10', restSeconds: 75, intensity: 'pressing load', rpe: 7, tempo: '21X1' },
      coachingCues: ['Keep the rib cage quiet while you press.', 'Reach long without shrugging into the ears.'],
      instructions: [
        'Set the shoulders back into a stable but not rigid position.',
        'Lower with control to the target depth while keeping the forearms aligned.',
        'Press smoothly without losing scapular rhythm or trunk position.',
      ],
      commonMistakes: ['Flared elbows and shrugged shoulders.', 'Pressing through pain or unstable wrists.'],
      regressions: ['wall-push-up', 'incline-push-up'],
      progressions: ['db-floor-press', 'db-bench-press', 'bb-bench-press'],
      substitutions: ['landmine-press', 'push-up-plus', 'band-press'],
      contraindications: ['acute_shoulder_pain'],
      injuryConstraints: ['shoulder_irritability', 'wrist_irritability'],
      sorenessConstraints: ['upper_push_domsy'],
      fatigueConstraints: [],
      readinessSuitability: ['moderate', 'high'],
      goalTags: ['strength', 'muscle_gain', 'athletic_performance'],
      sportTags: generalSportTags,
      positionTags: ['defender', 'wicketkeeper', 'thrower'],
      fitStartTags: ['upper_body_strength'],
      recoveryTags: [],
      rehabTags: ['controlled_press_return'],
      movementQualityTags: ['scapular_control', 'upper_body_force'],
      suitableBlocks: ['main', 'accessory'],
    },
    [
      { slug: 'wall-push-up', name: 'Wall Push-Up', difficulty: 'beginner', suitableBlocks: ['warmup', 'rehab', 'accessory'] },
      { slug: 'incline-push-up', name: 'Incline Push-Up', equipmentRequired: ['bodyweight', 'bench'], environment: ['gym', 'home'], difficulty: 'beginner' },
      { slug: 'push-up', name: 'Push-Up', equipmentRequired: ['bodyweight'], environment: ['gym', 'home', 'field'], difficulty: 'intermediate' },
      { slug: 'db-floor-press', name: 'DB Floor Press', equipmentRequired: ['dumbbell'], environment: ['gym', 'home'], difficulty: 'intermediate', suitableBlocks: ['accessory', 'main'] },
      { slug: 'db-bench-press', name: 'DB Bench Press', equipmentRequired: ['dumbbell', 'bench'], environment: ['gym', 'home'], difficulty: 'intermediate' },
      { slug: 'bb-bench-press', name: 'BB Bench Press', equipmentRequired: ['barbell', 'bench', 'rack'], environment: ['gym'], difficulty: 'advanced', defaultPrescription: { sets: 5, reps: '3-5', restSeconds: 120, rpe: 8, tempo: '21X1' } },
    ]
  ),
  ...makeSeries(
    {
      family: 'landmine-press',
      description: 'Shoulder-friendly angled pressing that blends upper-body force with trunk control.',
      category: 'strength',
      subcategory: 'vertical_push',
      movementPattern: 'angled_push',
      trainingIntent: ['strength', 'power', 'stability'],
      primaryMuscles: ['shoulders', 'triceps'],
      secondaryMuscles: ['serratus', 'trunk'],
      jointsInvolved: ['shoulders', 'elbows'],
      difficulty: 'beginner',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['bodyweight'],
      environment: ['gym', 'home'] as Environment[],
      unilateralOrBilateral: 'mixed',
      impactLevel: 'low',
      intensityProfile: 'moderate',
      estimatedDurationSeconds: 120,
      defaultPrescription: { sets: 3, reps: '6-8/side', restSeconds: 60, intensity: 'smooth press', rpe: 6, tempo: '21X1' },
      coachingCues: ['Press up and slightly out, not straight overhead.', 'Use the trunk to support the shoulder, not to cheat the rep.'],
      instructions: [
        'Set the base position tall with ribs stacked over the pelvis.',
        'Press through a clean arc while keeping the shoulder blade rotating naturally.',
        'Lower under control and reset fully before the next rep.',
      ],
      commonMistakes: ['Arching to finish the press.', 'Letting the elbow flare without scapular support.'],
      regressions: ['band-press-out', 'half-kneeling-band-press'],
      progressions: ['half-kneeling-landmine-press', 'standing-landmine-press', 'push-press'],
      substitutions: ['db-floor-press', 'push-up-plus', 'scap-push-up'],
      contraindications: ['acute_shoulder_pain'],
      injuryConstraints: ['shoulder_irritability'],
      sorenessConstraints: ['upper_push_domsy'],
      fatigueConstraints: ['high_cns_fatigue'],
      readinessSuitability: ['low', 'moderate', 'high'],
      goalTags: ['strength', 'athletic_performance', 'injury_reduction'],
      sportTags: generalSportTags,
      positionTags: ['fast bowler', 'goalkeeper', 'thrower', 'doubles'],
      fitStartTags: ['shoulder_resilience'],
      recoveryTags: [],
      rehabTags: ['scapular_control', 'controlled_press_return'],
      movementQualityTags: ['scapular_upward_rotation', 'serratus_control'],
      suitableBlocks: ['accessory', 'rehab'],
    },
    [
      { slug: 'band-press-out', name: 'Band Press-Out', equipmentRequired: ['band'], environment: ['gym', 'home'], difficulty: 'beginner', suitableBlocks: ['warmup', 'rehab'] },
      { slug: 'half-kneeling-band-press', name: 'Half-Kneeling Band Press', equipmentRequired: ['band'], environment: ['gym', 'home'], difficulty: 'beginner', suitableBlocks: ['rehab', 'accessory'] },
      { slug: 'half-kneeling-landmine-press', name: 'Half-Kneeling Landmine Press', equipmentRequired: ['landmine', 'barbell'], environment: ['gym'], difficulty: 'intermediate' },
      { slug: 'standing-landmine-press', name: 'Standing Landmine Press', equipmentRequired: ['landmine', 'barbell'], environment: ['gym'], difficulty: 'intermediate', suitableBlocks: ['main', 'accessory'] },
      { slug: 'single-arm-db-shoulder-press', name: 'Single-Arm DB Shoulder Press', equipmentRequired: ['dumbbell'], environment: ['gym', 'home'], difficulty: 'advanced', contraindications: ['acute_shoulder_pain', 'neck_irritability'], readinessSuitability: ['moderate', 'high'] },
      { slug: 'push-press', name: 'Push Press', equipmentRequired: ['barbell'], environment: ['gym'], difficulty: 'advanced', category: 'conditioning', subcategory: 'power_press', trainingIntent: ['power', 'athletic_performance'], defaultPrescription: { sets: 4, reps: '3-4', restSeconds: 120, rpe: 8, tempo: 'X0X1' }, suitableBlocks: ['main', 'conditioning'], readinessSuitability: ['high'] },
    ]
  ),
  ...makeSeries(
    {
      family: 'row',
      description: 'Upper-back pulling that supports posture, sprint mechanics, and shoulder balance.',
      category: 'strength',
      subcategory: 'upper_pull',
      movementPattern: 'row',
      trainingIntent: ['strength', 'hypertrophy', 'stability'],
      primaryMuscles: ['lats', 'mid_back'],
      secondaryMuscles: ['biceps', 'rear_shoulder'],
      jointsInvolved: ['shoulders', 'elbows', 'thoracic_spine'],
      difficulty: 'beginner',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['bodyweight'],
      environment: ['gym', 'home'] as Environment[],
      unilateralOrBilateral: 'mixed',
      impactLevel: 'low',
      intensityProfile: 'moderate',
      estimatedDurationSeconds: 120,
      defaultPrescription: { sets: 3, reps: '8-10', restSeconds: 60, intensity: 'tension', rpe: 6, tempo: '21X1' },
      coachingCues: ['Pull from the shoulder blade first, then the elbow.', 'Own the finish without jutting the chin.'],
      instructions: [
        'Set the trunk stable and establish a clean line of pull.',
        'Initiate by drawing the shoulder blade toward the spine without shrugging.',
        'Finish the row under control and lower smoothly back to the start.',
      ],
      commonMistakes: ['Yanking with the biceps first.', 'Losing trunk position to chase range.'],
      regressions: ['band-row', 'ring-row'],
      progressions: ['single-arm-db-row', 'chest-supported-db-row', 'seal-row'],
      substitutions: ['pull-down', 'face-pull', 'scap-retraction-hold'],
      contraindications: ['acute_shoulder_pain'],
      injuryConstraints: ['shoulder_irritability', 'elbow_irritability'],
      sorenessConstraints: ['upper_pull_domsy'],
      fatigueConstraints: [],
      readinessSuitability: ['low', 'moderate', 'high'],
      goalTags: ['strength', 'muscle_gain', 'injury_reduction', 'athletic_performance'],
      sportTags: generalSportTags,
      positionTags: ['wicketkeeper', 'goalkeeper', 'defender', 'thrower'],
      fitStartTags: ['upper_back_strength'],
      recoveryTags: [],
      rehabTags: ['scapular_control', 'posture_restore'],
      movementQualityTags: ['scapular_retraction', 'thoracic_position'],
      suitableBlocks: ['accessory', 'rehab'],
    },
    [
      { slug: 'band-row', name: 'Band Row', equipmentRequired: ['band'], environment: ['gym', 'home'], difficulty: 'beginner', suitableBlocks: ['warmup', 'rehab', 'accessory'] },
      { slug: 'ring-row', name: 'Ring Row', equipmentRequired: ['rings'], environment: ['gym', 'home'], difficulty: 'beginner', suitableBlocks: ['accessory', 'rehab'] },
      { slug: 'single-arm-db-row', name: 'Single-Arm DB Row', equipmentRequired: ['dumbbell', 'bench'], environment: ['gym', 'home'], unilateralOrBilateral: 'unilateral', difficulty: 'intermediate' },
      { slug: 'chest-supported-db-row', name: 'Chest-Supported DB Row', equipmentRequired: ['dumbbell', 'bench'], environment: ['gym'], difficulty: 'intermediate' },
      { slug: 'seal-row', name: 'Seal Row', equipmentRequired: ['barbell', 'bench'], environment: ['gym'], difficulty: 'advanced' },
      { slug: 'face-pull', name: 'Face Pull', equipmentRequired: ['cable', 'rope'], environment: ['gym'], difficulty: 'beginner', trainingIntent: ['stability', 'posture'], suitableBlocks: ['warmup', 'accessory', 'rehab'] },
    ]
  ),
  ...makeSeries(
    {
      family: 'pull-up',
      description: 'Vertical pulling progressions for upper-body force and shoulder control.',
      category: 'strength',
      subcategory: 'vertical_pull',
      movementPattern: 'vertical_pull',
      trainingIntent: ['strength', 'hypertrophy'],
      primaryMuscles: ['lats', 'upper_back'],
      secondaryMuscles: ['biceps', 'trunk'],
      jointsInvolved: ['shoulders', 'elbows'],
      difficulty: 'intermediate',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['pullup_bar'],
      environment: ['gym', 'home'] as Environment[],
      unilateralOrBilateral: 'bilateral',
      impactLevel: 'low',
      intensityProfile: 'moderate',
      estimatedDurationSeconds: 90,
      defaultPrescription: { sets: 4, reps: '4-6', restSeconds: 90, intensity: 'bodyweight strength', rpe: 8, tempo: '21X1' },
      coachingCues: ['Start by setting the shoulder blades, not by swinging.', 'Keep the ribs from flaring as you clear the bar.'],
      instructions: [
        'Hang with tension and set the shoulders before initiating.',
        'Pull the elbows down toward the ribs while staying long through the neck.',
        'Lower with control to a full hang or the planned range.',
      ],
      commonMistakes: ['Kipping when strict control is the goal.', 'Half reps with no scapular control.'],
      regressions: ['band-assisted-pull-up', 'lat-pull-down'],
      progressions: ['weighted-pull-up', 'sternum-pull-up'],
      substitutions: ['row', 'ring-row', 'band-row'],
      contraindications: ['acute_shoulder_pain', 'acute_elbow_pain'],
      injuryConstraints: ['shoulder_irritability', 'elbow_irritability'],
      sorenessConstraints: ['upper_pull_domsy'],
      fatigueConstraints: ['high_grip_fatigue'],
      readinessSuitability: ['moderate', 'high'],
      goalTags: ['strength', 'muscle_gain', 'athletic_performance'],
      sportTags: generalSportTags,
      positionTags: ['goalkeeper', 'wicketkeeper', 'defender'],
      fitStartTags: ['upper_body_strength'],
      recoveryTags: [],
      rehabTags: ['controlled_hang_progression'],
      movementQualityTags: ['scapular_depression', 'upper_body_force'],
      suitableBlocks: ['main', 'accessory'],
    },
    [
      { slug: 'lat-pull-down', name: 'Lat Pull-Down', equipmentRequired: ['machine'], environment: ['gym'], difficulty: 'beginner', suitableBlocks: ['accessory'] },
      { slug: 'band-assisted-pull-up', name: 'Band-Assisted Pull-Up', equipmentRequired: ['band', 'pullup_bar'], environment: ['gym', 'home'], difficulty: 'beginner' },
      { slug: 'chin-up', name: 'Chin-Up', equipmentRequired: ['pullup_bar'], environment: ['gym', 'home'], difficulty: 'intermediate' },
      { slug: 'pull-up', name: 'Pull-Up', equipmentRequired: ['pullup_bar'], environment: ['gym', 'home'], difficulty: 'intermediate' },
      { slug: 'weighted-pull-up', name: 'Weighted Pull-Up', equipmentRequired: ['pullup_bar', 'weight_belt'], environment: ['gym'], difficulty: 'advanced', defaultPrescription: { sets: 5, reps: '3-4', restSeconds: 120, rpe: 8, tempo: '21X1' } },
    ]
  ),
  ...makeSeries(
    {
      family: 'core-anti-extension',
      description: 'Trunk work that resists extension and keeps force transfer clean.',
      category: 'strength',
      subcategory: 'core',
      movementPattern: 'anti_extension',
      trainingIntent: ['core', 'stability', 'injury_reduction'],
      primaryMuscles: ['anterior_core'],
      secondaryMuscles: ['hip_flexors', 'serratus'],
      jointsInvolved: ['spine', 'shoulders', 'hips'],
      difficulty: 'beginner',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['bodyweight'],
      environment: ['gym', 'home', 'field'] as Environment[],
      unilateralOrBilateral: 'mixed',
      impactLevel: 'low',
      intensityProfile: 'low',
      estimatedDurationSeconds: 90,
      defaultPrescription: { sets: 3, reps: '20-30s', durationSeconds: 30, restSeconds: 45, intensity: 'position control', rpe: 5 },
      coachingCues: ['Breathe behind the brace instead of holding your breath.', 'Own the pelvis before adding arm or leg motion.'],
      instructions: [
        'Set the trunk with a long spine and lightly tucked ribs.',
        'Perform the hold or reach pattern without lumbar extension.',
        'Stop the set when position quality falls off.',
      ],
      commonMistakes: ['Holding the breath and shaking through bad positions.', 'Letting the low back arch as the lever gets longer.'],
      regressions: ['dead-bug'],
      progressions: ['hollow-hold', 'body-saw'],
      substitutions: ['side-plank', 'pallof-press'],
      contraindications: [],
      injuryConstraints: ['acute_low_back_spasm'],
      sorenessConstraints: [],
      fatigueConstraints: [],
      readinessSuitability: ['low', 'moderate', 'high'],
      goalTags: ['injury_reduction', 'athletic_performance', 'strength'],
      sportTags: generalSportTags,
      positionTags: ['fast bowler', 'spinner', 'midfielder', 'singles', 'sprinter'],
      fitStartTags: ['core_strength'],
      recoveryTags: [],
      rehabTags: ['trunk_control'],
      movementQualityTags: ['bracing', 'force_transfer'],
      suitableBlocks: ['warmup', 'accessory', 'rehab'],
    },
    [
      { slug: 'dead-bug', name: 'Dead Bug' },
      { slug: 'dead-bug-band-pulldown', name: 'Dead Bug Band Pulldown', equipmentRequired: ['band'], environment: ['gym', 'home'], difficulty: 'intermediate' },
      { slug: 'hollow-hold', name: 'Hollow Hold', difficulty: 'intermediate' },
      { slug: 'body-saw', name: 'Body Saw', equipmentRequired: ['slider'], environment: ['gym', 'home'], difficulty: 'advanced' },
      { slug: 'ab-wheel-rollout', name: 'Ab Wheel Rollout', equipmentRequired: ['ab_wheel'], environment: ['gym', 'home'], difficulty: 'advanced', readinessSuitability: ['moderate', 'high'], contraindications: ['acute_low_back_spasm'] },
    ]
  ),
  ...makeSeries(
    {
      family: 'core-anti-rotation',
      description: 'Anti-rotation and lateral trunk work for transfer, contact, and rotational control.',
      category: 'strength',
      subcategory: 'core_rotation',
      movementPattern: 'anti_rotation',
      trainingIntent: ['core', 'stability', 'injury_reduction'],
      primaryMuscles: ['obliques', 'trunk'],
      secondaryMuscles: ['glutes', 'serratus'],
      jointsInvolved: ['spine', 'hips', 'shoulders'],
      difficulty: 'beginner',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['bodyweight'],
      environment: ['gym', 'home', 'field', 'court'] as Environment[],
      unilateralOrBilateral: 'mixed',
      impactLevel: 'low',
      intensityProfile: 'low',
      estimatedDurationSeconds: 75,
      defaultPrescription: { sets: 3, reps: '8-10/side', restSeconds: 45, intensity: 'position control', rpe: 5 },
      coachingCues: ['Keep the zipper line facing forward.', 'Let the trunk resist movement before it creates it.'],
      instructions: [
        'Set the pelvis and ribs so the trunk feels stacked.',
        'Perform the press, hold, or lift pattern without twisting off line.',
        'Reset between reps if the posture starts to drift.',
      ],
      commonMistakes: ['Chasing range by turning the torso.', 'Holding tension in the neck instead of the trunk.'],
      regressions: ['side-plank-knees'],
      progressions: ['tall-kneeling-pallof-press', 'half-kneeling-lift', 'copenhagen-plank'],
      substitutions: ['dead-bug', 'carry', 'rotation-med-ball-scoop'],
      contraindications: [],
      injuryConstraints: ['acute_low_back_spasm', 'acute_adductor_strain'],
      sorenessConstraints: [],
      fatigueConstraints: [],
      readinessSuitability: ['low', 'moderate', 'high'],
      goalTags: ['injury_reduction', 'athletic_performance', 'return_to_play'],
      sportTags: generalSportTags,
      positionTags: ['fast bowler', 'spinner', 'midfielder', 'singles', 'thrower'],
      fitStartTags: ['trunk_control'],
      recoveryTags: [],
      rehabTags: ['lumbopelvic_control', 'groin_resilience'],
      movementQualityTags: ['anti_rotation', 'frontal_plane_control'],
      suitableBlocks: ['warmup', 'accessory', 'rehab'],
    },
    [
      { slug: 'side-plank-knees', name: 'Side Plank (Knees)' },
      { slug: 'side-plank', name: 'Side Plank', difficulty: 'intermediate' },
      { slug: 'pallof-press', name: 'Pallof Press', equipmentRequired: ['band'], environment: ['gym', 'home'], difficulty: 'beginner' },
      { slug: 'tall-kneeling-pallof-press', name: 'Tall-Kneeling Pallof Press', equipmentRequired: ['band'], environment: ['gym', 'home'], difficulty: 'intermediate' },
      { slug: 'half-kneeling-lift', name: 'Half-Kneeling Lift', equipmentRequired: ['cable'], environment: ['gym'], difficulty: 'advanced' },
      { slug: 'copenhagen-plank', name: 'Copenhagen Plank', equipmentRequired: ['bench'], environment: ['gym', 'home'], difficulty: 'advanced', rehabTags: ['groin_resilience', 'adductor_control'], positionTags: ['midfielder', 'defender', 'singles'] },
    ]
  ),
  ...makeSeries(
    {
      family: 'carry',
      description: 'Loaded carries teach posture, trunk stiffness, and simple repeatable work capacity.',
      category: 'strength',
      subcategory: 'carry',
      movementPattern: 'carry',
      trainingIntent: ['strength', 'stability', 'conditioning'],
      primaryMuscles: ['grip', 'trunk'],
      secondaryMuscles: ['glutes', 'upper_back'],
      jointsInvolved: ['shoulders', 'hips', 'ankles'],
      difficulty: 'beginner',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['bodyweight'],
      environment: ['gym', 'field', 'home'] as Environment[],
      unilateralOrBilateral: 'mixed',
      impactLevel: 'low',
      intensityProfile: 'variable',
      estimatedDurationSeconds: 60,
      defaultPrescription: { sets: 4, reps: '20-30m', durationSeconds: 30, restSeconds: 45, intensity: 'steady brace', rpe: 6 },
      coachingCues: ['Walk like the trunk is a pillar.', 'Let the breath stay quiet while the implement wants to pull you around.'],
      instructions: [
        'Stand tall and brace before initiating the carry.',
        'Walk under control with even steps and eyes forward.',
        'Finish the rep without leaning or rushing the turn.',
      ],
      commonMistakes: ['Shrugging or side-bending into the load.', 'Taking choppy, rushed steps.'],
      regressions: ['march-carry'],
      progressions: ['farmer-carry', 'suitcase-carry', 'front-rack-carry'],
      substitutions: ['pallof-press', 'step-up', 'sled-drag'],
      contraindications: ['acute_shoulder_pain'],
      injuryConstraints: ['shoulder_irritability', 'grip_irritability'],
      sorenessConstraints: [],
      fatigueConstraints: ['high_grip_fatigue'],
      readinessSuitability: ['low', 'moderate', 'high'],
      goalTags: ['strength', 'athletic_performance', 'injury_reduction', 'body_recomposition'],
      sportTags: generalSportTags,
      positionTags: ['wicketkeeper', 'defender', 'midfielder', 'doubles'],
      fitStartTags: ['trunk_stability'],
      recoveryTags: [],
      rehabTags: ['gait_control'],
      movementQualityTags: ['gait_stiffness', 'bracing'],
      suitableBlocks: ['accessory', 'conditioning', 'rehab'],
    },
    [
      { slug: 'march-carry', name: 'March Carry', equipmentRequired: ['dumbbell'], environment: ['gym', 'home'], difficulty: 'beginner', suitableBlocks: ['warmup', 'rehab'] },
      { slug: 'farmer-carry', name: 'Farmer Carry', equipmentRequired: ['dumbbell'], environment: ['gym', 'home', 'field'], difficulty: 'intermediate' },
      { slug: 'suitcase-carry', name: 'Suitcase Carry', equipmentRequired: ['dumbbell'], environment: ['gym', 'home', 'field'], unilateralOrBilateral: 'unilateral', difficulty: 'intermediate' },
      { slug: 'front-rack-carry', name: 'Front Rack Carry', equipmentRequired: ['kettlebell'], environment: ['gym', 'home'], difficulty: 'advanced' },
      { slug: 'cross-body-carry', name: 'Cross-Body Carry', equipmentRequired: ['kettlebell'], environment: ['gym', 'home'], unilateralOrBilateral: 'mixed', difficulty: 'advanced' },
    ]
  ),
  ...makeSeries(
    {
      family: 'hamstring-resilience',
      description: 'Posterior-chain resilience work for sprint tolerance and late-session force protection.',
      category: 'strength',
      subcategory: 'hamstring_resilience',
      movementPattern: 'knee_flexion',
      trainingIntent: ['strength', 'injury_reduction', 'return_to_play'],
      primaryMuscles: ['hamstrings'],
      secondaryMuscles: ['glutes', 'calves'],
      jointsInvolved: ['knees', 'hips'],
      difficulty: 'intermediate',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['bodyweight'],
      environment: ['gym', 'home', 'field'] as Environment[],
      unilateralOrBilateral: 'mixed',
      impactLevel: 'low',
      intensityProfile: 'moderate',
      estimatedDurationSeconds: 100,
      defaultPrescription: { sets: 3, reps: '5-8', restSeconds: 60, intensity: 'slow eccentric', rpe: 7, tempo: '50X1' },
      coachingCues: ['Own the lowering phase more than the finish.', 'Keep the hips long and avoid cramping the back.'],
      instructions: [
        'Set up so the hamstrings can lengthen under control.',
        'Control the eccentric through the full safe range.',
        'Use assistance as needed to keep quality high instead of failing ugly.',
      ],
      commonMistakes: ['Dropping through the eccentric.', 'Turning the set into a low-back movement.'],
      regressions: ['hamstring-bridge', 'slider-leg-curl'],
      progressions: ['nordic-lower', 'nordic-catch'],
      substitutions: ['rdl', 'hip-thrust', 'single-leg-rdl'],
      contraindications: ['acute_hamstring_strain'],
      injuryConstraints: ['hamstring_irritability'],
      sorenessConstraints: ['posterior_chain_domsy'],
      fatigueConstraints: ['high_cns_fatigue'],
      readinessSuitability: ['moderate', 'high'],
      goalTags: ['injury_reduction', 'athletic_performance', 'return_to_play', 'speed'],
      sportTags: ['football', 'cricket', 'athletics', 'general_fitness'],
      positionTags: ['fast bowler', 'winger', 'striker', 'sprinter'],
      fitStartTags: ['hamstring_resilience'],
      recoveryTags: [],
      rehabTags: ['hamstring_return_to_play'],
      movementQualityTags: ['posterior_chain_tension', 'eccentric_control'],
      suitableBlocks: ['accessory', 'rehab'],
    },
    [
      { slug: 'hamstring-bridge', name: 'Hamstring Bridge', difficulty: 'beginner', suitableBlocks: ['rehab', 'warmup', 'accessory'] },
      { slug: 'slider-leg-curl', name: 'Slider Leg Curl', equipmentRequired: ['slider'], environment: ['gym', 'home'], difficulty: 'intermediate' },
      { slug: 'single-leg-slider-leg-curl', name: 'Single-Leg Slider Leg Curl', equipmentRequired: ['slider'], environment: ['gym', 'home'], unilateralOrBilateral: 'unilateral', difficulty: 'advanced' },
      { slug: 'nordic-lower', name: 'Nordic Lower', equipmentRequired: ['partner', 'anchor'], environment: ['gym', 'field'], difficulty: 'advanced' },
      { slug: 'nordic-catch', name: 'Nordic Catch', equipmentRequired: ['partner', 'anchor'], environment: ['gym', 'field'], difficulty: 'advanced', readinessSuitability: ['high'], trainingIntent: ['strength', 'injury_reduction', 'eccentric_power'] },
      { slug: 'razor-curl', name: 'Razor Curl', equipmentRequired: ['partner', 'anchor'], environment: ['gym', 'field'], difficulty: 'advanced', readinessSuitability: ['high'] },
    ]
  ),
  ...makeSeries(
    {
      family: 'calf-foot',
      description: 'Ankle stiffness and calf strength work for repeat contacts, deceleration, and durability.',
      category: 'strength',
      subcategory: 'ankle_stiffness',
      movementPattern: 'ankle_extension',
      trainingIntent: ['strength', 'stability', 'injury_reduction'],
      primaryMuscles: ['calves', 'foot_intrinsics'],
      secondaryMuscles: ['soleus', 'tibialis'],
      jointsInvolved: ['ankles', 'toes'],
      difficulty: 'beginner',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['bodyweight'],
      environment: ['gym', 'home', 'field', 'court', 'track'] as Environment[],
      unilateralOrBilateral: 'mixed',
      impactLevel: 'low',
      intensityProfile: 'low',
      estimatedDurationSeconds: 60,
      defaultPrescription: { sets: 3, reps: '10-15', restSeconds: 30, intensity: 'controlled stiffness', rpe: 5 },
      coachingCues: ['Finish through the big toe without rolling out.', 'Let the ankle stay stacked instead of wobbling.'],
      instructions: [
        'Set the foot tripod before loading onto the forefoot.',
        'Rise or hold through the planned range while staying aligned over the toes.',
        'Lower slowly enough to own the eccentric.',
      ],
      commonMistakes: ['Rolling to the outside edge of the foot.', 'Bouncing through reps with no control.'],
      regressions: ['double-leg-calf-raise'],
      progressions: ['single-leg-calf-raise', 'seated-soleus-raise', 'weighted-calf-raise'],
      substitutions: ['ankle-pogo', 'march-carry', 'step-up'],
      contraindications: ['acute_achilles_pain'],
      injuryConstraints: ['achilles_irritability', 'ankle_irritability'],
      sorenessConstraints: ['calf_domsy'],
      fatigueConstraints: [],
      readinessSuitability: ['low', 'moderate', 'high'],
      goalTags: ['injury_reduction', 'athletic_performance', 'speed', 'agility'],
      sportTags: generalSportTags,
      positionTags: ['singles', 'winger', 'fullback', 'sprinter', 'jumper'],
      fitStartTags: ['ankle_stability'],
      recoveryTags: [],
      rehabTags: ['ankle_stability', 'achilles_reload'],
      movementQualityTags: ['ankle_stiffness', 'foot_control'],
      suitableBlocks: ['warmup', 'accessory', 'rehab'],
    },
    [
      { slug: 'double-leg-calf-raise', name: 'Double-Leg Calf Raise' },
      { slug: 'single-leg-calf-raise', name: 'Single-Leg Calf Raise', unilateralOrBilateral: 'unilateral', difficulty: 'intermediate' },
      { slug: 'seated-soleus-raise', name: 'Seated Soleus Raise', equipmentRequired: ['dumbbell', 'bench'], environment: ['gym', 'home'], difficulty: 'intermediate' },
      { slug: 'weighted-calf-raise', name: 'Weighted Calf Raise', equipmentRequired: ['dumbbell'], environment: ['gym', 'home'], difficulty: 'advanced' },
      { slug: 'tibialis-raise', name: 'Tibialis Raise', equipmentRequired: ['wall'], environment: ['gym', 'home'], difficulty: 'beginner', primaryMuscles: ['tibialis'], secondaryMuscles: ['foot_intrinsics'], trainingIntent: ['strength', 'injury_reduction', 'stability'] },
    ]
  ),
  ...makeSeries(
    {
      family: 'rotation-power',
      description: 'Rotational trunk and hip power that supports throwing, striking, and cutting sports.',
      category: 'conditioning',
      subcategory: 'rotational_power',
      movementPattern: 'rotation',
      trainingIntent: ['power', 'sport_drill', 'athletic_performance'],
      primaryMuscles: ['obliques', 'glutes'],
      secondaryMuscles: ['lats', 'adductors'],
      jointsInvolved: ['hips', 'spine', 'shoulders'],
      difficulty: 'intermediate',
      experienceLevelSuitability: ['beginner', 'intermediate', 'advanced'],
      equipmentRequired: ['med_ball'],
      environment: ['gym', 'field', 'court'] as Environment[],
      unilateralOrBilateral: 'mixed',
      impactLevel: 'moderate',
      intensityProfile: 'high',
      estimatedDurationSeconds: 45,
      defaultPrescription: { sets: 4, reps: '4-6/side', restSeconds: 60, intensity: 'violent but clean', rpe: 7 },
      coachingCues: ['Rotate from the hips into a braced trunk.', 'End the throw with a clean deceleration, not a collapse.'],
      instructions: [
        'Load the back hip and set the trunk before initiating the throw.',
        'Rotate forcefully while keeping the sequence smooth from ground to hand.',
        'Stick the finish and reset each rep instead of rushing.',
      ],
      commonMistakes: ['Spinning without loading the back hip.', 'Throwing from the arms with no trunk connection.'],
      regressions: ['half-kneeling-med-ball-rotation'],
      progressions: ['rotational-med-ball-shot-put', 'med-ball-scoop-toss'],
      substitutions: ['pallof-press', 'band-chop', 'shadow-swing-step'],
      contraindications: ['acute_low_back_spasm'],
      injuryConstraints: ['lumbar_irritability', 'oblique_strain'],
      sorenessConstraints: ['rotational_domsy'],
      fatigueConstraints: ['high_cns_fatigue'],
      readinessSuitability: ['moderate', 'high'],
      goalTags: ['athletic_performance', 'speed', 'power', 'match_readiness'],
      sportTags: ['cricket', 'football', 'badminton', 'athletics', 'general_fitness'],
      positionTags: ['batter', 'spinner', 'fast bowler', 'midfielder', 'thrower'],
      fitStartTags: ['rotational_power'],
      recoveryTags: [],
      rehabTags: ['return_to_throw'],
      movementQualityTags: ['hip_shoulder_separation', 'deceleration_control'],
      suitableBlocks: ['main', 'conditioning'],
    },
    [
      { slug: 'half-kneeling-med-ball-rotation', name: 'Half-Kneeling Med Ball Rotation', equipmentRequired: ['med_ball'], environment: ['gym', 'field'], difficulty: 'beginner', suitableBlocks: ['warmup', 'accessory'] },
      { slug: 'standing-med-ball-rotation', name: 'Standing Med Ball Rotation', equipmentRequired: ['med_ball'], environment: ['gym', 'field'], difficulty: 'intermediate' },
      { slug: 'rotational-med-ball-shot-put', name: 'Rotational Med Ball Shot Put', equipmentRequired: ['med_ball'], environment: ['gym', 'field'], difficulty: 'advanced' },
      { slug: 'med-ball-scoop-toss', name: 'Med Ball Scoop Toss', equipmentRequired: ['med_ball'], environment: ['gym', 'field'], difficulty: 'advanced' },
      { slug: 'step-behind-med-ball-scoop', name: 'Step-Behind Med Ball Scoop Toss', equipmentRequired: ['med_ball'], environment: ['field', 'court'], difficulty: 'advanced', readinessSuitability: ['high'] },
    ]
  ),
]
