import { athleteDailyFields } from '@/forms/schemas/athleteDaily'
import { athleteOnboardingFields } from '@/forms/schemas/athleteOnboarding'
import type { FormFlowDefinition } from '@/forms/types'

export const athleteOnboardingFlow: FormFlowDefinition = {
  id: 'athlete-onboarding-fast-start',
  version: '2026.04.fast-start',
  userType: 'athlete',
  kind: 'onboarding',
  title: 'Athlete Setup',
  description: 'A shorter setup that gets to the dashboard fast, then improves accuracy over time.',
  completionTargetSeconds: 90,
  fields: athleteOnboardingFields,
  steps: [
    {
      id: 'identity',
      title: 'Profile Name',
      goal: 'Create a usable athlete identity without making setup feel administrative.',
      fieldIds: ['fullName', 'username'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 12,
      interactionPattern: 'text inputs',
      helperCopy: 'One short screen. No long bio.',
    },
    {
      id: 'sport',
      title: 'Sport Context',
      goal: 'Anchor the sport model quickly so the system can infer baseline demands.',
      fieldIds: ['primarySport', 'position'],
      mandatory: true,
      optional: false,
      conditional: true,
      expectedSeconds: 10,
      interactionPattern: 'cards + inline text',
      helperCopy: 'Position appears only when it matters.',
    },
    {
      id: 'context',
      title: 'Athlete Snapshot',
      goal: 'Capture the smallest set of physiology and competitive context that meaningfully changes decisions.',
      fieldIds: ['age', 'biologicalSex', 'playingLevel', 'heightCm', 'weightKg'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 18,
      interactionPattern: 'number inputs + chips',
      helperCopy: 'Grouped on one screen because these inputs work best together.',
    },
    {
      id: 'goal',
      title: 'Primary Goal',
      goal: 'Focus the first dashboard and recommendation strategy around one clear priority.',
      fieldIds: ['primaryGoal'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 8,
      interactionPattern: 'goal cards',
    },
    {
      id: 'injury',
      title: 'Pain Check',
      goal: 'Capture only current pain or injury information needed to protect early recommendations.',
      fieldIds: ['currentIssue', 'injurySeverity', 'injuryLocations'],
      mandatory: true,
      optional: false,
      conditional: true,
      expectedSeconds: 15,
      interactionPattern: 'chips + body map',
      helperCopy: 'Only expands if the athlete reports a live issue.',
    },
    {
      id: 'consent',
      title: 'Finish Setup',
      goal: 'Collect legal consent and optional coach linking without burying the athlete in compliance copy.',
      fieldIds: ['coachLockerCode', 'platformConsent', 'medicalDisclaimerConsent', 'minorGuardianConsent'],
      mandatory: true,
      optional: true,
      conditional: true,
      expectedSeconds: 14,
      interactionPattern: 'toggle + short text input',
      helperCopy: 'The dashboard unlocks immediately after this.',
    },
  ],
}

export const athleteDailyFlow: FormFlowDefinition = {
  id: 'athlete-daily-quick',
  version: '2026.04.quick-check',
  userType: 'athlete',
  kind: 'daily',
  title: 'Athlete Check-In',
  description: 'A 10-second default check-in with deeper follow-ups only when signals look risky or ambiguous.',
  completionTargetSeconds: 10,
  fields: athleteDailyFields,
  defaultQuickSignalIds: ['energy', 'soreness', 'stress'],
  advancedSignalIds: ['sleepQuality', 'sleepDuration', 'painLocation', 'sessionCompletion', 'sessionRPE', 'sessionDuration'],
  steps: [
    {
      id: 'energy',
      title: 'Energy',
      goal: 'Measure central readiness with the fastest useful daily question.',
      fieldIds: ['energy'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 3,
      interactionPattern: 'emoji scale',
    },
    {
      id: 'soreness',
      title: 'Body Feel',
      goal: 'Capture neuromuscular readiness and pain risk in one glance.',
      fieldIds: ['soreness'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 3,
      interactionPattern: 'emoji scale',
    },
    {
      id: 'stress',
      title: 'Stress',
      goal: 'Capture mental and life load before training decisions are made.',
      fieldIds: ['stress'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 3,
      interactionPattern: 'emoji scale',
    },
    {
      id: 'sleep',
      title: 'Why So Flat?',
      goal: 'Ask one short follow-up when energy and stress need more explanation.',
      fieldIds: ['sleepQuality', 'sleepDuration'],
      mandatory: false,
      optional: false,
      conditional: true,
      expectedSeconds: 5,
      interactionPattern: 'chips',
      helperCopy: 'Only shown on low-energy or high-stress days.',
    },
    {
      id: 'pain',
      title: 'Pain Protection',
      goal: 'Locate the issue only when soreness is high enough to change risk management.',
      fieldIds: ['painLocation'],
      mandatory: false,
      optional: false,
      conditional: true,
      expectedSeconds: 5,
      interactionPattern: 'body map',
    },
    {
      id: 'load',
      title: 'Training Load',
      goal: 'Capture yesterday load only when the system needs it for better confidence.',
      fieldIds: ['sessionCompletion', 'sessionRPE', 'sessionDuration'],
      mandatory: false,
      optional: false,
      conditional: true,
      expectedSeconds: 6,
      interactionPattern: 'chips + sliders',
    },
  ],
}

