import { coachOnboardingFields } from '@/forms/schemas/coachOnboarding'
import type { FormFlowDefinition } from '@/forms/types'

export const coachOnboardingFlow: FormFlowDefinition = {
  id: 'coach-onboarding-fast',
  version: '2026.04.fast-start',
  userType: 'coach',
  kind: 'onboarding',
  title: 'Coach Setup',
  description: 'A shorter setup that gets coaches to their squad dashboard faster, then enriches structure later.',
  completionTargetSeconds: 60,
  fields: coachOnboardingFields,
  steps: [
    {
      id: 'identity',
      title: 'Coach Identity',
      goal: 'Create a usable coach profile without a long admin sequence.',
      fieldIds: ['fullName', 'username', 'mobileNumber'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 14,
      interactionPattern: 'text inputs',
    },
    {
      id: 'squad',
      title: 'Squad Setup',
      goal: 'Anchor sport, level, and team name so the first dashboard is correctly configured.',
      fieldIds: ['teamName', 'sportCoached', 'coachingLevel'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 14,
      interactionPattern: 'text + cards',
    },
    {
      id: 'structure',
      title: 'Team Structure',
      goal: 'Understand whether the coach manages one team, many groups, or a portfolio of individuals.',
      fieldIds: ['teamType', 'numberOfAthletes', 'teamStructure'],
      mandatory: true,
      optional: false,
      conditional: true,
      expectedSeconds: 12,
      interactionPattern: 'cards + inline text',
    },
    {
      id: 'focus',
      title: 'Main Focus',
      goal: 'Let the coach pick one priority so the dashboard can rank the right alerts first.',
      fieldIds: ['mainCoachingFocus'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 8,
      interactionPattern: 'goal cards',
    },
  ],
}
