import { individualDailyFields } from '@/forms/schemas/individualDaily'
import { individualOnboardingFields } from '@/forms/schemas/individualOnboarding'
import type { FormFlowDefinition } from '@/forms/types'

export const individualOnboardingFlow: FormFlowDefinition = {
  id: 'individual-fitstart-fast',
  version: '2026.04.fast-start',
  userType: 'individual',
  kind: 'onboarding',
  title: 'FitStart',
  description: 'A shorter setup focused on goal, reality, and limitations instead of a broad intake form.',
  completionTargetSeconds: 75,
  fields: individualOnboardingFields,
  steps: [
    {
      id: 'profile',
      title: 'Quick Snapshot',
      goal: 'Capture the smallest useful body-profile anchor for a safe first plan.',
      fieldIds: ['age', 'gender', 'heightCm', 'weightKg'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 15,
      interactionPattern: 'number inputs + chips',
    },
    {
      id: 'day-shape',
      title: 'Day Shape',
      goal: 'Understand movement reality and fatigue context without a long lifestyle interview.',
      fieldIds: ['occupation', 'activityLevel'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 10,
      interactionPattern: 'cards',
    },
    {
      id: 'goal',
      title: 'Main Goal',
      goal: 'Focus the first journey around one clear outcome and one time horizon.',
      fieldIds: ['primaryGoal', 'timeHorizon', 'intensityPreference'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 14,
      interactionPattern: 'goal cards + chips',
    },
    {
      id: 'setup',
      title: 'What You Have',
      goal: 'Only ask for constraints that directly change what plan the user can actually follow.',
      fieldIds: ['equipmentAccess'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 10,
      interactionPattern: 'multi-select chips',
    },
    {
      id: 'limitations',
      title: 'Any Limitation?',
      goal: 'Capture only live pain or limitation needed to avoid obviously poor recommendations.',
      fieldIds: ['injuryStatus', 'limitationArea'],
      mandatory: true,
      optional: false,
      conditional: true,
      expectedSeconds: 12,
      interactionPattern: 'chips + body map',
    },
  ],
}

export const individualDailyFlow: FormFlowDefinition = {
  id: 'individual-daily-quick',
  version: '2026.04.quick-check',
  userType: 'individual',
  kind: 'daily',
  title: 'Daily Pulse',
  description: 'Default check-in is three taps. Training details appear only when the user wants or needs them.',
  completionTargetSeconds: 10,
  fields: individualDailyFields,
  defaultQuickSignalIds: ['energy', 'stress', 'soreness'],
  advancedSignalIds: ['sleepQuality', 'sessionCompletion', 'trainingMinutes', 'sessionRPE', 'hydrationLiters'],
  steps: [
    {
      id: 'energy',
      title: 'Energy',
      goal: 'Get the strongest fast signal for how trainable today feels.',
      fieldIds: ['energy'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 3,
      interactionPattern: 'emoji scale',
    },
    {
      id: 'stress',
      title: 'Stress',
      goal: 'Capture non-training load because it changes recovery and adherence.',
      fieldIds: ['stress'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 3,
      interactionPattern: 'emoji scale',
    },
    {
      id: 'body',
      title: 'Body Feel',
      goal: 'Capture how physically ready the user feels right now.',
      fieldIds: ['soreness'],
      mandatory: true,
      optional: false,
      conditional: false,
      expectedSeconds: 3,
      interactionPattern: 'emoji scale',
    },
    {
      id: 'sleep',
      title: 'Sleep Follow-Up',
      goal: 'Add sleep only on ambiguous or low-readiness days.',
      fieldIds: ['sleepQuality'],
      mandatory: false,
      optional: false,
      conditional: true,
      expectedSeconds: 4,
      interactionPattern: 'chips',
    },
    {
      id: 'training',
      title: 'Training Capture',
      goal: 'Capture actual training load only when the user wants the model to learn from today.',
      fieldIds: ['sessionCompletion', 'trainingMinutes', 'sessionRPE'],
      mandatory: false,
      optional: false,
      conditional: true,
      expectedSeconds: 6,
      interactionPattern: 'chips + sliders',
    },
  ],
}

