import type { ObjectiveTestProtocolDefinition } from '@/lib/objective-tests/types'

const reactionProtocol: ObjectiveTestProtocolDefinition = {
  id: 'reaction_tap',
  family: 'neural',
  displayName: 'Reaction Tap',
  shortDescription: 'Five-tap sharpness check with AI-assisted trend interpretation.',
  analysisMode: 'ai_interpreted',
  captureMode: 'screen_tap',
  rolloutPhase: 1,
  supportedRoles: ['athlete', 'individual'],
  supportedSports: 'all',
  estimatedDurationMinutes: 2,
  estimatedLoad: 'very_low',
  heroLabel: 'AI-assisted sharpness anchor',
  protocolRules: [
    'Five accepted taps are required.',
    'False starts are tracked but not scored.',
    'Retest only once the full protocol is complete.',
  ],
  setupChecklist: [
    'Use one finger on the same part of the screen.',
    'Hold the phone still or place it on a stable surface.',
  ],
  whenUseful: [
    'You want one low-load measured sharpness signal.',
    'You want to compare how you feel against objective response speed.',
  ],
  whenToSkip: [
    'Your phone has severe touch lag.',
    'You already did this in the last 24 hours.',
  ],
  headlineMetric: {
    key: 'validated_reaction_ms',
    label: 'Validated reaction',
    unit: 'ms',
    direction: 'lower_better',
    decimals: 0,
    minimumDetectableChange: 10,
    provisionalThresholds: {
      good: 250,
      risk: [250, 309],
      critical: 310,
    },
  },
  secondaryMetrics: [
    {
      key: 'average_reaction_ms',
      label: 'Average reaction',
      unit: 'ms',
      direction: 'lower_better',
      decimals: 0,
      minimumDetectableChange: 12,
      provisionalThresholds: { good: 250, risk: [250, 309], critical: 310 },
    },
    {
      key: 'best_reaction_ms',
      label: 'Best tap',
      unit: 'ms',
      direction: 'lower_better',
      decimals: 0,
      minimumDetectableChange: 10,
      provisionalThresholds: { good: 230, risk: [230, 299], critical: 300 },
    },
    {
      key: 'consistency_ms',
      label: 'Consistency',
      unit: 'ms',
      direction: 'lower_better',
      decimals: 0,
      minimumDetectableChange: 8,
      provisionalThresholds: { good: 35, risk: [36, 55], critical: 56 },
    },
  ],
  baseline: {
    minimumAcceptedSessions: 3,
    initialMethod: 'first_3_median',
    rollingMethod: 'rolling_5_median',
    minimumDaysBetweenAnchorSessions: 2,
  },
  freshnessWindowHours: 168,
  cooldownHours: 24,
  weeklyCap: 2,
  validityRules: {
    minimumCaptureQuality: 0.75,
    minimumConfidence: 0.75,
    minimumAcceptedTrials: 5,
  },
  contraindications: [],
  decisionMappings: [
    { domain: 'neural_sharpness', coefficient: 1, maxInfluencePoints: 6 },
    { domain: 'speed_exposure_readiness', coefficient: 0.35, maxInfluencePoints: 2 },
  ],
}

const balanceProtocol: ObjectiveTestProtocolDefinition = {
  id: 'balance_single_leg',
  family: 'balance',
  displayName: 'Single-Leg Balance',
  shortDescription: 'AI pose analysis of single-leg control, sway, and left-right stability.',
  analysisMode: 'ai_pose',
  captureMode: 'camera_pose_upload',
  rolloutPhase: 1,
  supportedRoles: ['athlete', 'individual'],
  supportedSports: 'all',
  estimatedDurationMinutes: 4,
  estimatedLoad: 'low',
  heroLabel: 'AI balance scan',
  protocolRules: [
    'Record one left-leg hold and one right-leg hold.',
    'Keep the full body visible in a front-facing clip.',
    'Hands on hips, eyes open, flat surface.',
  ],
  setupChecklist: [
    'Place the phone steady at about hip height.',
    'Leave head, hips, knees, and feet fully visible.',
    'Use strong lighting and a flat floor.',
  ],
  whenUseful: [
    'You want a lower-limb control signal.',
    'You are monitoring rehab or unilateral stability.',
  ],
  whenToSkip: [
    'You feel dizzy or unstable.',
    'You have acute ankle or knee instability today.',
  ],
  headlineMetric: {
    key: 'normalized_sway_velocity_bw_per_s',
    label: 'Normalized sway',
    unit: 'bw/s',
    direction: 'lower_better',
    decimals: 2,
    minimumDetectableChange: 0.03,
    provisionalThresholds: {
      good: 0.18,
      risk: [0.19, 0.28],
      critical: 0.29,
    },
  },
  secondaryMetrics: [
    {
      key: 'hold_completion_sec',
      label: 'Hold time',
      unit: 's',
      direction: 'higher_better',
      decimals: 1,
      minimumDetectableChange: 1,
      provisionalThresholds: { good: 20, risk: [15, 19.9], critical: 14.9 },
    },
    {
      key: 'trunk_lean_variability_deg',
      label: 'Trunk variability',
      unit: 'deg',
      direction: 'lower_better',
      decimals: 1,
      minimumDetectableChange: 2,
      provisionalThresholds: { good: 6, risk: [6.1, 10], critical: 10.1 },
    },
    {
      key: 'pelvis_drop_variability_deg',
      label: 'Pelvis variability',
      unit: 'deg',
      direction: 'lower_better',
      decimals: 1,
      minimumDetectableChange: 2,
      provisionalThresholds: { good: 5, risk: [5.1, 8], critical: 8.1 },
    },
    {
      key: 'balance_asymmetry_percent',
      label: 'Balance asymmetry',
      unit: '%',
      direction: 'lower_better',
      decimals: 1,
      minimumDetectableChange: 5,
      provisionalThresholds: { good: 8, risk: [8.1, 14], critical: 14.1 },
    },
  ],
  baseline: {
    minimumAcceptedSessions: 3,
    initialMethod: 'first_3_median',
    rollingMethod: 'rolling_5_median',
    minimumDaysBetweenAnchorSessions: 3,
  },
  freshnessWindowHours: 168,
  cooldownHours: 48,
  weeklyCap: 2,
  validityRules: {
    minimumCaptureQuality: 0.7,
    minimumConfidence: 0.68,
    minimumFps: 24,
    requiredSides: ['left', 'right'],
  },
  contraindications: ['dizziness', 'acute ankle instability', 'acute knee instability'],
  decisionMappings: [
    { domain: 'postural_control', coefficient: 1, maxInfluencePoints: 5 },
    { domain: 'asymmetry_risk', coefficient: 0.7, maxInfluencePoints: 4 },
    { domain: 'return_to_play_confidence', coefficient: 0.9, maxInfluencePoints: 6, rehabMultiplier: 1.25 },
  ],
  alternativesWhenUnsafe: ['reaction_tap'],
}

const breathingProtocol: ObjectiveTestProtocolDefinition = {
  id: 'breathing_recovery',
  family: 'recovery',
  displayName: 'Breathing Recovery',
  shortDescription: 'AI-assisted recovery interpretation with guided effort and optional HR.',
  analysisMode: 'ai_sensor_fusion',
  captureMode: 'guided_timer_hr_optional',
  rolloutPhase: 1,
  supportedRoles: ['athlete', 'individual'],
  supportedSports: 'all',
  estimatedDurationMinutes: 4,
  estimatedLoad: 'low',
  heroLabel: 'AI recovery fusion',
  protocolRules: [
    'Complete the guided 60-second effort block.',
    'Add peak and 60-second HR if available for full influence.',
    'Without HR, the session is saved as supplemental only.',
  ],
  setupChecklist: [
    'Have a watch or synced health source if possible.',
    'Stop immediately if you feel chest pain, wheeze, or dizziness.',
  ],
  whenUseful: [
    'You want a recovery anchor after travel, poor sleep, or heat.',
    'You have a usable HR source and want more confidence in recovery interpretation.',
  ],
  whenToSkip: [
    'You feel unwell, dizzy, or have active respiratory symptoms.',
    'You have a medical reason to avoid the effort block.',
  ],
  headlineMetric: {
    key: 'hrr_60_bpm',
    label: 'HR recovery 60s',
    unit: 'bpm',
    direction: 'higher_better',
    decimals: 0,
    minimumDetectableChange: 5,
    provisionalThresholds: {
      good: 25,
      risk: [15, 24],
      critical: 14,
    },
  },
  secondaryMetrics: [
    {
      key: 'peak_hr_bpm',
      label: 'Peak HR',
      unit: 'bpm',
      direction: 'target_band',
      decimals: 0,
      minimumDetectableChange: 5,
      provisionalThresholds: { good: [120, 160], risk: [100, 119], critical: [0, 99] },
    },
    {
      key: 'hr_60s_bpm',
      label: 'HR at 60s',
      unit: 'bpm',
      direction: 'lower_better',
      decimals: 0,
      minimumDetectableChange: 5,
      provisionalThresholds: { good: 115, risk: [116, 135], critical: 136 },
    },
  ],
  baseline: {
    minimumAcceptedSessions: 3,
    initialMethod: 'first_3_median',
    rollingMethod: 'rolling_5_median',
    minimumDaysBetweenAnchorSessions: 2,
  },
  freshnessWindowHours: 168,
  cooldownHours: 48,
  weeklyCap: 2,
  validityRules: {
    minimumCaptureQuality: 0.5,
    minimumConfidence: 0.65,
  },
  contraindications: ['chest pain', 'fever', 'active respiratory illness', 'dizziness'],
  decisionMappings: [
    { domain: 'systemic_recovery', coefficient: 1, maxInfluencePoints: 5 },
    { domain: 'return_to_play_confidence', coefficient: 0.25, maxInfluencePoints: 1 },
  ],
}

const jumpProtocol: ObjectiveTestProtocolDefinition = {
  id: 'jump_landing_control',
  family: 'power',
  displayName: 'Jump Landing Control',
  shortDescription: 'AI pose analysis of jump amplitude, landing control, and stabilization.',
  analysisMode: 'ai_pose',
  captureMode: 'camera_pose_upload',
  rolloutPhase: 2,
  supportedRoles: ['athlete', 'individual'],
  supportedSports: 'all',
  estimatedDurationMinutes: 5,
  estimatedLoad: 'moderate',
  heroLabel: 'AI landing control scan',
  protocolRules: [
    'Record 3 countermovement jumps or snap-down landings.',
    'Keep feet and trunk fully visible.',
    'Use a front or front-45-degree camera angle.',
  ],
  setupChecklist: [
    'Use a flat, non-slippery surface.',
    'Leave overhead clearance and frame enough space around the landing.',
  ],
  whenUseful: [
    'You want a neuromuscular or landing-quality anchor.',
    'You are monitoring explosive readiness or late-stage rehab progression.',
  ],
  whenToSkip: [
    'You have lower-limb or back pain today.',
    'You are early in rehab or the surface is unsafe.',
  ],
  headlineMetric: {
    key: 'time_to_stabilization_ms',
    label: 'Time to stabilization',
    unit: 'ms',
    direction: 'lower_better',
    decimals: 0,
    minimumDetectableChange: 150,
    provisionalThresholds: {
      good: 1200,
      risk: [1201, 1800],
      critical: 1801,
    },
  },
  secondaryMetrics: [
    {
      key: 'landing_valgus_event_count',
      label: 'Valgus events',
      unit: 'count',
      direction: 'lower_better',
      decimals: 0,
      minimumDetectableChange: 1,
      provisionalThresholds: { good: 0, risk: [1, 1], critical: 2 },
    },
    {
      key: 'landing_asymmetry_percent',
      label: 'Landing asymmetry',
      unit: '%',
      direction: 'lower_better',
      decimals: 1,
      minimumDetectableChange: 5,
      provisionalThresholds: { good: 10, risk: [10.1, 14], critical: 14.1 },
    },
    {
      key: 'jump_amplitude_proxy_bw',
      label: 'Jump amplitude proxy',
      unit: 'bw',
      direction: 'higher_better',
      decimals: 2,
      minimumDetectableChange: 0.05,
      provisionalThresholds: { good: 0.35, risk: [0.2, 0.34], critical: 0.19 },
    },
  ],
  baseline: {
    minimumAcceptedSessions: 3,
    initialMethod: 'first_3_median',
    rollingMethod: 'rolling_5_median',
    minimumDaysBetweenAnchorSessions: 3,
  },
  freshnessWindowHours: 168,
  cooldownHours: 72,
  weeklyCap: 2,
  validityRules: {
    minimumCaptureQuality: 0.7,
    minimumConfidence: 0.68,
    minimumFps: 30,
  },
  contraindications: ['lower-limb pain', 'back pain', 'early rehab'],
  decisionMappings: [
    { domain: 'explosive_readiness', coefficient: 1, maxInfluencePoints: 7 },
    { domain: 'postural_control', coefficient: 0.6, maxInfluencePoints: 3 },
    { domain: 'asymmetry_risk', coefficient: 0.7, maxInfluencePoints: 4 },
    { domain: 'return_to_play_confidence', coefficient: 1, maxInfluencePoints: 8, rehabMultiplier: 1.25 },
  ],
  alternativesWhenUnsafe: ['balance_single_leg'],
}

const mobilityProtocol: ObjectiveTestProtocolDefinition = {
  id: 'mobility_battery',
  family: 'mobility',
  displayName: 'Mobility Battery',
  shortDescription: 'AI movement battery covering squat, shoulder, hinge, and ankle mobility.',
  analysisMode: 'ai_pose',
  captureMode: 'camera_pose_upload',
  rolloutPhase: 2,
  supportedRoles: ['athlete', 'individual'],
  supportedSports: 'all',
  estimatedDurationMinutes: 8,
  estimatedLoad: 'low',
  heroLabel: 'AI mobility battery',
  protocolRules: [
    'Upload one short clip for each guided subtest.',
    'Finish the full battery before saving the session.',
  ],
  setupChecklist: [
    'Use a steady phone and leave the full body visible.',
    'Follow the subtest-specific angle instructions on screen.',
  ],
  whenUseful: [
    'You want to see what movement limitation is bottlenecking training.',
    'You want a plan-focused signal rather than a pure readiness signal.',
  ],
  whenToSkip: [
    'You have acute pain or instability in the movement being tested.',
  ],
  headlineMetric: {
    key: 'mobility_battery_score',
    label: 'Battery score',
    unit: 'pts',
    direction: 'higher_better',
    decimals: 0,
    minimumDetectableChange: 5,
    provisionalThresholds: {
      good: 80,
      risk: [60, 79],
      critical: 59,
    },
  },
  secondaryMetrics: [
    {
      key: 'ankle_dorsiflexion_deg',
      label: 'Ankle dorsiflexion',
      unit: 'deg',
      direction: 'higher_better',
      decimals: 1,
      minimumDetectableChange: 5,
      provisionalThresholds: { good: 35, risk: [28, 34], critical: 27 },
    },
    {
      key: 'squat_depth_ratio',
      label: 'Squat depth ratio',
      unit: 'ratio',
      direction: 'lower_better',
      decimals: 2,
      minimumDetectableChange: 0.05,
      provisionalThresholds: { good: 1, risk: [1.01, 1.15], critical: 1.16 },
    },
    {
      key: 'shoulder_flexion_deg',
      label: 'Shoulder flexion',
      unit: 'deg',
      direction: 'higher_better',
      decimals: 1,
      minimumDetectableChange: 5,
      provisionalThresholds: { good: 165, risk: [150, 164], critical: 149 },
    },
  ],
  subtests: [
    { key: 'ankle_dorsiflexion', label: 'Ankle dorsiflexion', metrics: [] },
    { key: 'overhead_squat', label: 'Overhead squat', metrics: [] },
    { key: 'shoulder_flexion', label: 'Shoulder flexion', metrics: [] },
    { key: 'toe_touch_hinge', label: 'Toe touch and hinge', metrics: [] },
  ],
  baseline: {
    minimumAcceptedSessions: 2,
    initialMethod: 'first_3_median',
    rollingMethod: 'rolling_5_median',
    minimumDaysBetweenAnchorSessions: 5,
  },
  freshnessWindowHours: 336,
  cooldownHours: 168,
  weeklyCap: 1,
  validityRules: {
    minimumCaptureQuality: 0.65,
    minimumConfidence: 0.65,
    minimumFps: 24,
  },
  contraindications: ['acute pain', 'acute instability'],
  decisionMappings: [
    { domain: 'movement_capacity', coefficient: 1, maxInfluencePoints: 4 },
    { domain: 'asymmetry_risk', coefficient: 0.5, maxInfluencePoints: 2 },
    { domain: 'postural_control', coefficient: 0.35, maxInfluencePoints: 1 },
  ],
}

const sprintProtocol: ObjectiveTestProtocolDefinition = {
  id: 'sprint_10m',
  family: 'speed',
  displayName: 'Sprint 10m',
  shortDescription: 'AI pose timing pilot for 10m acceleration on a marked lane.',
  analysisMode: 'ai_pose',
  captureMode: 'camera_pose_upload',
  rolloutPhase: 3,
  supportedRoles: ['athlete', 'individual'],
  supportedSports: 'all',
  estimatedDurationMinutes: 5,
  estimatedLoad: 'high',
  heroLabel: 'AI sprint timing pilot',
  protocolRules: [
    'Record the full 10m lane with start and finish marks visible.',
    'Use one sprint effort per clip.',
  ],
  setupChecklist: [
    'Keep the full running lane in frame.',
    'Use strong daylight or a well-lit space.',
    'Only use this where the lane and surface are safe.',
  ],
  whenUseful: [
    'You want a pilot AI speed exposure signal in a supported, controlled setup.',
  ],
  whenToSkip: [
    'You are in pain, short on space, or the environment is unsafe.',
  ],
  headlineMetric: {
    key: 'sprint_10m_time_ms',
    label: '10m sprint time',
    unit: 'ms',
    direction: 'lower_better',
    decimals: 0,
    minimumDetectableChange: 40,
    provisionalThresholds: {
      good: 1800,
      risk: [1801, 2300],
      critical: 2301,
    },
  },
  secondaryMetrics: [
    {
      key: 'first_step_time_ms',
      label: 'First-step time',
      unit: 'ms',
      direction: 'lower_better',
      decimals: 0,
      minimumDetectableChange: 20,
      provisionalThresholds: { good: 350, risk: [351, 500], critical: 501 },
    },
    {
      key: 'step_count_10m',
      label: 'Step count',
      unit: 'count',
      direction: 'target_band',
      decimals: 0,
      minimumDetectableChange: 1,
      provisionalThresholds: { good: [6, 10], risk: [5, 11], critical: [0, 4] },
    },
  ],
  baseline: {
    minimumAcceptedSessions: 3,
    initialMethod: 'first_3_median',
    rollingMethod: 'rolling_5_median',
    minimumDaysBetweenAnchorSessions: 4,
  },
  freshnessWindowHours: 336,
  cooldownHours: 72,
  weeklyCap: 1,
  validityRules: {
    minimumCaptureQuality: 0.65,
    minimumConfidence: 0.62,
    minimumFps: 30,
  },
  contraindications: ['lower-limb pain', 'back pain', 'unsafe surface', 'heat', 'poor AQI'],
  decisionMappings: [
    { domain: 'speed_exposure_readiness', coefficient: 1, maxInfluencePoints: 6 },
    { domain: 'explosive_readiness', coefficient: 0.45, maxInfluencePoints: 2 },
  ],
  alternativesWhenUnsafe: ['reaction_tap'],
}

const agilityProtocol: ObjectiveTestProtocolDefinition = {
  id: 'agility_505',
  family: 'agility',
  displayName: 'Agility 505',
  shortDescription: 'AI pose timing pilot for change-of-direction control and turn quality.',
  analysisMode: 'ai_pose',
  captureMode: 'camera_pose_upload',
  rolloutPhase: 3,
  supportedRoles: ['athlete', 'individual'],
  supportedSports: 'all',
  estimatedDurationMinutes: 6,
  estimatedLoad: 'high',
  heroLabel: 'AI agility timing pilot',
  protocolRules: [
    'Record the full change-of-direction path with visible setup markers.',
    'Use one 505 effort per clip.',
  ],
  setupChecklist: [
    'Leave space before and after the turn point.',
    'Use only on a safe, non-slippery surface.',
  ],
  whenUseful: [
    'You want a pilot AI COD signal in a controlled setup.',
  ],
  whenToSkip: [
    'You are early in rehab or do not have a safe setup.',
  ],
  headlineMetric: {
    key: 'agility_505_time_ms',
    label: '505 time',
    unit: 'ms',
    direction: 'lower_better',
    decimals: 0,
    minimumDetectableChange: 60,
    provisionalThresholds: {
      good: 2800,
      risk: [2801, 3400],
      critical: 3401,
    },
  },
  secondaryMetrics: [
    {
      key: 'left_turn_vs_right_turn_asymmetry_percent',
      label: 'Turn asymmetry',
      unit: '%',
      direction: 'lower_better',
      decimals: 1,
      minimumDetectableChange: 5,
      provisionalThresholds: { good: 8, risk: [8.1, 14], critical: 14.1 },
    },
    {
      key: 'turn_quality_score',
      label: 'Turn quality',
      unit: 'pts',
      direction: 'higher_better',
      decimals: 0,
      minimumDetectableChange: 5,
      provisionalThresholds: { good: 80, risk: [60, 79], critical: 59 },
    },
  ],
  baseline: {
    minimumAcceptedSessions: 3,
    initialMethod: 'first_3_median',
    rollingMethod: 'rolling_5_median',
    minimumDaysBetweenAnchorSessions: 4,
  },
  freshnessWindowHours: 336,
  cooldownHours: 96,
  weeklyCap: 1,
  validityRules: {
    minimumCaptureQuality: 0.65,
    minimumConfidence: 0.62,
    minimumFps: 30,
  },
  contraindications: ['lower-limb pain', 'early rehab', 'unsafe surface'],
  decisionMappings: [
    { domain: 'speed_exposure_readiness', coefficient: 0.8, maxInfluencePoints: 4 },
    { domain: 'postural_control', coefficient: 0.4, maxInfluencePoints: 2 },
    { domain: 'asymmetry_risk', coefficient: 0.6, maxInfluencePoints: 3 },
  ],
  alternativesWhenUnsafe: ['balance_single_leg'],
}

export const OBJECTIVE_TEST_PROTOCOLS = [
  reactionProtocol,
  balanceProtocol,
  breathingProtocol,
  jumpProtocol,
  mobilityProtocol,
  sprintProtocol,
  agilityProtocol,
] as const

export function getObjectiveProtocol(protocolId: string) {
  return OBJECTIVE_TEST_PROTOCOLS.find((protocol) => protocol.id === protocolId) || null
}

export function getProtocolsForRole(role: 'athlete' | 'individual') {
  return OBJECTIVE_TEST_PROTOCOLS.filter((protocol) => protocol.supportedRoles.includes(role))
}
