import * as z from 'zod'

import type { FormFieldDefinition } from '@/forms/types'

const readinessEmojis = [
  { label: 'Very low', value: 1, emoji: '😵' },
  { label: 'Low', value: 2, emoji: '😕' },
  { label: 'Okay', value: 3, emoji: '🙂' },
  { label: 'Good', value: 4, emoji: '💪' },
  { label: 'Peak', value: 5, emoji: '⚡' },
] as const

export const athleteDailyFields: FormFieldDefinition[] = [
  {
    id: 'energy',
    label: 'How is your energy right now?',
    helper: 'This is the strongest single daily readiness signal.',
    inputType: 'emoji',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: ['energyLevel', 'motivation'],
    options: readinessEmojis.map((option) => ({ ...option })),
  },
  {
    id: 'soreness',
    label: 'How heavy does your body feel?',
    helper: 'Think stiffness, soreness, and how springy you feel.',
    inputType: 'emoji',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: ['muscleSoreness', 'painStatus'],
    options: [
      { label: 'None', value: 1, emoji: '🪶' },
      { label: 'Low', value: 2, emoji: '🙂' },
      { label: 'Moderate', value: 3, emoji: '😬' },
      { label: 'High', value: 4, emoji: '🥴' },
      { label: 'Very high', value: 5, emoji: '🩹' },
    ],
  },
  {
    id: 'stress',
    label: 'How heavy does the day feel mentally?',
    helper: 'Life load matters because it changes recovery and execution.',
    inputType: 'emoji',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: ['lifeStress', 'examStressScore'],
    options: [
      { label: 'Very calm', value: 1, emoji: '😌' },
      { label: 'Calm', value: 2, emoji: '🙂' },
      { label: 'Normal', value: 3, emoji: '😐' },
      { label: 'Heavy', value: 4, emoji: '😟' },
      { label: 'Overloaded', value: 5, emoji: '😰' },
    ],
  },
  {
    id: 'sleepQuality',
    label: 'How was last night’s sleep?',
    helper: 'We ask only when your core signals need more explanation.',
    inputType: 'chips',
    category: 'conditional',
    layer: 'layer1',
    required: false,
    backendMappingKey: ['sleepQuality', 'sleepLatency'],
    triggerConditions: [
      { field: 'energy', operator: 'lte', value: 2 },
      { field: 'stress', operator: 'gte', value: 4 },
    ],
    options: [
      { label: 'Poor', value: 1 },
      { label: 'Okay', value: 2 },
      { label: 'Good', value: 4 },
      { label: 'Excellent', value: 5 },
    ],
  },
  {
    id: 'sleepDuration',
    label: 'Roughly how long did you sleep?',
    helper: 'A fast duration band sharpens confidence.',
    inputType: 'chips',
    category: 'conditional',
    layer: 'layer1',
    required: false,
    backendMappingKey: 'sleepDuration',
    triggerConditions: [{ field: 'sleepQuality', operator: 'exists' }],
    options: [
      { label: '< 6h', value: '<6' },
      { label: '6-7h', value: '6-7' },
      { label: '7-8h', value: '7-8' },
      { label: '8-9h', value: '8-9' },
      { label: '9h+', value: '9+' },
    ],
  },
  {
    id: 'painLocation',
    label: 'Where is the issue?',
    helper: 'Only shown when soreness suggests pain protection is needed.',
    inputType: 'body-map',
    category: 'conditional',
    layer: 'layer1',
    required: false,
    backendMappingKey: 'painLocation',
    triggerConditions: [{ field: 'soreness', operator: 'gte', value: 4 }],
    options: [
      { label: 'Neck', value: 'Neck' },
      { label: 'Shoulder', value: 'Shoulder' },
      { label: 'Back', value: 'Back' },
      { label: 'Hip', value: 'Hip' },
      { label: 'Knee', value: 'Knee' },
      { label: 'Ankle', value: 'Ankle' },
    ],
    maxSelections: 2,
  },
  {
    id: 'sessionCompletion',
    label: 'Did you complete the planned session?',
    helper: 'Shown when we need yesterday load to improve today’s call.',
    inputType: 'chips',
    category: 'conditional',
    layer: 'layer1',
    required: false,
    backendMappingKey: 'sessionCompletion',
    triggerConditions: [{ field: 'hasOutstandingTrainingCapture', operator: 'truthy', source: 'context' }],
    options: [
      { label: 'Completed', value: 'completed' },
      { label: 'Competition', value: 'competition' },
      { label: 'Rest day', value: 'rest' },
      { label: 'Missed', value: 'missed' },
    ],
  },
  {
    id: 'sessionRPE',
    label: 'How hard did it feel?',
    helper: 'Only captured if a session happened.',
    inputType: 'slider',
    category: 'conditional',
    layer: 'layer1',
    required: false,
    backendMappingKey: ['yesterdayDemand', 'sessionRPE'],
    triggerConditions: [
      { field: 'sessionCompletion', operator: 'in', value: ['completed', 'competition'] },
    ],
    min: 1,
    max: 10,
    step: 1,
  },
  {
    id: 'sessionDuration',
    label: 'How long was the session?',
    helper: 'Only captured when we need load volume.',
    inputType: 'slider',
    category: 'conditional',
    layer: 'layer1',
    required: false,
    backendMappingKey: ['yesterdayDuration', 'durationMinutes'],
    triggerConditions: [
      { field: 'sessionCompletion', operator: 'in', value: ['completed', 'competition'] },
    ],
    min: 0,
    max: 180,
    step: 5,
    unit: 'min',
  },
  {
    id: 'sessionNotes',
    label: 'Anything unusual today?',
    helper: 'Optional note for edge cases like travel, cramps, or illness.',
    inputType: 'textarea',
    category: 'progressive',
    layer: 'layer2',
    required: false,
    backendMappingKey: 'sessionNotes',
    placeholder: 'Optional',
  },
]

export const athleteDailyQuickSchema = z.object({
  energy: z.number().min(1).max(5),
  soreness: z.number().min(1).max(5),
  stress: z.number().min(1).max(5),
  sleepQuality: z.number().min(1).max(5).optional(),
  sleepDuration: z.enum(['<6', '6-7', '7-8', '8-9', '9+']).optional(),
  painLocation: z.array(z.string()).max(2).optional().default([]),
  sessionCompletion: z.enum(['completed', 'competition', 'rest', 'missed']).optional(),
  sessionRPE: z.number().min(1).max(10).optional(),
  sessionDuration: z.number().min(0).max(180).optional(),
  sessionNotes: z.string().max(300).optional().default(''),
  heatLevel: z.enum(['normal', 'warm', 'hot', 'extreme']).optional(),
  humidityLevel: z.enum(['low', 'moderate', 'high']).optional(),
  aqiBand: z.enum(['good', 'moderate', 'poor', 'very_poor']).optional(),
})

export type AthleteDailyQuickInput = z.infer<typeof athleteDailyQuickSchema>

