import * as z from 'zod'

import { SPORTS_LIST } from '@/lib/constants'
import type { FormFieldDefinition } from '@/forms/types'

export const coachOnboardingFields: FormFieldDefinition[] = [
  {
    id: 'fullName',
    label: 'What should athletes see as your name?',
    helper: 'Usually your professional coaching name.',
    inputType: 'text',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: 'fullName',
    placeholder: 'Coach Anil Kumar',
  },
  {
    id: 'username',
    label: 'Choose your coach handle',
    helper: 'Used for lookup and mentions.',
    inputType: 'text',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: 'username',
    placeholder: 'coach_anil',
  },
  {
    id: 'mobileNumber',
    label: 'WhatsApp or mobile number',
    helper: 'Used for verification and squad coordination.',
    inputType: 'phone',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: 'mobileNumber',
    placeholder: '+91 98XXXX XXXXX',
  },
  {
    id: 'teamName',
    label: 'What is your main squad or setup called?',
    helper: 'You can add more teams later.',
    inputType: 'text',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: 'teamName',
    placeholder: 'Haryana U-19 Fast Bowling Unit',
  },
  {
    id: 'sportCoached',
    label: 'What sport do you coach?',
    helper: 'This anchors the intelligence model and risk language.',
    inputType: 'chips',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: 'sportCoached',
    options: SPORTS_LIST.map((sport) => ({ label: sport, value: sport })),
  },
  {
    id: 'coachingLevel',
    label: 'What best describes your setup?',
    helper: 'This influences how much structure and automation you need.',
    inputType: 'chips',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: 'coachingLevel',
    options: [
      { label: 'Private Pro Coach', value: 'Private Pro Coach' },
      { label: 'Academy / Club Coach', value: 'Academy / Club Coach' },
      { label: 'School / University Coach', value: 'School / University Coach' },
    ],
  },
  {
    id: 'teamType',
    label: 'How do you coach today?',
    helper: 'This determines whether we ask for team structure details.',
    inputType: 'chips',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: 'teamType',
    options: [
      { label: 'Single team', value: 'Single Team' },
      { label: 'Multiple teams / age groups', value: 'Multiple Teams / Age Groups' },
      { label: 'Individual athletes', value: 'Individual Athletes' },
    ],
  },
  {
    id: 'numberOfAthletes',
    label: 'How many athletes are active right now?',
    helper: 'Enough to size the first dashboard correctly.',
    inputType: 'chips',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: 'numberOfAthletes',
    options: [
      { label: '1-5', value: '1-5' },
      { label: '6-15', value: '6-15' },
      { label: '16-30', value: '16-30' },
      { label: '30+', value: '30+' },
    ],
  },
  {
    id: 'mainCoachingFocus',
    label: 'What do you care about most right now?',
    helper: 'This drives the first version of your coach dashboard.',
    inputType: 'chips',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: ['mainCoachingFocus', 'criticalRisks'],
    options: [
      { label: 'Injury Risk Reduction', value: 'Injury Risk Reduction' },
      { label: 'Peak Performance Optimization', value: 'Peak Performance Optimization' },
      { label: 'Player Compliance', value: 'Player Compliance' },
      { label: 'Scouting / Talent ID', value: 'Scouting / Talent ID' },
    ],
  },
  {
    id: 'trainingFrequency',
    label: 'How often do your athletes usually train with you?',
    helper: 'Useful but not essential for fast start.',
    inputType: 'chips',
    category: 'progressive',
    layer: 'layer2',
    required: false,
    backendMappingKey: 'trainingFrequency',
    options: [
      { label: 'Daily', value: 'Daily' },
      { label: '3-4x Weekly', value: '3-4x Weekly' },
      { label: '1-2x Weekly', value: '1-2x Weekly' },
    ],
  },
  {
    id: 'teamStructure',
    label: 'How many groups or age bands do you run?',
    helper: 'Only shown for multi-team setups.',
    inputType: 'text',
    category: 'conditional',
    layer: 'layer2',
    required: false,
    backendMappingKey: 'teamStructure',
    triggerConditions: [{ field: 'teamType', operator: 'eq', value: 'Multiple Teams / Age Groups' }],
    placeholder: 'e.g. U-14, U-17, Senior',
  },
]

export const coachOnboardingFastStartSchema = z.object({
  fullName: z.string().min(2),
  username: z
    .string()
    .min(3)
    .regex(/^[a-zA-Z0-9_]+$/, 'Only letters, numbers, and underscores allowed'),
  mobileNumber: z.string().min(10),
  teamName: z.string().min(2),
  sportCoached: z.enum(SPORTS_LIST),
  coachingLevel: z.enum(['Private Pro Coach', 'Academy / Club Coach', 'School / University Coach']),
  teamType: z.enum(['Single Team', 'Multiple Teams / Age Groups', 'Individual Athletes']),
  numberOfAthletes: z.enum(['1-5', '6-15', '16-30', '30+']),
  mainCoachingFocus: z.enum([
    'Injury Risk Reduction',
    'Peak Performance Optimization',
    'Player Compliance',
    'Scouting / Talent ID',
  ]),
  trainingFrequency: z.enum(['Daily', '3-4x Weekly', '1-2x Weekly']).optional(),
  teamStructure: z.string().optional().default(''),
})

export type CoachOnboardingFastStart = z.infer<typeof coachOnboardingFastStartSchema>
