import * as z from 'zod'

import type { FormFieldDefinition } from '@/forms/types'

export const individualGoalOptions = [
  'fat_loss',
  'muscle_gain',
  'endurance',
  'general_fitness',
  'sport_specific',
] as const

export const individualOnboardingFields: FormFieldDefinition[] = [
  {
    id: 'age',
    label: 'How old are you?',
    helper: 'Age shapes recovery assumptions and progression rate.',
    inputType: 'number',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: 'basic.age',
    min: 13,
    max: 90,
  },
  {
    id: 'gender',
    label: 'Gender',
    helper: 'Used as an optional physiology anchor until real trend data replaces it.',
    inputType: 'chips',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: 'basic.gender',
    options: [
      { label: 'Female', value: 'Female' },
      { label: 'Male', value: 'Male' },
      { label: 'Non-binary', value: 'Non-binary' },
      { label: 'Prefer not to say', value: 'Prefer not to say' },
    ],
  },
  {
    id: 'heightCm',
    label: 'Height',
    helper: 'This keeps the first readiness and nutrition guidance grounded.',
    inputType: 'number',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: 'basic.heightCm',
    min: 120,
    max: 230,
    unit: 'cm',
  },
  {
    id: 'weightKg',
    label: 'Weight',
    helper: 'A quick body-size anchor improves personalization from day one.',
    inputType: 'number',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: 'basic.weightKg',
    min: 30,
    max: 220,
    unit: 'kg',
  },
  {
    id: 'occupation',
    label: 'What does your normal day look like?',
    helper: 'This helps us infer movement, fatigue, and schedule reality.',
    inputType: 'chips',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: ['basic.occupation', 'lifestyle.scheduleConstraints'],
    options: [
      { label: 'Desk / study heavy', value: 'desk_job' },
      { label: 'Mixed day', value: 'mixed_day' },
      { label: 'On feet most of the day', value: 'active_job' },
      { label: 'Shift work', value: 'shift_work' },
    ],
  },
  {
    id: 'activityLevel',
    label: 'How active are you most weeks?',
    helper: 'This gives us a starting point before we learn your real patterns.',
    inputType: 'chips',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: 'basic.activityLevel',
    options: [
      { label: 'Mostly seated', value: 'sedentary' },
      { label: 'Some movement', value: 'moderate' },
      { label: 'Active most days', value: 'active' },
    ],
  },
  {
    id: 'primaryGoal',
    label: 'What are you trying to improve first?',
    helper: 'We’ll optimize the first plan around this.',
    inputType: 'chips',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: 'goals.primaryGoal',
    options: [
      { label: 'Fat loss', value: 'fat_loss' },
      { label: 'Muscle gain', value: 'muscle_gain' },
      { label: 'Endurance', value: 'endurance' },
      { label: 'General fitness', value: 'general_fitness' },
      { label: 'Sport-specific', value: 'sport_specific' },
    ],
  },
  {
    id: 'timeHorizon',
    label: 'When do you want to feel a real change?',
    helper: 'A short time horizon creates a more focused first plan.',
    inputType: 'chips',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: 'goals.timeHorizon',
    options: [
      { label: '4 weeks', value: '4_weeks' },
      { label: '8 weeks', value: '8_weeks' },
      { label: '12 weeks', value: '12_weeks' },
      { label: 'Long term', value: 'long_term' },
    ],
  },
  {
    id: 'intensityPreference',
    label: 'How hard do you want this to feel?',
    helper: 'Useful for adherence, not just intensity.',
    inputType: 'chips',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: 'goals.intensityPreference',
    options: [
      { label: 'Low', value: 'low' },
      { label: 'Moderate', value: 'moderate' },
      { label: 'High', value: 'high' },
    ],
  },
  {
    id: 'equipmentAccess',
    label: 'What can you reliably use?',
    helper: 'We only need the options you can count on every week.',
    inputType: 'multi-chip',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: 'lifestyle.equipmentAccess',
    options: [
      { label: 'Bodyweight', value: 'bodyweight' },
      { label: 'Home weights', value: 'home_dumbbells' },
      { label: 'Gym access', value: 'gym' },
      { label: 'Cardio machine', value: 'cardio_machine' },
      { label: 'Pool', value: 'pool' },
    ],
    maxSelections: 4,
  },
  {
    id: 'injuryStatus',
    label: 'Any pain, injury, or movement limitation right now?',
    helper: 'We only ask more if you say yes.',
    inputType: 'chips',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: ['physiology.injuryHistory', 'physiology.mobilityLimitations'],
    options: [
      { label: 'No', value: 'none' },
      { label: 'Yes, a little', value: 'minor' },
      { label: 'Yes, moderate', value: 'moderate' },
      { label: 'Yes, major', value: 'major' },
      { label: 'Yes, long-term', value: 'chronic' },
    ],
  },
  {
    id: 'limitationArea',
    label: 'Where is it affecting you most?',
    helper: 'Choose the main area only.',
    inputType: 'body-map',
    category: 'conditional',
    layer: 'layer1',
    required: false,
    backendMappingKey: 'physiology.mobilityLimitationsArea',
    triggerConditions: [{ field: 'injuryStatus', operator: 'ne', value: 'none' }],
    options: [
      { label: 'Shoulder', value: 'Shoulder' },
      { label: 'Back', value: 'Back' },
      { label: 'Hip', value: 'Hip' },
      { label: 'Knee', value: 'Knee' },
      { label: 'Ankle', value: 'Ankle' },
    ],
    maxSelections: 2,
  },
  {
    id: 'trainingExperience',
    label: 'How much structured training experience do you have?',
    helper: 'Helpful later for progression accuracy.',
    inputType: 'chips',
    category: 'progressive',
    layer: 'layer2',
    required: false,
    backendMappingKey: 'physiology.trainingExperience',
    options: [
      { label: 'Brand new', value: 'beginner' },
      { label: 'A little', value: 'novice' },
      { label: 'Some consistency', value: 'intermediate' },
      { label: 'Very consistent', value: 'advanced' },
      { label: 'Long-term', value: 'experienced' },
    ],
  },
  {
    id: 'sleepBaseline',
    label: 'What is your normal sleep quality?',
    helper: 'This improves early recovery recommendations but is not essential to start.',
    inputType: 'slider',
    category: 'progressive',
    layer: 'layer2',
    required: false,
    backendMappingKey: ['physiology.sleepQuality', 'physiology.energyLevels'],
    min: 1,
    max: 5,
    step: 1,
  },
]

export const individualOnboardingFastStartSchema = z.object({
  age: z.number().min(13).max(90),
  gender: z.string().min(1),
  heightCm: z.number().min(120).max(230),
  weightKg: z.number().min(30).max(220),
  occupation: z.enum(['desk_job', 'mixed_day', 'active_job', 'shift_work']),
  activityLevel: z.enum(['sedentary', 'moderate', 'active']),
  primaryGoal: z.enum(individualGoalOptions),
  timeHorizon: z.enum(['4_weeks', '8_weeks', '12_weeks', 'long_term']),
  intensityPreference: z.enum(['low', 'moderate', 'high']),
  equipmentAccess: z.array(z.enum(['bodyweight', 'home_dumbbells', 'gym', 'cardio_machine', 'pool'])).min(1),
  injuryStatus: z.enum(['none', 'minor', 'moderate', 'major', 'chronic']),
  limitationArea: z.array(z.string()).max(2).optional().default([]),
})

export type IndividualOnboardingFastStart = z.infer<typeof individualOnboardingFastStartSchema>

