import * as z from 'zod'

import type { FormFieldDefinition } from '@/forms/types'

export const individualDailyFields: FormFieldDefinition[] = [
  {
    id: 'energy',
    label: 'How is your energy right now?',
    helper: 'A fast signal for how trainable today feels.',
    inputType: 'emoji',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: 'energy_level',
    options: [
      { label: 'Empty', value: 1, emoji: '🪫' },
      { label: 'Low', value: 2, emoji: '😕' },
      { label: 'Okay', value: 3, emoji: '🙂' },
      { label: 'Good', value: 4, emoji: '💪' },
      { label: 'Very high', value: 5, emoji: '⚡' },
    ],
  },
  {
    id: 'stress',
    label: 'How heavy does life feel today?',
    helper: 'Work, study, family, and travel all count.',
    inputType: 'emoji',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: 'stress_level',
    options: [
      { label: 'Very calm', value: 1, emoji: '😌' },
      { label: 'Calm', value: 2, emoji: '🙂' },
      { label: 'Normal', value: 3, emoji: '😐' },
      { label: 'Heavy', value: 4, emoji: '😟' },
      { label: 'Overloaded', value: 5, emoji: '😰' },
    ],
  },
  {
    id: 'soreness',
    label: 'How does your body feel?',
    helper: 'Use soreness to capture how ready you feel physically.',
    inputType: 'emoji',
    category: 'baseline',
    layer: 'layer1',
    required: true,
    backendMappingKey: ['soreness_level', 'recovery_feel'],
    options: [
      { label: 'Fresh', value: 1, emoji: '🪶' },
      { label: 'Light soreness', value: 2, emoji: '🙂' },
      { label: 'Moderate', value: 3, emoji: '😬' },
      { label: 'Heavy', value: 4, emoji: '🥴' },
      { label: 'Very heavy', value: 5, emoji: '🩹' },
    ],
  },
  {
    id: 'sleepQuality',
    label: 'How was last night’s sleep?',
    helper: 'We ask only when energy or stress needs more context.',
    inputType: 'chips',
    category: 'conditional',
    layer: 'layer1',
    required: false,
    backendMappingKey: 'sleep_quality',
    triggerConditions: [
      { field: 'energy', operator: 'lte', value: 2 },
      { field: 'stress', operator: 'gte', value: 4 },
    ],
    options: [
      { label: 'Poor', value: 1 },
      { label: 'Okay', value: 3 },
      { label: 'Good', value: 4 },
      { label: 'Excellent', value: 5 },
    ],
  },
  {
    id: 'sessionCompletion',
    label: 'Did you train today?',
    helper: 'Only shown if you want the plan to learn from today’s activity.',
    inputType: 'chips',
    category: 'conditional',
    layer: 'layer1',
    required: false,
    backendMappingKey: 'session_completion',
    triggerConditions: [{ field: 'trackTrainingToday', operator: 'truthy', source: 'context' }],
    options: [
      { label: 'Missed', value: 'missed' },
      { label: 'Partial', value: 'partial' },
      { label: 'Complete', value: 'complete' },
      { label: 'Crushed it', value: 'crushed' },
    ],
  },
  {
    id: 'trainingMinutes',
    label: 'How many minutes did you train?',
    helper: 'Only asked if a session happened.',
    inputType: 'slider',
    category: 'conditional',
    layer: 'layer1',
    required: false,
    backendMappingKey: 'training_minutes',
    triggerConditions: [{ field: 'sessionCompletion', operator: 'in', value: ['partial', 'complete', 'crushed'] }],
    min: 0,
    max: 180,
    step: 5,
    unit: 'min',
  },
  {
    id: 'sessionRPE',
    label: 'How hard did it feel?',
    helper: 'This turns minutes into useful load context.',
    inputType: 'slider',
    category: 'conditional',
    layer: 'layer1',
    required: false,
    backendMappingKey: 'session_rpe',
    triggerConditions: [{ field: 'sessionCompletion', operator: 'in', value: ['partial', 'complete', 'crushed'] }],
    min: 1,
    max: 10,
    step: 1,
  },
  {
    id: 'hydrationLiters',
    label: 'How much water did you drink?',
    helper: 'Optional for people who want tighter recovery guidance.',
    inputType: 'slider',
    category: 'progressive',
    layer: 'layer2',
    required: false,
    backendMappingKey: 'hydration_liters',
    min: 0,
    max: 6,
    step: 0.25,
    unit: 'L',
  },
]

export const individualDailyQuickSchema = z.object({
  energy: z.number().min(1).max(5),
  stress: z.number().min(1).max(5),
  soreness: z.number().min(1).max(5),
  sleepQuality: z.number().min(1).max(5).optional(),
  sessionCompletion: z.enum(['missed', 'partial', 'complete', 'crushed']).optional(),
  trainingMinutes: z.number().min(0).max(180).optional(),
  sessionRPE: z.number().min(1).max(10).optional(),
  hydrationLiters: z.number().min(0).max(6).optional(),
  steps: z.number().min(0).max(100000).optional(),
  heatLevel: z.enum(['normal', 'warm', 'hot', 'extreme']).optional(),
  humidityLevel: z.enum(['low', 'moderate', 'high']).optional(),
  aqiBand: z.enum(['good', 'moderate', 'poor', 'very_poor']).optional(),
})

export type IndividualDailyQuickInput = z.infer<typeof individualDailyQuickSchema>

