import LegalLayout from '@/components/LegalLayout';

export default function DisclaimerPage() {
  return (
    <LegalLayout title="Medical & Performance Disclaimer">
      <p>Last Updated: March 19, 2026</p>
      
      <div className="bg-amber-50 border-l-4 border-amber-500 p-4 my-8">
        <p className="text-amber-800 font-bold mb-0 text-xs uppercase tracking-widest">CRITICAL NOTICE</p>
        <p className="text-amber-900 font-black mb-1">CREEDA is a performance intelligence advisory platform, NOT a medical device.</p>
        <p className="text-amber-800 text-[10px] leading-tight font-medium">EMERGENCY: If severe pain, acute symptoms, or unusual physiological markers are detected, immediate professional medical evaluation is mandatory. Do not rely on platform scores for emergency triage.</p>
      </div>

      <p>CREEDA provides advanced decision-support intelligence through its proprietary <strong>Intelligence Engine</strong>. This system processes subjective athlete inputs (wellness, load, recovery) and objective diagnostics to provide advisory performance insights.</p>
      
      <h3>1. Not a Substitute for Medical Advice</h3>
      <p>The readiness scores, trend alerts, and <strong>Performance Risk Outlook</strong> generated by CREEDA do not constitute medical diagnosis, treatment, or advice. Always seek the advice of a physician or qualified health provider. Never disregard professional medical advice because of information provided by our Intelligence Engine.</p>
      
      <h3>2. Physiology Profiling & Diagnostics</h3>
      <p>Physiology profiling (Speed, Agility, Reaction Time, etc.) represents a functional snapshot at a specific point in time. These metrics are used for performance calibration and are not intended to screen for, diagnose, or monitor any underlying medical conditions or pathologies.</p>

      <h3>3. Coach & Athlete Responsibility</h3>
      <p>The final decision regarding an athlete's participation, training intensity, and recovery protocol remains exclusively with the coach and the athlete's authorized medical staff. CREEDA provides data-driven support but does not replace professional human judgment.</p>
      
      <h3>4. Accuracy of Inputs</h3>
      <p>Intelligence accuracy depends entirely on honest and consistent input from the athlete. CREEDA is not responsible for unsafe training decisions or injuries resulting from untruthful, inconsistent, or manipulated reporting of symptoms, pain, or fatigue.</p>
      
      <h3>5. Assumption of Risk</h3>
      <p>Elite sports involve inherent risk of injury. By using CREEDA, users acknowledge that the platform is a tool to help <em>manage</em> and <em>visualize</em> that risk, not eliminate it entirely.</p>
    </LegalLayout>
  );
}
